// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.GI.Voxel.Voxelization;
import Core;
import :Autogen.Tables.GI.Voxel.Voxelization;
import :Autogen.Layouts.Frame.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace GI
	{
		namespace Voxel
		{
			struct Voxelization :public DataHolder<Voxelization, SlotID::Voxelization, Table::GI::Voxel::Voxelization, ::Frame::DefaultLayout::Instance3>
			{
				static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
				Voxelization() = default;
			};
		}
	}
}