// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "../../PassNodeBase.h"

using namespace FrameGraph;

namespace Passes
{
namespace Editor
{

	class stencil_renderer : public PassNodeBase
	{
	public:
		struct Context
		{


			Handlers::Texture GBuffer_ObjectID = ResourceID::GBuffer_ObjectID;


			Handlers::Texture ResultTexture = ResourceID::ResultTexture;


			Handlers::StructuredBuffer<UINT> axis_id_buffer = ResourceID::axis_id_buffer;


			// Resources this pass always needs whenever it runs, generated from
			// each field's own [Always=X] annotation (further gated by [Optional=X]
			// when present -- a raw bool expression, e.g. builder.exists(...) or a
			// context-read flag, deciding whether this specific field is actually
			// needed this frame), or, for a View-typed field (e.g. `GBuffer
			// gbuffer;`), every leaf the View itself marks [Always=X] that this
			// pass's own [Write=...] on that field doesn't already cover. A field
			// that ALSO carries [Size]/[Format] (so create_always() below creates
			// it under its own [Optional] condition) gets the negated condition
			// here instead -- "need what some other instance/frame already
			// created" is the complement of "create it this time." Called by
			// TypedPass::setup() after setup_func returns true - not a
			// substitute for setup_func's own need()/create() calls for anything
			// else conditional.
			static void need_always(Context& data, FrameGraph::TaskBuilder& builder)
			{
				builder.need(data.GBuffer_ObjectID, FrameGraph::ResourceFlags::Read);
				builder.need(data.ResultTexture, FrameGraph::ResourceFlags::RenderTarget);
			}

			// Resources this pass always creates with a fixed desc, generated from
			// each field's own [Size]/[Format] annotation (plus [Always] for the
			// creation flags, or [Always]+[Recreate]+[RecreateFlags] for a field
			// that needs its original chain link before recreating a new one). A
			// field that ALSO carries [Optional] creates only under that
			// condition -- need_always() (above) emits a complementary need() for
			// the SAME field under the negated condition, using the same
			// [Always] flags, e.g. a [Multiple] pass where instance 0 creates a
			// shared resource and every other instance just needs it (see
			// PSSM_Cascade, pssm.prism). Called by TypedPass::setup() after
			// setup_func returns true - not a substitute for setup_func's own
			// create()/recreate() calls for anything whose Desc depends on
			// runtime state.
			static void create_always(Context& data, FrameGraph::TaskBuilder& builder)
			{
				builder.create(data.axis_id_buffer, { 1 }, FrameGraph::ResourceFlags::UnorderedAccess);
			}
			// Which chain link each handler field resolved to, one named slot per
			// field. Filled from a live frame's finished Context and applied on a
			// replayed one, so a replay neither re-runs create_always/need_always nor
			// depends on the order they made their calls in. The id is not stored:
			// the field fixes it.
			struct Cache
			{
				FrameGraph::ChainIndex GBuffer_ObjectID = FrameGraph::ChainIndex::Unresolved;
				FrameGraph::ChainIndex ResultTexture = FrameGraph::ChainIndex::Unresolved;
				FrameGraph::ChainIndex axis_id_buffer = FrameGraph::ChainIndex::Unresolved;
			};

			static void save_to_cache([[maybe_unused]] const Context& data, [[maybe_unused]] Cache& cache)
			{
				cache.GBuffer_ObjectID = FrameGraph::TaskBuilder::cache_slot(data.GBuffer_ObjectID, ResourceID::GBuffer_ObjectID);
				cache.ResultTexture = FrameGraph::TaskBuilder::cache_slot(data.ResultTexture, ResourceID::ResultTexture);
				cache.axis_id_buffer = FrameGraph::TaskBuilder::cache_slot(data.axis_id_buffer, ResourceID::axis_id_buffer);
			}

			// Replay counterpart of create_always/need_always. A field this pass
			// creates gets its desc recomputed on the link the cache names, so descs
			// follow the current context instead of being stored in the plan; every
			// other field is only pointed at its link. Each link is created by exactly
			// one pass and nothing here reads another resource's desc, so passes can
			// load in any order. A [Recreate] without [Size]/[Format] copies the
			// previous link's desc, which LoadGraph does once every pass has loaded.
			static void load_from_cache([[maybe_unused]] Context& data, [[maybe_unused]] const Cache& cache, [[maybe_unused]] const FrameGraph::TaskBuilder& builder)
			{
				builder.load(data.GBuffer_ObjectID, ResourceID::GBuffer_ObjectID, cache.GBuffer_ObjectID);
				builder.load(data.ResultTexture, ResourceID::ResultTexture, cache.ResultTexture);
				builder.create_versioned(data.axis_id_buffer, cache.axis_id_buffer, { 1 });
			}

			// Resources this pass touches, in declaration order, each paired with
			// whether the pass writes it (own [Write], or the view usage's
			// [Write] / [Write = {leaves...}] for resources inside a view group).
			static inline const FrameGraph::ResourceAccess resource_accesses[] = {
				{ ResourceID::GBuffer_ObjectID, false },
				{ ResourceID::ResultTexture, true },
				{ ResourceID::axis_id_buffer, true },
			};
			static constexpr uint resource_count = std::size(resource_accesses);
		};


		std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
		{
			return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
		}

		static constexpr LiteralWStr Name{L"stencil_renderer"};

		static constexpr PassID ID = PassID::stencil_renderer;


		using setup_func_type = std::function<FrameGraph::SetupResult(Context&, FrameGraph::TaskBuilder&)>;
		using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;

		render_func_type render_func;

		const FrameGraph::PassFlags flags = FrameGraph::PassFlags::Required;
	};
}

}
