// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Tables.Denoise.NRD.SIGMA_SmoothTilesResources;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
import :Autogen.Tables.Denoise.NRD.SIGMASharedConstants;
export namespace Table
{
	#pragma pack(push, 1)
	namespace Denoise
	{
		namespace NRD
		{
			struct SIGMA_SmoothTilesResources
			{
				static constexpr SlotID ID = SlotID::SIGMA_SmoothTilesResources;
				HLSL::Texture2D<float3> gIn_Tiles;
				HLSL::RWTexture2D<float2> gOut_Tiles;
				Table::Denoise::NRD::SIGMASharedConstants sharedConstants;
				HLSL::Texture2D<float3>& GetGIn_Tiles() { return gIn_Tiles; }
				HLSL::RWTexture2D<float2>& GetGOut_Tiles() { return gOut_Tiles; }
				Table::Denoise::NRD::SIGMASharedConstants& GetSharedConstants() { return sharedConstants; }
				static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
				template<class Compiler>
				void compile(Compiler& compiler) const
				{
					compiler.compile(gIn_Tiles, "SIGMA_SmoothTilesResources::gIn_Tiles");
					compiler.compile(gOut_Tiles, "SIGMA_SmoothTilesResources::gOut_Tiles");
					compiler.compile(sharedConstants, "SIGMA_SmoothTilesResources::sharedConstants");
				}
				struct Compiled
				{
					uint gIn_Tiles; // Texture2D<float3>
					uint gOut_Tiles; // RWTexture2D<float2>
					Table::Denoise::NRD::SIGMASharedConstants::Compiled sharedConstants; // SIGMASharedConstants

			
					private:
					SERIALIZE()
					{
						ar& NVP(sharedConstants);
					}


				};

				static std::string get_typename()
				{
					return "Tables::SIGMA_SmoothTilesResources";
				}
				private:
				SERIALIZE()
				{
					ar& NVP(sharedConstants);
				}

			};
		}
	}
	#pragma pack(pop)
}

