// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.UI.Text.FontRenderingConstants;
import Core;
import :Autogen.Tables.UI.Text.FontRenderingConstants;
import :Autogen.Layouts.Frame.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace UI
	{
		namespace Text
		{
			struct FontRenderingConstants :public DataHolder<FontRenderingConstants, SlotID::FontRenderingConstants, Table::UI::Text::FontRenderingConstants, ::Frame::DefaultLayout::Instance1>
			{
				static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
				FontRenderingConstants() = default;
			};
		}
	}
}