// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.PSO.UI.Text.GlyphRender;

import Core;
import :PSO;
import :Enums;
import :Types;


export namespace PSOS
{
	namespace UI
	{
		namespace Text
		{
			struct GlyphRender: public PSOBase
			{
				struct Keys {
					GEN_DEF_COMP(Keys);
				private:
					SERIALIZE()
					{
					}
				};

				GEN_GRAPHICS_PSO(GlyphRender)


				SimplePSO init_pso(Keys & key, std::function<void(SimplePSO&, Keys&)> f)
				{


					SimplePSO mpso("GlyphRender");
					if(f) f(mpso,key);

					mpso.root_signature = Layouts::DefaultLayout;

					mpso.vertex.file_name = "shaders/gui/glyph.hlsl";
					mpso.vertex.entry_point = "VS";
					mpso.vertex.flags = HAL::ShaderOptions::None;
			
					mpso.pixel.file_name = "shaders/gui/glyph.hlsl";
					mpso.pixel.entry_point = "PS";
					mpso.pixel.flags = HAL::ShaderOptions::None;
			

					mpso.rtv_formats = { HAL::Format::R16G16B16A16_FLOAT };	
					mpso.blend = { HAL::Blends::AlphaBlend };

					mpso.cull =HAL::CullMode::None;
					return mpso;
				}

				private:
				SERIALIZE()
				{
					ar&NVP(wrap(psos));
				}
			};
		}
	}
}