// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.PSO.UI.Text.GlyphRender;

import Core;
import :PSO;
import :Enums;
import :Types;


export namespace PSOS
{
	namespace UI
	{
		namespace Text
		{
			struct GlyphRender: public PSOBase
			{
				struct Keys {
					KeyValue<Underlying<HAL::Format>, NonNullable, ALL_RT_BLENDING_FORMATS> Format;
					GEN_DEF_COMP(Keys);
				private:
					SERIALIZE()
					{
						ar&NVP(Format);
					}
				};

				GEN_GRAPHICS_PSO(GlyphRender, Format)
				GEN_KEY(Format, true);


				SimplePSO init_pso(Keys & key, std::function<void(SimplePSO&, Keys&)> f)
				{
					static const ShaderDefine<&Keys::Format,&SimpleGraphicsPSO::pixel> Format = "Format";


					SimplePSO mpso("GlyphRender");
					if(f) f(mpso,key);

					mpso.root_signature = Layouts::DefaultLayout;

					mpso.vertex.file_name = "shaders/gui/glyph.hlsl";
					mpso.vertex.entry_point = "VS";
					mpso.vertex.flags = HAL::ShaderOptions::None;
			
					mpso.pixel.file_name = "shaders/gui/glyph.hlsl";
					mpso.pixel.entry_point = "PS";
					mpso.pixel.flags = HAL::ShaderOptions::None;
			
					Format.Apply(mpso, key);

					mpso.rtv_formats = { Format.get_value(mpso, key) };	
					mpso.blend = { HAL::Blends::AlphaBlend };

					mpso.cull =HAL::CullMode::None;
					return mpso;
				}

				private:
				SERIALIZE()
				{
					ar&NVP(wrap(psos));
				}
			};
		}
	}
}