// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once

#include "../tables/GraphInput.h"
#include "../tables/TileRecord.h"
#include "../tables/TileRecord.h"

#ifdef WORKGRAPH_EMULATION
// ============================================================
// Emulation mode: compute shader stubs for WorkGraph nodes
// ============================================================
#include "../WorkGREmulation.h"

// Broadcasting entry node input wrappers

#ifndef WG_EMUL_DISPATCH_INPUT_GraphInput
#define WG_EMUL_DISPATCH_INPUT_GraphInput
struct WGEmul_DispatchInput_GraphInput {
    GraphInput Get() { return GetWorkGREmulation().GetGraphInput(); }
};
#endif

// Thread node input wrappers (via ConsumeStructuredBuffer in SIG emulation table)

#ifndef WG_EMUL_THREAD_INPUT_TileRecord
#define WG_EMUL_THREAD_INPUT_TileRecord
struct WGEmul_ThreadInput_TileRecord {
    TileRecord Get() { return GetWorkGREmulation().GetTileRecordConsume().Consume(); }
};
#endif

// Output record wrappers (write via AppendStructuredBuffer in SIG emulation table)

#ifndef WG_EMUL_OUT_RECORDS_TileRecord
#define WG_EMUL_OUT_RECORDS_TileRecord
struct WGEmul_OutRecords_TileRecord {
    TileRecord _data;
    int _count;
    void OutputComplete() { if (_count > 0) GetWorkGREmulation().GetTileRecordAppend().Append(_data); }
};
#endif

// Unified API macros
#define WG_DISPATCH_INPUT(T) WGEmul_DispatchInput_##T
#define WG_THREAD_INPUT(T) WGEmul_ThreadInput_##T
#define WG_OUTPUT_RECORDS(T, r, src, n) WGEmul_OutRecords_##T r; r._count = (n)
#define WG_SET_RECORD(r, field, val) r._data.field = val
#define WG_OUTPUT_COMPLETE(r) r.OutputComplete()

// Node output parameter macros (emulation: empty - UAVs are globally bound)

#define WG_NODE_OUTPUT_ClassifyPixels_Node
#define WG_NODE_OUTPUT_Shadows_Node

// Node function attribute macros (emulation: plain compute shaders)

#define NODE_ClassifyPixels_Node [numthreads(64,1,1)] void ClassifyPixels_Node

#define NODE_Shadows_Node [numthreads(1,1,1)] void Shadows_Node


// Recover original 3D group ID from YZ-chunked dispatch
uint3 WG_GetGroupID(uint3 rawGroupID)
{
    uint yz_linear = CreateWorkGREmulation().GetYZBase() + rawGroupID.y;
    uint WY        = (uint)CreateWorkGREmulation().GetGraphInput().GetDispatch_grid().y;
    return uint3(rawGroupID.x, yz_linear % WY, yz_linear / WY);
}

#else // !WORKGRAPH_EMULATION
// ============================================================
// Native WorkGraph mode
// ============================================================

// Unified API macros
#define WG_DISPATCH_INPUT(T) DispatchNodeInputRecord<T>
#define WG_THREAD_INPUT(T) ThreadNodeInputRecord<T>
#define WG_OUTPUT_RECORDS(T, r, src, n) ThreadNodeOutputRecords<T> r = src.GetThreadNodeOutputRecords(n)
#define WG_SET_RECORD(r, field, val) r[0].field = val
#define WG_OUTPUT_COMPLETE(r) r.OutputComplete()

// Node output parameter macros (native: NodeOutput parameters with MaxRecords)

#define WG_NODE_OUTPUT_ClassifyPixels_Node , [MaxRecords(64)] NodeOutput<TileRecord> Shadows_Node
#define WG_NODE_OUTPUT_Shadows_Node 

// Node function attribute macros (native: full WorkGraph attributes)
#define NODE_ClassifyPixels_Node [Shader("node")][NodeLaunch("broadcasting")][NodeIsProgramEntry][NodeMaxDispatchGrid(256,64,64)][numthreads(64,1,1)] void ClassifyPixels_Node
#define NODE_Shadows_Node [Shader("node")][NodeLaunch("thread")] void Shadows_Node


// Native mode: group ID is already correct
uint3 WG_GetGroupID(uint3 rawGroupID) { return rawGroupID; }

#endif // WORKGRAPH_EMULATION
