// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.GI.DDGI.DDGIInfo;
import Core;
import :Autogen.Tables.GI.DDGI.DDGIInfo;
import :Autogen.Layouts.Frame.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace GI
	{
		namespace DDGI
		{
			struct DDGIInfo :public DataHolder<DDGIInfo, SlotID::DDGIInfo, Table::GI::DDGI::DDGIInfo, ::Frame::DefaultLayout::Instance0>
			{
				static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
				DDGIInfo() = default;
			};
		}
	}
}