vcpkg install zlib:x64-windows
vcpkg install bzip2:x64-windows
vcpkg install zstd:x64-windows
vcpkg install liblzma:x64-windows
vcpkg install directxtex:x64-windows
vcpkg install assimp:x64-windows
vcpkg install boost-serialization:x64-windows
vcpkg install boost-program-options:x64-windows
vcpkg install boost-lockfree:x64-windows
vcpkg install boost-stacktrace:x64-windows
vcpkg install boost-spirit:x64-windows
vcpkg install antlr4:x64-windows