// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Tables.Clear_UInt4Resources;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)
	struct Clear_UInt4Resources
	{
		static constexpr SlotID ID = SlotID::Clear_UInt4Resources;
		HLSL::RWTexture2D<uint4> gOut;
		HLSL::RWTexture2D<uint4>& GetGOut() { return gOut; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(gOut, "Clear_UInt4Resources::gOut");
		}
		struct Compiled
		{
			uint gOut; // RWTexture2D<uint4>

			
			private:
			SERIALIZE()
			{
			}


		};

		static std::string get_typename()
		{
			return "Tables::Clear_UInt4Resources";
		}
		private:
		SERIALIZE()
		{
		}

	};
	#pragma pack(pop)
}

