// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.Color;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)
	struct Color
	{
		static constexpr SlotID ID = SlotID::Color;
		float4 color;
		float4& GetColor() { return color; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(color);
		}
		using Compiled = Color;

		static std::string get_typename()
		{
			return "Tables::Color";
		}
		private:
		SERIALIZE()
		{
			ar& NVP(color);
		}

	};
	#pragma pack(pop)
}

