// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.Countour;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)

	struct Countour
	{
		static constexpr SlotID ID = SlotID::Countour;
		float4 color;
		HLSL::Texture2D<float4> tex;
		float4& GetColor() { return color; }
		HLSL::Texture2D<float4>& GetTex() { return tex; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(color);
			compiler.compile(tex);
		}
		struct Compiled
		{
			float4 color; // float4
			uint tex; // Texture2D<float4>

			
			private:
			SERIALIZE()
			{
				ar& NVP(color);
			}


		};

		static std::string get_typename()
		{
			return "Tables::Countour";
		}
		private:
		SERIALIZE()
		{
			ar& NVP(color);
		}

	};
	#pragma pack(pop)
}

