// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.DDGIDebugData;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
import :Autogen.Tables.DDGIInfo;
import :Autogen.Tables.DDGIProbes;
export namespace Table
{
	#pragma pack(push, 1)
	struct DDGIDebugData
	{
		static constexpr SlotID ID = SlotID::DDGIDebugData;
		HLSL::Texture2D<float> depth;
		HLSL::Texture2D<float4> probe_irradiance;
		HLSL::StructuredBuffer<uint> probe_residency;
		HLSL::RWTexture2D<float4> target;
		DDGIInfo cascade0;
		DDGIInfo cascade1;
		DDGIInfo cascade2;
		DDGIInfo cascade3;
		DDGIInfo cascade4;
		DDGIProbes probes;
		HLSL::Texture2D<float>& GetDepth() { return depth; }
		HLSL::Texture2D<float4>& GetProbe_irradiance() { return probe_irradiance; }
		HLSL::StructuredBuffer<uint>& GetProbe_residency() { return probe_residency; }
		HLSL::RWTexture2D<float4>& GetTarget() { return target; }
		DDGIInfo& GetCascade0() { return cascade0; }
		DDGIInfo& GetCascade1() { return cascade1; }
		DDGIInfo& GetCascade2() { return cascade2; }
		DDGIInfo& GetCascade3() { return cascade3; }
		DDGIInfo& GetCascade4() { return cascade4; }
		DDGIProbes& GetProbes() { return probes; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(depth, "DDGIDebugData::depth");
			compiler.compile(probe_irradiance, "DDGIDebugData::probe_irradiance");
			compiler.compile(probe_residency, "DDGIDebugData::probe_residency");
			compiler.compile(target, "DDGIDebugData::target");
			compiler.compile(cascade0, "DDGIDebugData::cascade0");
			compiler.compile(cascade1, "DDGIDebugData::cascade1");
			compiler.compile(cascade2, "DDGIDebugData::cascade2");
			compiler.compile(cascade3, "DDGIDebugData::cascade3");
			compiler.compile(cascade4, "DDGIDebugData::cascade4");
			compiler.compile(probes, "DDGIDebugData::probes");
		}
		struct Compiled
		{
			uint depth; // Texture2D<float>
			uint probe_irradiance; // Texture2D<float4>
			uint probe_residency; // StructuredBuffer<uint>
			uint target; // RWTexture2D<float4>
			DDGIInfo::Compiled cascade0; // DDGIInfo
			DDGIInfo::Compiled cascade1; // DDGIInfo
			DDGIInfo::Compiled cascade2; // DDGIInfo
			DDGIInfo::Compiled cascade3; // DDGIInfo
			DDGIInfo::Compiled cascade4; // DDGIInfo
			DDGIProbes::Compiled probes; // DDGIProbes

			
			private:
			SERIALIZE()
			{
				ar& NVP(cascade0);
				ar& NVP(cascade1);
				ar& NVP(cascade2);
				ar& NVP(cascade3);
				ar& NVP(cascade4);
				ar& NVP(probes);
			}


		};

		static std::string get_typename()
		{
			return "Tables::DDGIDebugData";
		}
		private:
		SERIALIZE()
		{
			ar& NVP(cascade0);
			ar& NVP(cascade1);
			ar& NVP(cascade2);
			ar& NVP(cascade3);
			ar& NVP(cascade4);
			ar& NVP(probes);
		}

	};
	#pragma pack(pop)
}

