// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.DDGIProbeSelectData;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
import :Autogen.Tables.DDGIInfo;
import :Autogen.Tables.DDGIProbes;
export namespace Table
{
	#pragma pack(push, 1)
	struct DDGIProbeSelectData
	{
		static constexpr SlotID ID = SlotID::DDGIProbeSelectData;
		DDGIInfo info;
		DDGIProbes probes;
		DDGIInfo& GetInfo() { return info; }
		DDGIProbes& GetProbes() { return probes; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(info, "DDGIProbeSelectData::info");
			compiler.compile(probes, "DDGIProbeSelectData::probes");
		}
		using Compiled = DDGIProbeSelectData;

		static std::string get_typename()
		{
			return "Tables::DDGIProbeSelectData";
		}
		private:
		SERIALIZE()
		{
			ar& NVP(info);
			ar& NVP(probes);
		}

	};
	#pragma pack(pop)
}

