// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.DDGIProbeResidencyMarkData;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
import :Autogen.Tables.DDGIInfo;
export namespace Table
{
	#pragma pack(push, 1)
	struct DDGIProbeResidencyMarkData
	{
		static constexpr SlotID ID = SlotID::DDGIProbeResidencyMarkData;
		uint reset_only;
		HLSL::RWStructuredBuffer<uint> probe_residency;
		HLSL::RWStructuredBuffer<uint> compacted_list;
		HLSL::RWStructuredBuffer<uint> compacted_count;
		HLSL::RWStructuredBuffer<uint> pending;
		HLSL::RWStructuredBuffer<uint> miss_streak;
		DDGIInfo info;
		HLSL::RWStructuredBuffer<uint>& GetProbe_residency() { return probe_residency; }
		HLSL::RWStructuredBuffer<uint>& GetCompacted_list() { return compacted_list; }
		HLSL::RWStructuredBuffer<uint>& GetCompacted_count() { return compacted_count; }
		HLSL::RWStructuredBuffer<uint>& GetPending() { return pending; }
		HLSL::RWStructuredBuffer<uint>& GetMiss_streak() { return miss_streak; }
		uint& GetReset_only() { return reset_only; }
		DDGIInfo& GetInfo() { return info; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(reset_only, "DDGIProbeResidencyMarkData::reset_only");
			compiler.compile(probe_residency, "DDGIProbeResidencyMarkData::probe_residency");
			compiler.compile(compacted_list, "DDGIProbeResidencyMarkData::compacted_list");
			compiler.compile(compacted_count, "DDGIProbeResidencyMarkData::compacted_count");
			compiler.compile(pending, "DDGIProbeResidencyMarkData::pending");
			compiler.compile(miss_streak, "DDGIProbeResidencyMarkData::miss_streak");
			compiler.compile(info, "DDGIProbeResidencyMarkData::info");
		}
		struct Compiled
		{
			uint reset_only; // uint
			uint probe_residency; // RWStructuredBuffer<uint>
			uint compacted_list; // RWStructuredBuffer<uint>
			uint compacted_count; // RWStructuredBuffer<uint>
			uint pending; // RWStructuredBuffer<uint>
			uint miss_streak; // RWStructuredBuffer<uint>
			DDGIInfo::Compiled info; // DDGIInfo

			
			private:
			SERIALIZE()
			{
				ar& NVP(info);
				ar& NVP(reset_only);
			}


		};

		static std::string get_typename()
		{
			return "Tables::DDGIProbeResidencyMarkData";
		}
		private:
		SERIALIZE()
		{
			ar& NVP(info);
			ar& NVP(reset_only);
		}

	};
	#pragma pack(pop)
}

