// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.DDGISelectors;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)
	struct DDGISelectors
	{
		static constexpr SlotID ID = SlotID::DDGISelectors;
		bool enabled = true;
		bool& GetEnabled() { return enabled; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(enabled, "DDGISelectors::enabled");
		}
		using Compiled = DDGISelectors;

		static std::string get_typename()
		{
			return "Tables::DDGISelectors";
		}
		private:
		SERIALIZE()
		{
			ar& NVP(enabled);
		}

	};
	#pragma pack(pop)
}

