// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.DebugStruct;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)
	struct DebugStruct
	{
		static constexpr SlotID ID = SlotID::DebugStruct;
		uint format_id;
		uint4 args;
		uint& GetFormat_id() { return format_id; }
		uint4& GetArgs() { return args; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(format_id, "DebugStruct::format_id");
			compiler.compile(args, "DebugStruct::args");
		}
		using Compiled = DebugStruct;

		static std::string get_typename()
		{
			return "Tables::DebugStruct";
		}
		private:
		SERIALIZE()
		{
			ar& NVP(format_id);
			ar& NVP(args);
		}

	};
	#pragma pack(pop)
}

