// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.DenoiserHistoryFix;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)
	struct DenoiserHistoryFix
	{
		static constexpr SlotID ID = SlotID::DenoiserHistoryFix;
		HLSL::Texture2D<float4> color;
		HLSL::Texture2D<float> frames;
		HLSL::RWTexture2D<float4> target;
		HLSL::Texture2D<float4>& GetColor() { return color; }
		HLSL::Texture2D<float>& GetFrames() { return frames; }
		HLSL::RWTexture2D<float4>& GetTarget() { return target; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(color);
			compiler.compile(frames);
			compiler.compile(target);
		}
		struct Compiled
		{
			uint color; // Texture2D<float4>
			uint frames; // Texture2D<float>
			uint target; // RWTexture2D<float4>

			
			private:
			SERIALIZE()
			{
			}


		};

		static std::string get_typename()
		{
			return "Tables::DenoiserHistoryFix";
		}
		private:
		SERIALIZE()
		{
		}

	};
	#pragma pack(pop)
}

