// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.DenoiserDownsample;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)
	struct DenoiserDownsample
	{
		static constexpr SlotID ID = SlotID::DenoiserDownsample;
		HLSL::Texture2D<float4> color;
		HLSL::Texture2D<float> depth;
		HLSL::Texture2D<float4>& GetColor() { return color; }
		HLSL::Texture2D<float>& GetDepth() { return depth; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(color, "DenoiserDownsample::color");
			compiler.compile(depth, "DenoiserDownsample::depth");
		}
		struct Compiled
		{
			uint color; // Texture2D<float4>
			uint depth; // Texture2D<float>

			
			private:
			SERIALIZE()
			{
			}


		};

		static std::string get_typename()
		{
			return "Tables::DenoiserDownsample";
		}
		private:
		SERIALIZE()
		{
		}

	};
	#pragma pack(pop)
}

