// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.DispatchParameters;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)

	struct DispatchParameters
	{
		static constexpr SlotID ID = SlotID::DispatchParameters;
		float SurfaceThickness = 0.005;
		float BilinearThreshold = 0.02;
		float ShadowContrast = 4;
		uint IgnoreEdgePixels = false;
		uint UsePrecisionOffset = false;
		uint BilinearSamplingOffsetMode = false;
		uint DebugOutputEdgeMask = false;
		uint DebugOutputThreadIndex = false;
		uint DebugOutputWaveIndex = false;
		float2 DepthBounds = float2(0,1);
		uint UseEarlyOut = false;
		float4 LightCoordinate;
		int2 WaveOffset;
		float FarDepthValue;
		float NearDepthValue;
		float2 InvDepthTextureSize;
		HLSL::Texture2D<float> DepthTexture;
		HLSL::RWTexture2D<float4> OutputTexture;
		float& GetSurfaceThickness() { return SurfaceThickness; }
		float& GetBilinearThreshold() { return BilinearThreshold; }
		float& GetShadowContrast() { return ShadowContrast; }
		uint& GetIgnoreEdgePixels() { return IgnoreEdgePixels; }
		uint& GetUsePrecisionOffset() { return UsePrecisionOffset; }
		uint& GetBilinearSamplingOffsetMode() { return BilinearSamplingOffsetMode; }
		uint& GetDebugOutputEdgeMask() { return DebugOutputEdgeMask; }
		uint& GetDebugOutputThreadIndex() { return DebugOutputThreadIndex; }
		uint& GetDebugOutputWaveIndex() { return DebugOutputWaveIndex; }
		float2& GetDepthBounds() { return DepthBounds; }
		uint& GetUseEarlyOut() { return UseEarlyOut; }
		float4& GetLightCoordinate() { return LightCoordinate; }
		int2& GetWaveOffset() { return WaveOffset; }
		float& GetFarDepthValue() { return FarDepthValue; }
		float& GetNearDepthValue() { return NearDepthValue; }
		float2& GetInvDepthTextureSize() { return InvDepthTextureSize; }
		HLSL::Texture2D<float>& GetDepthTexture() { return DepthTexture; }
		HLSL::RWTexture2D<float4>& GetOutputTexture() { return OutputTexture; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(SurfaceThickness);
			compiler.compile(BilinearThreshold);
			compiler.compile(ShadowContrast);
			compiler.compile(IgnoreEdgePixels);
			compiler.compile(UsePrecisionOffset);
			compiler.compile(BilinearSamplingOffsetMode);
			compiler.compile(DebugOutputEdgeMask);
			compiler.compile(DebugOutputThreadIndex);
			compiler.compile(DebugOutputWaveIndex);
			compiler.compile(DepthBounds);
			compiler.compile(UseEarlyOut);
			compiler.compile(LightCoordinate);
			compiler.compile(WaveOffset);
			compiler.compile(FarDepthValue);
			compiler.compile(NearDepthValue);
			compiler.compile(InvDepthTextureSize);
			compiler.compile(DepthTexture);
			compiler.compile(OutputTexture);
		}
		struct Compiled
		{
			float SurfaceThickness; // float
			float BilinearThreshold; // float
			float ShadowContrast; // float
			uint IgnoreEdgePixels; // uint
			uint UsePrecisionOffset; // uint
			uint BilinearSamplingOffsetMode; // uint
			uint DebugOutputEdgeMask; // uint
			uint DebugOutputThreadIndex; // uint
			uint DebugOutputWaveIndex; // uint
			float2 DepthBounds; // float2
			uint UseEarlyOut; // uint
			float4 LightCoordinate; // float4
			int2 WaveOffset; // int2
			float FarDepthValue; // float
			float NearDepthValue; // float
			float2 InvDepthTextureSize; // float2
			uint DepthTexture; // Texture2D<float>
			uint OutputTexture; // RWTexture2D<float4>

			
			private:
			SERIALIZE()
			{
				ar& NVP(SurfaceThickness);
				ar& NVP(BilinearThreshold);
				ar& NVP(ShadowContrast);
				ar& NVP(IgnoreEdgePixels);
				ar& NVP(UsePrecisionOffset);
				ar& NVP(BilinearSamplingOffsetMode);
				ar& NVP(DebugOutputEdgeMask);
				ar& NVP(DebugOutputThreadIndex);
				ar& NVP(DebugOutputWaveIndex);
				ar& NVP(DepthBounds);
				ar& NVP(UseEarlyOut);
				ar& NVP(LightCoordinate);
				ar& NVP(WaveOffset);
				ar& NVP(FarDepthValue);
				ar& NVP(NearDepthValue);
				ar& NVP(InvDepthTextureSize);
			}


		};

		static std::string get_typename()
		{
			return "Tables::DispatchParameters";
		}
		private:
		SERIALIZE()
		{
			ar& NVP(SurfaceThickness);
			ar& NVP(BilinearThreshold);
			ar& NVP(ShadowContrast);
			ar& NVP(IgnoreEdgePixels);
			ar& NVP(UsePrecisionOffset);
			ar& NVP(BilinearSamplingOffsetMode);
			ar& NVP(DebugOutputEdgeMask);
			ar& NVP(DebugOutputThreadIndex);
			ar& NVP(DebugOutputWaveIndex);
			ar& NVP(DepthBounds);
			ar& NVP(UseEarlyOut);
			ar& NVP(LightCoordinate);
			ar& NVP(WaveOffset);
			ar& NVP(FarDepthValue);
			ar& NVP(NearDepthValue);
			ar& NVP(InvDepthTextureSize);
		}

	};
	#pragma pack(pop)
}

