// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.FontRendering;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)

	struct FontRendering
	{
		static constexpr SlotID ID = SlotID::FontRendering;
		HLSL::Texture2D<float> tex0;
		HLSL::StructuredBuffer<float4> positions;
		HLSL::Texture2D<float>& GetTex0() { return tex0; }
		HLSL::StructuredBuffer<float4>& GetPositions() { return positions; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(tex0);
			compiler.compile(positions);
		}
		struct Compiled
		{
			uint tex0; // Texture2D<float>
			uint positions; // StructuredBuffer<float4>

			
			private:
			SERIALIZE()
			{
			}


		};

		static std::string get_typename()
		{
			return "Tables::FontRendering";
		}
		private:
		SERIALIZE()
		{
		}

	};
	#pragma pack(pop)
}

