// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.NRD_GBufferPackParams;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
import :Autogen.Tables.GBuffer;
export namespace Table
{
	#pragma pack(push, 1)
	struct NRD_GBufferPackParams
	{
		static constexpr SlotID ID = SlotID::NRD_GBufferPackParams;
		HLSL::RWTexture2D<float> NRD_ViewZ;
		HLSL::RWTexture2D<float4> NRD_NormalRoughness;
		HLSL::RWTexture2D<float4> NRD_Mv;
		GBuffer gbuffer;
		HLSL::RWTexture2D<float>& GetNRD_ViewZ() { return NRD_ViewZ; }
		HLSL::RWTexture2D<float4>& GetNRD_NormalRoughness() { return NRD_NormalRoughness; }
		HLSL::RWTexture2D<float4>& GetNRD_Mv() { return NRD_Mv; }
		GBuffer& GetGbuffer() { return gbuffer; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(NRD_ViewZ, "NRD_GBufferPackParams::NRD_ViewZ");
			compiler.compile(NRD_NormalRoughness, "NRD_GBufferPackParams::NRD_NormalRoughness");
			compiler.compile(NRD_Mv, "NRD_GBufferPackParams::NRD_Mv");
			compiler.compile(gbuffer, "NRD_GBufferPackParams::gbuffer");
		}
		struct Compiled
		{
			uint NRD_ViewZ; // RWTexture2D<float>
			uint NRD_NormalRoughness; // RWTexture2D<float4>
			uint NRD_Mv; // RWTexture2D<float4>
			GBuffer::Compiled gbuffer; // GBuffer

			
			private:
			SERIALIZE()
			{
				ar& NVP(gbuffer);
			}


		};

		static std::string get_typename()
		{
			return "Tables::NRD_GBufferPackParams";
		}
		private:
		SERIALIZE()
		{
			ar& NVP(gbuffer);
		}

	};
	#pragma pack(pop)
}

