// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.PSSMDataGlobal;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
import :Autogen.Tables.Camera;
export namespace Table
{
	#pragma pack(push, 1)

	struct PSSMDataGlobal
	{
		static constexpr SlotID ID = SlotID::PSSMDataGlobal;
		HLSL::Texture2D<float> light_buffer;
		HLSL::StructuredBuffer<Camera> light_camera;
		HLSL::Texture2D<float>& GetLight_buffer() { return light_buffer; }
		HLSL::StructuredBuffer<Camera>& GetLight_camera() { return light_camera; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(light_buffer);
			compiler.compile(light_camera);
		}
		struct Compiled
		{
			uint light_buffer; // Texture2D<float>
			uint light_camera; // StructuredBuffer<Camera>

			
			private:
			SERIALIZE()
			{
			}


		};

		static std::string get_typename()
		{
			return "Tables::PSSMDataGlobal";
		}
		private:
		SERIALIZE()
		{
		}

	};
	#pragma pack(pop)
}

