// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Tables.SIGMASharedConstants;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)
	struct SIGMASharedConstants
	{
		static constexpr SlotID ID = SlotID::SIGMASharedConstants;
		float4x4 gWorldToView;
		float4x4 gViewToClip;
		float4x4 gWorldToClipPrev;
		float4x4 gWorldToViewPrev;
		float4 gRotator;
		float4 gRotatorPost;
		float4 gViewVectorWorld;
		float4 gLightDirectionView;
		float4 gFrustum;
		float4 gFrustumPrev;
		float4 gCameraDelta;
		float4 gMvScale;
		float2 gResourceSizeInv;
		float2 gResourceSizeInvPrev;
		float2 gRectSize;
		float2 gRectSizeInv;
		float2 gRectSizePrev;
		float2 gResolutionScale;
		float2 gRectOffset;
		uint2 gPrintfAt;
		uint2 gRectOrigin;
		int2 gRectSizeMinusOne;
		int2 gTilesSizeMinusOne;
		float gOrthoMode;
		float gUnproject;
		float gDenoisingRange;
		float gPlaneDistSensitivity;
		float gStabilizationStrength;
		float gDebug;
		float gSplitScreen;
		float gViewZScale;
		float gMinRectDimMulUnproject;
		uint gFrameIndex;
		uint gIsRectChanged;
		float4x4& GetGWorldToView() { return gWorldToView; }
		float4x4& GetGViewToClip() { return gViewToClip; }
		float4x4& GetGWorldToClipPrev() { return gWorldToClipPrev; }
		float4x4& GetGWorldToViewPrev() { return gWorldToViewPrev; }
		float4& GetGRotator() { return gRotator; }
		float4& GetGRotatorPost() { return gRotatorPost; }
		float4& GetGViewVectorWorld() { return gViewVectorWorld; }
		float4& GetGLightDirectionView() { return gLightDirectionView; }
		float4& GetGFrustum() { return gFrustum; }
		float4& GetGFrustumPrev() { return gFrustumPrev; }
		float4& GetGCameraDelta() { return gCameraDelta; }
		float4& GetGMvScale() { return gMvScale; }
		float2& GetGResourceSizeInv() { return gResourceSizeInv; }
		float2& GetGResourceSizeInvPrev() { return gResourceSizeInvPrev; }
		float2& GetGRectSize() { return gRectSize; }
		float2& GetGRectSizeInv() { return gRectSizeInv; }
		float2& GetGRectSizePrev() { return gRectSizePrev; }
		float2& GetGResolutionScale() { return gResolutionScale; }
		float2& GetGRectOffset() { return gRectOffset; }
		uint2& GetGPrintfAt() { return gPrintfAt; }
		uint2& GetGRectOrigin() { return gRectOrigin; }
		int2& GetGRectSizeMinusOne() { return gRectSizeMinusOne; }
		int2& GetGTilesSizeMinusOne() { return gTilesSizeMinusOne; }
		float& GetGOrthoMode() { return gOrthoMode; }
		float& GetGUnproject() { return gUnproject; }
		float& GetGDenoisingRange() { return gDenoisingRange; }
		float& GetGPlaneDistSensitivity() { return gPlaneDistSensitivity; }
		float& GetGStabilizationStrength() { return gStabilizationStrength; }
		float& GetGDebug() { return gDebug; }
		float& GetGSplitScreen() { return gSplitScreen; }
		float& GetGViewZScale() { return gViewZScale; }
		float& GetGMinRectDimMulUnproject() { return gMinRectDimMulUnproject; }
		uint& GetGFrameIndex() { return gFrameIndex; }
		uint& GetGIsRectChanged() { return gIsRectChanged; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(gWorldToView, "SIGMASharedConstants::gWorldToView");
			compiler.compile(gViewToClip, "SIGMASharedConstants::gViewToClip");
			compiler.compile(gWorldToClipPrev, "SIGMASharedConstants::gWorldToClipPrev");
			compiler.compile(gWorldToViewPrev, "SIGMASharedConstants::gWorldToViewPrev");
			compiler.compile(gRotator, "SIGMASharedConstants::gRotator");
			compiler.compile(gRotatorPost, "SIGMASharedConstants::gRotatorPost");
			compiler.compile(gViewVectorWorld, "SIGMASharedConstants::gViewVectorWorld");
			compiler.compile(gLightDirectionView, "SIGMASharedConstants::gLightDirectionView");
			compiler.compile(gFrustum, "SIGMASharedConstants::gFrustum");
			compiler.compile(gFrustumPrev, "SIGMASharedConstants::gFrustumPrev");
			compiler.compile(gCameraDelta, "SIGMASharedConstants::gCameraDelta");
			compiler.compile(gMvScale, "SIGMASharedConstants::gMvScale");
			compiler.compile(gResourceSizeInv, "SIGMASharedConstants::gResourceSizeInv");
			compiler.compile(gResourceSizeInvPrev, "SIGMASharedConstants::gResourceSizeInvPrev");
			compiler.compile(gRectSize, "SIGMASharedConstants::gRectSize");
			compiler.compile(gRectSizeInv, "SIGMASharedConstants::gRectSizeInv");
			compiler.compile(gRectSizePrev, "SIGMASharedConstants::gRectSizePrev");
			compiler.compile(gResolutionScale, "SIGMASharedConstants::gResolutionScale");
			compiler.compile(gRectOffset, "SIGMASharedConstants::gRectOffset");
			compiler.compile(gPrintfAt, "SIGMASharedConstants::gPrintfAt");
			compiler.compile(gRectOrigin, "SIGMASharedConstants::gRectOrigin");
			compiler.compile(gRectSizeMinusOne, "SIGMASharedConstants::gRectSizeMinusOne");
			compiler.compile(gTilesSizeMinusOne, "SIGMASharedConstants::gTilesSizeMinusOne");
			compiler.compile(gOrthoMode, "SIGMASharedConstants::gOrthoMode");
			compiler.compile(gUnproject, "SIGMASharedConstants::gUnproject");
			compiler.compile(gDenoisingRange, "SIGMASharedConstants::gDenoisingRange");
			compiler.compile(gPlaneDistSensitivity, "SIGMASharedConstants::gPlaneDistSensitivity");
			compiler.compile(gStabilizationStrength, "SIGMASharedConstants::gStabilizationStrength");
			compiler.compile(gDebug, "SIGMASharedConstants::gDebug");
			compiler.compile(gSplitScreen, "SIGMASharedConstants::gSplitScreen");
			compiler.compile(gViewZScale, "SIGMASharedConstants::gViewZScale");
			compiler.compile(gMinRectDimMulUnproject, "SIGMASharedConstants::gMinRectDimMulUnproject");
			compiler.compile(gFrameIndex, "SIGMASharedConstants::gFrameIndex");
			compiler.compile(gIsRectChanged, "SIGMASharedConstants::gIsRectChanged");
		}
		using Compiled = SIGMASharedConstants;

		static std::string get_typename()
		{
			return "Tables::SIGMASharedConstants";
		}
		private:
		SERIALIZE()
		{
			ar& NVP(gWorldToView);
			ar& NVP(gViewToClip);
			ar& NVP(gWorldToClipPrev);
			ar& NVP(gWorldToViewPrev);
			ar& NVP(gRotator);
			ar& NVP(gRotatorPost);
			ar& NVP(gViewVectorWorld);
			ar& NVP(gLightDirectionView);
			ar& NVP(gFrustum);
			ar& NVP(gFrustumPrev);
			ar& NVP(gCameraDelta);
			ar& NVP(gMvScale);
			ar& NVP(gResourceSizeInv);
			ar& NVP(gResourceSizeInvPrev);
			ar& NVP(gRectSize);
			ar& NVP(gRectSizeInv);
			ar& NVP(gRectSizePrev);
			ar& NVP(gResolutionScale);
			ar& NVP(gRectOffset);
			ar& NVP(gPrintfAt);
			ar& NVP(gRectOrigin);
			ar& NVP(gRectSizeMinusOne);
			ar& NVP(gTilesSizeMinusOne);
			ar& NVP(gOrthoMode);
			ar& NVP(gUnproject);
			ar& NVP(gDenoisingRange);
			ar& NVP(gPlaneDistSensitivity);
			ar& NVP(gStabilizationStrength);
			ar& NVP(gDebug);
			ar& NVP(gSplitScreen);
			ar& NVP(gViewZScale);
			ar& NVP(gMinRectDimMulUnproject);
			ar& NVP(gFrameIndex);
			ar& NVP(gIsRectChanged);
		}

	};
	#pragma pack(pop)
}

