// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Tables.SkyFace;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)
	namespace Environment
	{
		struct SkyFace
		{
			static constexpr SlotID ID = SlotID::SkyFace;
			HLSL::RWTexture2DArray<float4> faces;
			HLSL::RWTexture2DArray<float4>& GetFaces() { return faces; }
			static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
			template<class Compiler>
			void compile(Compiler& compiler) const
			{
				compiler.compile(faces, "SkyFace::faces");
			}
			struct Compiled
			{
				uint faces; // RWTexture2DArray<float4>

			
				private:
				SERIALIZE()
				{
				}


			};

			static std::string get_typename()
			{
				return "Tables::SkyFace";
			}
			private:
			SERIALIZE()
			{
			}

		};
	}
	#pragma pack(pop)
}

