// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.StatGraph;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)
	struct StatGraph
	{
		static constexpr SlotID ID = SlotID::StatGraph;
		uint Count;
		uint Width;
		uint Height;
		float Vmin;
		float Vmax;
		float4 LineColor;
		float4 FillTop;
		float4 FillBot;
		float4 BgTop;
		float4 BgBot;
		HLSL::StructuredBuffer<float> Samples;
		HLSL::RWTexture2D<float4> Output;
		uint& GetCount() { return Count; }
		uint& GetWidth() { return Width; }
		uint& GetHeight() { return Height; }
		float& GetVmin() { return Vmin; }
		float& GetVmax() { return Vmax; }
		float4& GetLineColor() { return LineColor; }
		float4& GetFillTop() { return FillTop; }
		float4& GetFillBot() { return FillBot; }
		float4& GetBgTop() { return BgTop; }
		float4& GetBgBot() { return BgBot; }
		HLSL::StructuredBuffer<float>& GetSamples() { return Samples; }
		HLSL::RWTexture2D<float4>& GetOutput() { return Output; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(Count);
			compiler.compile(Width);
			compiler.compile(Height);
			compiler.compile(Vmin);
			compiler.compile(Vmax);
			compiler.compile(LineColor);
			compiler.compile(FillTop);
			compiler.compile(FillBot);
			compiler.compile(BgTop);
			compiler.compile(BgBot);
			compiler.compile(Samples);
			compiler.compile(Output);
		}
		struct Compiled
		{
			uint Count; // uint
			uint Width; // uint
			uint Height; // uint
			float Vmin; // float
			float Vmax; // float
			float4 LineColor; // float4
			float4 FillTop; // float4
			float4 FillBot; // float4
			float4 BgTop; // float4
			float4 BgBot; // float4
			uint Samples; // StructuredBuffer<float>
			uint Output; // RWTexture2D<float4>

			
			private:
			SERIALIZE()
			{
				ar& NVP(Count);
				ar& NVP(Width);
				ar& NVP(Height);
				ar& NVP(Vmin);
				ar& NVP(Vmax);
				ar& NVP(LineColor);
				ar& NVP(FillTop);
				ar& NVP(FillBot);
				ar& NVP(BgTop);
				ar& NVP(BgBot);
			}


		};

		static std::string get_typename()
		{
			return "Tables::StatGraph";
		}
		private:
		SERIALIZE()
		{
			ar& NVP(Count);
			ar& NVP(Width);
			ar& NVP(Height);
			ar& NVP(Vmin);
			ar& NVP(Vmax);
			ar& NVP(LineColor);
			ar& NVP(FillTop);
			ar& NVP(FillBot);
			ar& NVP(BgTop);
			ar& NVP(BgBot);
		}

	};
	#pragma pack(pop)
}

