// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Tables.Test;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
import :Autogen.Tables.MeshInstanceInfo;
export namespace Table
{
	#pragma pack(push, 1)
	namespace Dev
	{
		struct Test
		{
			static constexpr SlotID ID = SlotID::Test;
			float data[16];
			::Dev::TestEnumMode mode = ::Dev::TestEnumMode::None;
			std::vector<HLSL::StructuredBuffer<Table::Meshes::MeshInstanceInfo>> instances;
			std::vector<HLSL::Texture2D<float4>> tex;
			float* GetData() { return data; }
			::Dev::TestEnumMode& GetMode() { return mode; }
			std::vector<HLSL::StructuredBuffer<Table::Meshes::MeshInstanceInfo>>& GetInstances() { return instances; }
			std::vector<HLSL::Texture2D<float4>>& GetTex() { return tex; }
			static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
			template<class Compiler>
			void compile(Compiler& compiler) const
			{
				compiler.compile(data, "Test::data");
				compiler.compile(mode, "Test::mode");
				compiler.compile(instances, "Test::instances");
				compiler.compile(tex, "Test::tex");
			}
			struct Compiled
			{
				float data[16]; // float
				::Dev::TestEnumMode mode; // TestEnumMode
				uint instances; // StructuredBuffer<MeshInstanceInfo>
				uint tex; // Texture2D<float4>

			
				private:
				SERIALIZE()
				{
					ar& NVP(data);
					ar& NVP(mode);
				}


			};

			static std::string get_typename()
			{
				return "Tables::Test";
			}
			private:
			SERIALIZE()
			{
				ar& NVP(data);
				ar& NVP(mode);
			}

		};
	}
	#pragma pack(pop)
}

