// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.vertex_input;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)
	struct vertex_input
	{
		static constexpr SlotID ID = SlotID::vertex_input;
		float2 pos;
		float2 tc;
		float4 mulColor;
		float4 addColor;
		float gammaEncode;
		float2& GetPos() { return pos; }
		float2& GetTc() { return tc; }
		float4& GetMulColor() { return mulColor; }
		float4& GetAddColor() { return addColor; }
		float& GetGammaEncode() { return gammaEncode; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(pos);
			compiler.compile(tc);
			compiler.compile(mulColor);
			compiler.compile(addColor);
			compiler.compile(gammaEncode);
		}
		using Compiled = vertex_input;

		static std::string get_typename()
		{
			return "Tables::vertex_input";
		}
		private:
		SERIALIZE()
		{
			ar& NVP(pos);
			ar& NVP(tc);
			ar& NVP(mulColor);
			ar& NVP(addColor);
			ar& NVP(gammaEncode);
		}

	};
	#pragma pack(pop)
}

