// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.VSMBlockerClassifyInitDispatch;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)
	struct VSMBlockerClassifyInitDispatch
	{
		static constexpr SlotID ID = SlotID::VSMBlockerClassifyInitDispatch;
		HLSL::StructuredBuffer<uint> lit_counter;
		HLSL::StructuredBuffer<uint> dark_counter;
		HLSL::StructuredBuffer<uint> search_counter;
		HLSL::RWStructuredBuffer<DispatchArguments> lit_dispatch_data;
		HLSL::RWStructuredBuffer<DispatchArguments> dark_dispatch_data;
		HLSL::RWStructuredBuffer<DispatchArguments> search_dispatch_data;
		HLSL::StructuredBuffer<uint>& GetLit_counter() { return lit_counter; }
		HLSL::StructuredBuffer<uint>& GetDark_counter() { return dark_counter; }
		HLSL::StructuredBuffer<uint>& GetSearch_counter() { return search_counter; }
		HLSL::RWStructuredBuffer<DispatchArguments>& GetLit_dispatch_data() { return lit_dispatch_data; }
		HLSL::RWStructuredBuffer<DispatchArguments>& GetDark_dispatch_data() { return dark_dispatch_data; }
		HLSL::RWStructuredBuffer<DispatchArguments>& GetSearch_dispatch_data() { return search_dispatch_data; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(lit_counter);
			compiler.compile(dark_counter);
			compiler.compile(search_counter);
			compiler.compile(lit_dispatch_data);
			compiler.compile(dark_dispatch_data);
			compiler.compile(search_dispatch_data);
		}
		struct Compiled
		{
			uint lit_counter; // StructuredBuffer<uint>
			uint dark_counter; // StructuredBuffer<uint>
			uint search_counter; // StructuredBuffer<uint>
			uint lit_dispatch_data; // RWStructuredBuffer<DispatchArguments>
			uint dark_dispatch_data; // RWStructuredBuffer<DispatchArguments>
			uint search_dispatch_data; // RWStructuredBuffer<DispatchArguments>

			
			private:
			SERIALIZE()
			{
			}


		};

		static std::string get_typename()
		{
			return "Tables::VSMBlockerClassifyInitDispatch";
		}
		private:
		SERIALIZE()
		{
		}

	};
	#pragma pack(pop)
}

