// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.VSMCopyLevelHiZBatch;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
import :Autogen.Tables.VSMDirtyPageInfo;
export namespace Table
{
	#pragma pack(push, 1)
	struct VSMCopyLevelHiZBatch
	{
		static constexpr SlotID ID = SlotID::VSMCopyLevelHiZBatch;
		HLSL::Texture2DArray<float2> page_hiz_coarsest;
		HLSL::StructuredBuffer<VSMDirtyPageInfo> dirty_pages;
		HLSL::RWTexture2DArray<float2> level_hiz_mip0;
		HLSL::Texture2DArray<float2>& GetPage_hiz_coarsest() { return page_hiz_coarsest; }
		HLSL::RWTexture2DArray<float2>& GetLevel_hiz_mip0() { return level_hiz_mip0; }
		HLSL::StructuredBuffer<VSMDirtyPageInfo>& GetDirty_pages() { return dirty_pages; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile_whole(page_hiz_coarsest);
			compiler.compile(dirty_pages);
			compiler.compile_whole(level_hiz_mip0);
		}
		struct Compiled
		{
			uint page_hiz_coarsest; // Texture2DArray<float2>
			uint dirty_pages; // StructuredBuffer<VSMDirtyPageInfo>
			uint level_hiz_mip0; // RWTexture2DArray<float2>

			
			private:
			SERIALIZE()
			{
			}


		};

		static std::string get_typename()
		{
			return "Tables::VSMCopyLevelHiZBatch";
		}
		private:
		SERIALIZE()
		{
		}

	};
	#pragma pack(pop)
}

