// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.VSMDirtyPageInfo;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)
	struct VSMDirtyPageInfo
	{
		static constexpr SlotID ID = SlotID::VSMDirtyPageInfo;
		uint physical_slot;
		uint level;
		uint page_x;
		uint page_y;
		uint& GetPhysical_slot() { return physical_slot; }
		uint& GetLevel() { return level; }
		uint& GetPage_x() { return page_x; }
		uint& GetPage_y() { return page_y; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(physical_slot);
			compiler.compile(level);
			compiler.compile(page_x);
			compiler.compile(page_y);
		}
		using Compiled = VSMDirtyPageInfo;

		static std::string get_typename()
		{
			return "Tables::VSMDirtyPageInfo";
		}
		private:
		SERIALIZE()
		{
			ar& NVP(physical_slot);
			ar& NVP(level);
			ar& NVP(page_x);
			ar& NVP(page_y);
		}

	};
	#pragma pack(pop)
}

