// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Tables.VSMLevelDispatchInfo;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
import :Autogen.Tables.VSMPageBatch;
export namespace Table
{
	#pragma pack(push, 1)
	struct VSMLevelDispatchInfo
	{
		static constexpr SlotID ID = SlotID::VSMLevelDispatchInfo;
		Pointer<VSMPageBatch> page_batch_cb;
		float2 bounds_min;
		float2 bounds_max;
		Pointer<VSMPageBatch>& GetPage_batch_cb() { return page_batch_cb; }
		float2& GetBounds_min() { return bounds_min; }
		float2& GetBounds_max() { return bounds_max; }
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
		template<class Compiler>
		void compile(Compiler& compiler) const
		{
			compiler.compile(page_batch_cb, "VSMLevelDispatchInfo::page_batch_cb");
			compiler.compile(bounds_min, "VSMLevelDispatchInfo::bounds_min");
			compiler.compile(bounds_max, "VSMLevelDispatchInfo::bounds_max");
		}
		using Compiled = VSMLevelDispatchInfo;

		static std::string get_typename()
		{
			return "Tables::VSMLevelDispatchInfo";
		}
		private:
		SERIALIZE()
		{
			ar& NVP(page_batch_cb);
			ar& NVP(bounds_min);
			ar& NVP(bounds_max);
		}

	};
	#pragma pack(pop)
}

