// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Tables.VSMShadowLookupData;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
import :Autogen.Tables.VSMShadowLookup;
export namespace Table
{
	#pragma pack(push, 1)
	namespace Shadows
	{
		namespace VSM
		{
			struct VSMShadowLookupData
			{
				static constexpr SlotID ID = SlotID::VSMShadowLookupData;
				Table::Shadows::VSM::VSMShadowLookup lookup;
				Table::Shadows::VSM::VSMShadowLookup& GetLookup() { return lookup; }
				static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
				template<class Compiler>
				void compile(Compiler& compiler) const
				{
					compiler.compile(lookup, "VSMShadowLookupData::lookup");
				}
				using Compiled = VSMShadowLookupData;

				static std::string get_typename()
				{
					return "Tables::VSMShadowLookupData";
				}
				private:
				SERIALIZE()
				{
					ar& NVP(lookup);
				}

			};
		}
	}
	#pragma pack(pop)
}

