// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module FrameGraph:Passes;

import :Base;
import :ViewportContext;
import Core;
import HAL;

export import "../defines.h";


#include "pass/Editor/AssetGBuffer.h"
#include "pass/Editor/AssetMip.h"
#include "pass/Post/BloomBuild.h"
#include "pass/Post/BloomProcess.h"
#include "pass/Post/BloomBuildPost.h"
#include "pass/Post/BloomComposite.h"
#include "pass/Utility/BlueNoise.h"
#include "pass/GI/DDGI/DDGIProbeSelect.h"
#include "pass/GI/DDGI/DDGIProbeResidencyMark.h"
#include "pass/GI/DDGI/DDGIProbeDispatchArgsBuild.h"
#include "pass/GI/DDGI/DDGIProbeTrace.h"
#include "pass/GI/DDGI/DDGIProbeConvolve.h"
#include "pass/GI/DDGI/Dev/DDGIDebug.h"
#include "pass/GI/DDGI/Dev/DDGIIndirectDebug.h"
#include "pass/Dev/DebugView.h"
#include "pass/Post/Upscale/FSR.h"
#include "pass/Frame/ResultCreation.h"
#include "pass/Denoise/NRD/NRD_GBufferPack.h"
#include "pass/Denoise/NRD/NRD_REBLUR_Execute.h"
#include "pass/Denoise/NRD/NRD_SIGMA_Execute.h"
#include "pass/Denoise/NRD/NRD_IndirectCombine.h"
#include "pass/Denoise/NRD/NRD_ShadowCombine.h"
#include "pass/Shadows/PSSM/PSSM_Cascade.h"
#include "pass/Shadows/PSSM/PSSM_GenerateMask.h"
#include "pass/Shadows/PSSM/PSSM_Combine.h"
#include "pass/Shadows/PSSM/PSSM_Global.h"
#include "pass/Shadows/RTXShadow.h"
#include "pass/Raytrace/Dev/RTXColorPass.h"
#include "pass/Raytrace/TranslucentRTX.h"
#include "pass/Frame/PreScene.h"
#include "pass/Dev/Profiler.h"
#include "pass/Meshes/Scene.h"
#include "pass/Environment/Sky.h"
#include "pass/Environment/CubeSky.h"
#include "pass/Environment/CubeMapDownsample.h"
#include "pass/Environment/CubeMapEnviromentProcessor.h"
#include "pass/Post/AA/SMAA.h"
#include "pass/Editor/stencil_renderer.h"
#include "pass/Post/Tonemap.h"
#include "pass/UI/UI_PreDraw.h"
#include "pass/UI/UI_Render.h"
#include "pass/Editor/AssetPreview.h"
#include "pass/Post/Upscale/UpscalingDLSS.h"
#include "pass/Post/Upscale/NormalRoughnessRepack.h"
#include "pass/Post/Upscale/UpscalingDLSSRR.h"
#include "pass/Meshes/GBufferDownsampler.h"
#include "pass/GI/Voxel/Dev/VoxelDebug.h"
#include "pass/Reflections/ReflectionRTXHalf.h"
#include "pass/Reflections/ReflectionRTX.h"
#include "pass/Shadows/ShadowRTX.h"
#include "pass/GI/IndirectRTXHalf.h"
#include "pass/GI/IndirectRTX.h"
#include "pass/Reflections/ReflCombine.h"
#include "pass/GI/RTXCombine.h"
#include "pass/GI/Voxel/Voxelize.h"
#include "pass/GI/Voxel/Lighting.h"
#include "pass/GI/Voxel/Mipmapping.h"
#include "pass/GI/Voxel/VoxelScreen.h"
#include "pass/Reflections/ScreenReflection.h"
#include "pass/Shadows/VSM/VSM_GatherDispatch.h"
#include "pass/Shadows/VSM/VSM_RenderPages.h"
#include "pass/Shadows/VSM/VSM_HiZRebuild.h"
#include "pass/Shadows/VSM/VSM_BlockerClassify.h"
#include "pass/Shadows/VSM/VSM_BlockerSearch.h"
#include "pass/Shadows/VSM/VSM_ScreenSpaceShadow.h"
#include "pass/Shadows/VSM/VSM_ShadowResolve.h"
#include "pass/Shadows/VSM/VSM_Combine.h"
#include "pass/Shadows/VSM/Dev/VSM_DebugClassifyOverlay.h"
#include "pass/Shadows/VSM/VSM_DepthAnalysis.h"
#include "pass/Editor/AssetPipeline.pipeline.h"
#include "pass/Frame/MainPipeline.pipeline.h"
#include "pass/UI/UIPipeline.pipeline.h"

export namespace Passes
{
	namespace Editor
	{
		using ::Passes::Editor::AssetGBuffer;
	}
	namespace Editor
	{
		using ::Passes::Editor::AssetMip;
	}
	namespace Post
	{
		using ::Passes::Post::BloomBuild;
	}
	namespace Post
	{
		using ::Passes::Post::BloomProcess;
	}
	namespace Post
	{
		using ::Passes::Post::BloomBuildPost;
	}
	namespace Post
	{
		using ::Passes::Post::BloomComposite;
	}
	namespace Utility
	{
		using ::Passes::Utility::BlueNoise;
	}
	namespace GI
	{
		namespace DDGI
		{
			using ::Passes::GI::DDGI::DDGIProbeSelect;
		}
	}
	namespace GI
	{
		namespace DDGI
		{
			using ::Passes::GI::DDGI::DDGIProbeResidencyMark;
		}
	}
	namespace GI
	{
		namespace DDGI
		{
			using ::Passes::GI::DDGI::DDGIProbeDispatchArgsBuild;
		}
	}
	namespace GI
	{
		namespace DDGI
		{
			using ::Passes::GI::DDGI::DDGIProbeTrace;
		}
	}
	namespace GI
	{
		namespace DDGI
		{
			using ::Passes::GI::DDGI::DDGIProbeConvolve;
		}
	}
	namespace GI
	{
		namespace DDGI
		{
			namespace Dev
			{
				using ::Passes::GI::DDGI::Dev::DDGIDebug;
			}
		}
	}
	namespace GI
	{
		namespace DDGI
		{
			namespace Dev
			{
				using ::Passes::GI::DDGI::Dev::DDGIIndirectDebug;
			}
		}
	}
	namespace Dev
	{
		using ::Passes::Dev::DebugView;
	}
	namespace Post
	{
		namespace Upscale
		{
			using ::Passes::Post::Upscale::FSR;
		}
	}
	namespace Frame
	{
		using ::Passes::Frame::ResultCreation;
	}
	namespace Denoise
	{
		namespace NRD
		{
			using ::Passes::Denoise::NRD::NRD_GBufferPack;
		}
	}
	namespace Denoise
	{
		namespace NRD
		{
			using ::Passes::Denoise::NRD::NRD_REBLUR_Execute;
		}
	}
	namespace Denoise
	{
		namespace NRD
		{
			using ::Passes::Denoise::NRD::NRD_SIGMA_Execute;
		}
	}
	namespace Denoise
	{
		namespace NRD
		{
			using ::Passes::Denoise::NRD::NRD_IndirectCombine;
		}
	}
	namespace Denoise
	{
		namespace NRD
		{
			using ::Passes::Denoise::NRD::NRD_ShadowCombine;
		}
	}
	namespace Shadows
	{
		namespace PSSM
		{
			using ::Passes::Shadows::PSSM::PSSM_Cascade;
		}
	}
	namespace Shadows
	{
		namespace PSSM
		{
			using ::Passes::Shadows::PSSM::PSSM_GenerateMask;
		}
	}
	namespace Shadows
	{
		namespace PSSM
		{
			using ::Passes::Shadows::PSSM::PSSM_Combine;
		}
	}
	namespace Shadows
	{
		namespace PSSM
		{
			using ::Passes::Shadows::PSSM::PSSM_Global;
		}
	}
	namespace Shadows
	{
		using ::Passes::Shadows::RTXShadow;
	}
	namespace Raytrace
	{
		namespace Dev
		{
			using ::Passes::Raytrace::Dev::RTXColorPass;
		}
	}
	namespace Raytrace
	{
		using ::Passes::Raytrace::TranslucentRTX;
	}
	namespace Frame
	{
		using ::Passes::Frame::PreScene;
	}
	namespace Dev
	{
		using ::Passes::Dev::Profiler;
	}
	namespace Meshes
	{
		using ::Passes::Meshes::Scene;
	}
	namespace Environment
	{
		using ::Passes::Environment::Sky;
	}
	namespace Environment
	{
		using ::Passes::Environment::CubeSky;
	}
	namespace Environment
	{
		using ::Passes::Environment::CubeMapDownsample;
	}
	namespace Environment
	{
		using ::Passes::Environment::CubeMapEnviromentProcessor;
	}
	namespace Post
	{
		namespace AA
		{
			using ::Passes::Post::AA::SMAA;
		}
	}
	namespace Editor
	{
		using ::Passes::Editor::stencil_renderer;
	}
	namespace Post
	{
		using ::Passes::Post::Tonemap;
	}
	namespace UI
	{
		using ::Passes::UI::UI_PreDraw;
	}
	namespace UI
	{
		using ::Passes::UI::UI_Render;
	}
	namespace Editor
	{
		using ::Passes::Editor::AssetPreview;
	}
	namespace Post
	{
		namespace Upscale
		{
			using ::Passes::Post::Upscale::UpscalingDLSS;
		}
	}
	namespace Post
	{
		namespace Upscale
		{
			using ::Passes::Post::Upscale::NormalRoughnessRepack;
		}
	}
	namespace Post
	{
		namespace Upscale
		{
			using ::Passes::Post::Upscale::UpscalingDLSSRR;
		}
	}
	namespace Meshes
	{
		using ::Passes::Meshes::GBufferDownsampler;
	}
	namespace GI
	{
		namespace Voxel
		{
			namespace Dev
			{
				using ::Passes::GI::Voxel::Dev::VoxelDebug;
			}
		}
	}
	namespace Reflections
	{
		using ::Passes::Reflections::ReflectionRTXHalf;
	}
	namespace Reflections
	{
		using ::Passes::Reflections::ReflectionRTX;
	}
	namespace Shadows
	{
		using ::Passes::Shadows::ShadowRTX;
	}
	namespace GI
	{
		using ::Passes::GI::IndirectRTXHalf;
	}
	namespace GI
	{
		using ::Passes::GI::IndirectRTX;
	}
	namespace Reflections
	{
		using ::Passes::Reflections::ReflCombine;
	}
	namespace GI
	{
		using ::Passes::GI::RTXCombine;
	}
	namespace GI
	{
		namespace Voxel
		{
			using ::Passes::GI::Voxel::Voxelize;
		}
	}
	namespace GI
	{
		namespace Voxel
		{
			using ::Passes::GI::Voxel::Lighting;
		}
	}
	namespace GI
	{
		namespace Voxel
		{
			using ::Passes::GI::Voxel::Mipmapping;
		}
	}
	namespace GI
	{
		namespace Voxel
		{
			using ::Passes::GI::Voxel::VoxelScreen;
		}
	}
	namespace Reflections
	{
		using ::Passes::Reflections::ScreenReflection;
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_GatherDispatch;
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_RenderPages;
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_HiZRebuild;
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_BlockerClassify;
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_BlockerSearch;
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_ScreenSpaceShadow;
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_ShadowResolve;
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_Combine;
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			namespace Dev
			{
				using ::Passes::Shadows::VSM::Dev::VSM_DebugClassifyOverlay;
			}
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_DepthAnalysis;
		}
	}
}

export namespace Pipelines
{
	namespace Editor
	{
		using ::Pipelines::Editor::AssetPipeline;
	}
	namespace Frame
	{
		using ::Pipelines::Frame::MainPipeline;
	}
	namespace UI
	{
		using ::Pipelines::UI::UIPipeline;
	}
}
