// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module FrameGraph:Passes;

import :Base;
import :ViewportContext;
import Core;
import HAL;

export import "../defines.h";


#include "pass/AssetGBuffer.h"
#include "pass/AssetMip.h"
#include "pass/BlueNoise.h"
#include "pass/DDGIProbeSelect.h"
#include "pass/DDGIProbeResidencyMark.h"
#include "pass/DDGIProbeDispatchArgsBuild.h"
#include "pass/DDGIProbeTrace.h"
#include "pass/DDGIProbeConvolve.h"
#include "pass/DDGIDebug.h"
#include "pass/DDGIIndirectDebug.h"
#include "pass/FSR.h"
#include "pass/ResultCreation.h"
#include "pass/NRD_GBufferPack.h"
#include "pass/NRD_REBLUR_Execute.h"
#include "pass/NRD_SIGMA_Execute.h"
#include "pass/NRD_IndirectCombine.h"
#include "pass/NRD_ShadowCombine.h"
#include "pass/PSSM_Cascade.h"
#include "pass/PSSM_GenerateMask.h"
#include "pass/PSSM_Combine.h"
#include "pass/PSSM_Global.h"
#include "pass/RTXShadow.h"
#include "pass/RTXColorPass.h"
#include "pass/TranslucentRTX.h"
#include "pass/PreScene.h"
#include "pass/Profiler.h"
#include "pass/Scene.h"
#include "pass/Sky.h"
#include "pass/CubeSky.h"
#include "pass/CubeMapDownsample.h"
#include "pass/CubeMapEnviromentProcessor.h"
#include "pass/SMAA.h"
#include "pass/stencil_renderer.h"
#include "pass/Tonemap.h"
#include "pass/UI_PreDraw.h"
#include "pass/UI_Render.h"
#include "pass/AssetPreview.h"
#include "pass/UpscalingDLSS.h"
#include "pass/NormalRoughnessRepack.h"
#include "pass/UpscalingDLSSRR.h"
#include "pass/GBufferDownsampler.h"
#include "pass/VoxelDebug.h"
#include "pass/ReflectionRTXHalf.h"
#include "pass/ReflectionRTX.h"
#include "pass/ShadowRTX.h"
#include "pass/IndirectRTXHalf.h"
#include "pass/IndirectRTX.h"
#include "pass/ReflCombine.h"
#include "pass/RTXCombine.h"
#include "pass/Voxelize.h"
#include "pass/Lighting.h"
#include "pass/Mipmapping.h"
#include "pass/VoxelScreen.h"
#include "pass/ScreenReflection.h"
#include "pass/VSM_GatherDispatch.h"
#include "pass/VSM_RenderPages.h"
#include "pass/VSM_HiZRebuild.h"
#include "pass/VSM_BlockerClassify.h"
#include "pass/VSM_BlockerSearch.h"
#include "pass/VSM_ScreenSpaceShadow.h"
#include "pass/VSM_ShadowResolve.h"
#include "pass/VSM_Combine.h"
#include "pass/VSM_DebugClassifyOverlay.h"
#include "pass/VSM_DepthAnalysis.h"
#include "pass/AssetPipeline.pipeline.h"
#include "pass/MainPipeline.pipeline.h"
#include "pass/UIPipeline.pipeline.h"

export namespace Passes
{
	namespace Editor
	{
		using ::Passes::Editor::AssetGBuffer;
	}
	namespace Editor
	{
		using ::Passes::Editor::AssetMip;
	}
	namespace Utility
	{
		using ::Passes::Utility::BlueNoise;
	}
	namespace GI
	{
		namespace DDGI
		{
			using ::Passes::GI::DDGI::DDGIProbeSelect;
		}
	}
	namespace GI
	{
		namespace DDGI
		{
			using ::Passes::GI::DDGI::DDGIProbeResidencyMark;
		}
	}
	namespace GI
	{
		namespace DDGI
		{
			using ::Passes::GI::DDGI::DDGIProbeDispatchArgsBuild;
		}
	}
	namespace GI
	{
		namespace DDGI
		{
			using ::Passes::GI::DDGI::DDGIProbeTrace;
		}
	}
	namespace GI
	{
		namespace DDGI
		{
			using ::Passes::GI::DDGI::DDGIProbeConvolve;
		}
	}
	namespace GI
	{
		namespace DDGI
		{
			namespace Dev
			{
				using ::Passes::GI::DDGI::Dev::DDGIDebug;
			}
		}
	}
	namespace GI
	{
		namespace DDGI
		{
			namespace Dev
			{
				using ::Passes::GI::DDGI::Dev::DDGIIndirectDebug;
			}
		}
	}
	namespace Post
	{
		namespace Upscale
		{
			using ::Passes::Post::Upscale::FSR;
		}
	}
	namespace Frame
	{
		using ::Passes::Frame::ResultCreation;
	}
	namespace Denoise
	{
		namespace NRD
		{
			using ::Passes::Denoise::NRD::NRD_GBufferPack;
		}
	}
	namespace Denoise
	{
		namespace NRD
		{
			using ::Passes::Denoise::NRD::NRD_REBLUR_Execute;
		}
	}
	namespace Denoise
	{
		namespace NRD
		{
			using ::Passes::Denoise::NRD::NRD_SIGMA_Execute;
		}
	}
	namespace Denoise
	{
		namespace NRD
		{
			using ::Passes::Denoise::NRD::NRD_IndirectCombine;
		}
	}
	namespace Denoise
	{
		namespace NRD
		{
			using ::Passes::Denoise::NRD::NRD_ShadowCombine;
		}
	}
	namespace Shadows
	{
		namespace PSSM
		{
			using ::Passes::Shadows::PSSM::PSSM_Cascade;
		}
	}
	namespace Shadows
	{
		namespace PSSM
		{
			using ::Passes::Shadows::PSSM::PSSM_GenerateMask;
		}
	}
	namespace Shadows
	{
		namespace PSSM
		{
			using ::Passes::Shadows::PSSM::PSSM_Combine;
		}
	}
	namespace Shadows
	{
		namespace PSSM
		{
			using ::Passes::Shadows::PSSM::PSSM_Global;
		}
	}
	namespace Shadows
	{
		using ::Passes::Shadows::RTXShadow;
	}
	namespace Raytrace
	{
		namespace Dev
		{
			using ::Passes::Raytrace::Dev::RTXColorPass;
		}
	}
	namespace Raytrace
	{
		using ::Passes::Raytrace::TranslucentRTX;
	}
	namespace Frame
	{
		using ::Passes::Frame::PreScene;
	}
	namespace Dev
	{
		using ::Passes::Dev::Profiler;
	}
	namespace Meshes
	{
		using ::Passes::Meshes::Scene;
	}
	namespace Environment
	{
		using ::Passes::Environment::Sky;
	}
	namespace Environment
	{
		using ::Passes::Environment::CubeSky;
	}
	namespace Environment
	{
		using ::Passes::Environment::CubeMapDownsample;
	}
	namespace Environment
	{
		using ::Passes::Environment::CubeMapEnviromentProcessor;
	}
	namespace Post
	{
		namespace AA
		{
			using ::Passes::Post::AA::SMAA;
		}
	}
	namespace Editor
	{
		using ::Passes::Editor::stencil_renderer;
	}
	namespace Post
	{
		using ::Passes::Post::Tonemap;
	}
	namespace UI
	{
		using ::Passes::UI::UI_PreDraw;
	}
	namespace UI
	{
		using ::Passes::UI::UI_Render;
	}
	namespace Editor
	{
		using ::Passes::Editor::AssetPreview;
	}
	namespace Post
	{
		namespace Upscale
		{
			using ::Passes::Post::Upscale::UpscalingDLSS;
		}
	}
	namespace Post
	{
		namespace Upscale
		{
			using ::Passes::Post::Upscale::NormalRoughnessRepack;
		}
	}
	namespace Post
	{
		namespace Upscale
		{
			using ::Passes::Post::Upscale::UpscalingDLSSRR;
		}
	}
	namespace Meshes
	{
		using ::Passes::Meshes::GBufferDownsampler;
	}
	namespace GI
	{
		namespace Voxel
		{
			namespace Dev
			{
				using ::Passes::GI::Voxel::Dev::VoxelDebug;
			}
		}
	}
	namespace Reflections
	{
		using ::Passes::Reflections::ReflectionRTXHalf;
	}
	namespace Reflections
	{
		using ::Passes::Reflections::ReflectionRTX;
	}
	namespace Shadows
	{
		using ::Passes::Shadows::ShadowRTX;
	}
	namespace GI
	{
		using ::Passes::GI::IndirectRTXHalf;
	}
	namespace GI
	{
		using ::Passes::GI::IndirectRTX;
	}
	namespace Reflections
	{
		using ::Passes::Reflections::ReflCombine;
	}
	namespace GI
	{
		using ::Passes::GI::RTXCombine;
	}
	namespace GI
	{
		namespace Voxel
		{
			using ::Passes::GI::Voxel::Voxelize;
		}
	}
	namespace GI
	{
		namespace Voxel
		{
			using ::Passes::GI::Voxel::Lighting;
		}
	}
	namespace GI
	{
		namespace Voxel
		{
			using ::Passes::GI::Voxel::Mipmapping;
		}
	}
	namespace GI
	{
		namespace Voxel
		{
			using ::Passes::GI::Voxel::VoxelScreen;
		}
	}
	namespace Reflections
	{
		using ::Passes::Reflections::ScreenReflection;
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_GatherDispatch;
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_RenderPages;
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_HiZRebuild;
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_BlockerClassify;
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_BlockerSearch;
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_ScreenSpaceShadow;
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_ShadowResolve;
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_Combine;
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			namespace Dev
			{
				using ::Passes::Shadows::VSM::Dev::VSM_DebugClassifyOverlay;
			}
		}
	}
	namespace Shadows
	{
		namespace VSM
		{
			using ::Passes::Shadows::VSM::VSM_DepthAnalysis;
		}
	}
}

export namespace Pipelines
{
	namespace Editor
	{
		using ::Pipelines::Editor::AssetPipeline;
	}
	namespace Frame
	{
		using ::Pipelines::Frame::MainPipeline;
	}
	namespace UI
	{
		using ::Pipelines::UI::UIPipeline;
	}
}
