// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.PSO.Dev.DebugLinesOccluded;

import Core;
import :PSO;
import :Enums;
import :Types;


export namespace PSOS
{
	namespace Dev
	{
		struct DebugLinesOccluded: public PSOBase
		{
			struct Keys {
				GEN_DEF_COMP(Keys);
			private:
				SERIALIZE()
				{
				}
			};

			GEN_GRAPHICS_PSO(DebugLinesOccluded)


			SimplePSO init_pso(Keys & key, std::function<void(SimplePSO&, Keys&)> f)
			{


				SimplePSO mpso("DebugLinesOccluded");
				if(f) f(mpso,key);

				mpso.root_signature = Layouts::DefaultLayout;

				mpso.vertex.file_name = "shaders/debug/debug_lines.hlsl";
				mpso.vertex.entry_point = "VS";
				mpso.vertex.flags = HAL::ShaderOptions::None;
			
				mpso.pixel.file_name = "shaders/debug/debug_lines.hlsl";
				mpso.pixel.entry_point = "PS";
				mpso.pixel.flags = HAL::ShaderOptions::None;
			

				mpso.rtv_formats = { HAL::Format::R8G8B8A8_UNORM };	
				mpso.blend = { HAL::Blends::AlphaBlend };

				mpso.ds =HAL::Format::D32_FLOAT;
				mpso.depth_write =false;
				mpso.depth_func =HAL::ComparisonFunc::LESS;
				mpso.cull =HAL::CullMode::None;
				return mpso;
			}

			private:
			SERIALIZE()
			{
				ar&NVP(wrap(psos));
			}
		};
	}
}