// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Tables.UI.Text.GlyphQuad;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)
	namespace UI
	{
		namespace Text
		{
			struct GlyphQuad
			{
				static constexpr SlotID ID = SlotID::GlyphQuad;
				float4 pos;
				float4 uv;
				float4 color;
				uint atlas;
				uint is_color;
				float4& GetPos() { return pos; }
				float4& GetUv() { return uv; }
				float4& GetColor() { return color; }
				uint& GetAtlas() { return atlas; }
				uint& GetIs_color() { return is_color; }
				static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
				template<class Compiler>
				void compile(Compiler& compiler) const
				{
					compiler.compile(pos, "GlyphQuad::pos");
					compiler.compile(uv, "GlyphQuad::uv");
					compiler.compile(color, "GlyphQuad::color");
					compiler.compile(atlas, "GlyphQuad::atlas");
					compiler.compile(is_color, "GlyphQuad::is_color");
				}
				using Compiled = GlyphQuad;

				static std::string get_typename()
				{
					return "Tables::GlyphQuad";
				}
				private:
				SERIALIZE()
				{
					ar& NVP(pos);
					ar& NVP(uv);
					ar& NVP(color);
					ar& NVP(atlas);
					ar& NVP(is_color);
				}

			};
		}
	}
	#pragma pack(pop)
}

