// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Tables.Post.BloomDownsample;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)
	namespace Post
	{
		struct BloomDownsample
		{
			static constexpr SlotID ID = SlotID::BloomDownsample;
			float2 source_texel;
			uint karis;
			float threshold;
			float knee;
			uint unjitter;
			HLSL::Texture2D<float4> source;
			HLSL::StructuredBuffer<float4> exposure_state;
			HLSL::RWTexture2D<float4> target;
			HLSL::Texture2D<float4>& GetSource() { return source; }
			HLSL::RWTexture2D<float4>& GetTarget() { return target; }
			float2& GetSource_texel() { return source_texel; }
			uint& GetKaris() { return karis; }
			float& GetThreshold() { return threshold; }
			float& GetKnee() { return knee; }
			HLSL::StructuredBuffer<float4>& GetExposure_state() { return exposure_state; }
			uint& GetUnjitter() { return unjitter; }
			static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
			template<class Compiler>
			void compile(Compiler& compiler) const
			{
				compiler.compile(source_texel, "BloomDownsample::source_texel");
				compiler.compile(karis, "BloomDownsample::karis");
				compiler.compile(threshold, "BloomDownsample::threshold");
				compiler.compile(knee, "BloomDownsample::knee");
				compiler.compile(unjitter, "BloomDownsample::unjitter");
				compiler.compile(source, "BloomDownsample::source");
				compiler.compile(exposure_state, "BloomDownsample::exposure_state");
				compiler.compile(target, "BloomDownsample::target");
			}
			struct Compiled
			{
				float2 source_texel; // float2
				uint karis; // uint
				float threshold; // float
				float knee; // float
				uint unjitter; // uint
				uint source; // Texture2D<float4>
				uint exposure_state; // StructuredBuffer<float4>
				uint target; // RWTexture2D<float4>

			
				private:
				SERIALIZE()
				{
					ar& NVP(source_texel);
					ar& NVP(karis);
					ar& NVP(threshold);
					ar& NVP(knee);
					ar& NVP(unjitter);
				}


			};

			static std::string get_typename()
			{
				return "Tables::BloomDownsample";
			}
			private:
			SERIALIZE()
			{
				ar& NVP(source_texel);
				ar& NVP(karis);
				ar& NVP(threshold);
				ar& NVP(knee);
				ar& NVP(unjitter);
			}

		};
	}
	#pragma pack(pop)
}

