// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.PSO.Meshes.GatherPipeline;

import Core;
import :PSO;
import :Enums;
import :Types;


export namespace PSOS
{
	namespace Meshes
	{
		struct GatherPipeline: public PSOBase
		{
			struct Keys {
				KeyValue<int, Nullable> CheckFrustum;
				KeyValue<int, Nullable> CaptureVisibility;
				GEN_DEF_COMP(Keys);
			private:
				SERIALIZE()
				{
					ar&NVP(CheckFrustum);
					ar&NVP(CaptureVisibility);
				}
			};

			GEN_COMPUTE_PSO(GatherPipeline, CheckFrustum, CaptureVisibility)
			GEN_KEY(CheckFrustum, true);
			GEN_KEY(CaptureVisibility, true);


			SimplePSO init_pso(Keys & key, std::function<void(SimplePSO&, Keys&)> f)
			{
				static const ShaderDefine<&Keys::CheckFrustum,&SimpleComputePSO::compute> CheckFrustum = "CHECK_FRUSTUM";
				static const ShaderDefine<&Keys::CaptureVisibility,&SimpleComputePSO::compute> CaptureVisibility = "CAPTURE_VISIBILITY";


				SimplePSO mpso("GatherPipeline");
				if(f) f(mpso,key);

				mpso.root_signature = Layouts::DefaultLayout;

				mpso.compute.file_name = "shaders/gbuffer/gather_pipeline.hlsl";
				mpso.compute.entry_point = "CS";
				mpso.compute.flags = HAL::ShaderOptions::None;
			
				CheckFrustum.Apply(mpso, key);
				CaptureVisibility.Apply(mpso, key);
				return mpso;
			}

			private:
			SERIALIZE()
			{
				ar&NVP(wrap(psos));
			}
		};
	}
}