// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once

struct ColorRTX: public RaytraceRaygen<ColorRTX>
{
	static const constexpr uint ID = 3;
	static const constexpr std::string_view shader = "shaders\\raytracing.hlsl";
	static const constexpr std::wstring_view raygen = L"ColorRTXRaygenShader";
};