// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once

struct DDGIProbeTrace: public RaytraceRaygen<DDGIProbeTrace>
{
	static const constexpr uint ID = 10;
	static const constexpr std::string_view shader = "shaders\\ddgi/ddgi_probe_trace.hlsl";
	static const constexpr std::wstring_view raygen = L"DDGIProbeTraceRaygenShader";
};