# Sharpmake AppVeyor CI configuration

image:
- macOS
- Ubuntu
- Visual Studio 2019

skip_commits:
  files:
    - docs/*

platform:
- Any CPU

configuration:
- Debug
- Release

init:
- sh: >-
    export NUGET_HTTP_CACHE_PATH=$PWD/tmp/nuget_cache

before_build:
- cmd: bootstrap.bat
- sh: ./bootstrap.sh

build_script:
- cmd: CompileSharpmake.bat Sharpmake.sln "%CONFIGURATION%" "%PLATFORM%"
- sh: ./CompileSharpmake.sh Sharpmake.sln "${CONFIGURATION}" "${PLATFORM}"

test:
  assemblies:
    - 'tmp/bin/*/Sharpmake.UnitTests/Sharpmake.UnitTests.dll'

after_test:
- cmd: python regression_test.py
