// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.PSO.Denoise.NRD.NRD_IndirectCombine;

import Core;
import :PSO;
import :Enums;
import :Types;


export namespace PSOS
{
	namespace Denoise
	{
		namespace NRD
		{
			struct NRD_IndirectCombine: public PSOBase
			{
				struct Keys {
					GEN_DEF_COMP(Keys);
				private:
					SERIALIZE()
					{
					}
				};

				GEN_COMPUTE_PSO(NRD_IndirectCombine)


				SimplePSO init_pso(Keys & key, std::function<void(SimplePSO&, Keys&)> f)
				{


					SimplePSO mpso("NRD_IndirectCombine");
					if(f) f(mpso,key);

					mpso.root_signature = Layouts::DefaultLayout;

					mpso.compute.file_name = "shaders/nrd/nrd_indirect_combine.hlsl";
					mpso.compute.entry_point = "CS";
					mpso.compute.flags = HAL::ShaderOptions::None;
			
					return mpso;
				}

				private:
				SERIALIZE()
				{
					ar&NVP(wrap(psos));
				}
			};
		}
	}
}