// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#ifndef SLOT_4
	#define SLOT_4
#else
	#error Slot 4 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/BloomCopy.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_BloomCopy { uint offset; };
static _CB_BloomCopy pass_BloomCopy = { _hal_push.s4 };
#else
ConstantBuffer<CB> pass_BloomCopy: register(b4, space4);
#endif
ConstantBuffer<BloomCopy> CreateBloomCopy()
{
	return ResourceDescriptorHeap[pass_BloomCopy.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<BloomCopy> bloomCopy_global = CreateBloomCopy();
ConstantBuffer<BloomCopy> GetBloomCopy() { return bloomCopy_global; }
#endif