// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_4
	#define SLOT_4
#else
	#error Slot 4 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/BlueNoise.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_BlueNoise { uint offset; };
static _CB_BlueNoise pass_BlueNoise = { _hal_push.s4 };
#else
ConstantBuffer<CB> pass_BlueNoise: register(b4, space4);
#endif

ConstantBuffer<BlueNoise> CreateBlueNoise()
{
	return ResourceDescriptorHeap[pass_BlueNoise.offset];
}
			
#ifndef NO_GLOBAL
static const ConstantBuffer<BlueNoise> blueNoise_global = CreateBlueNoise();
ConstantBuffer<BlueNoise> GetBlueNoise(){ return blueNoise_global; }
#endif