// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_4
	#define SLOT_4
#else
	#error Slot 4 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/CopyTexture.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_CopyTexture { uint offset; };
static _CB_CopyTexture pass_CopyTexture = { _hal_push.s4 };
#else
ConstantBuffer<CB> pass_CopyTexture: register(b4, space4);
#endif

ConstantBuffer<CopyTexture> CreateCopyTexture()
{
	return ResourceDescriptorHeap[pass_CopyTexture.offset];
}
			
#ifndef NO_GLOBAL
static const ConstantBuffer<CopyTexture> copyTexture_global = CreateCopyTexture();
ConstantBuffer<CopyTexture> GetCopyTexture(){ return copyTexture_global; }
#endif