// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_5
	#define SLOT_5
#else
	#error Slot 5 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/DDGIProbeSelectData.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_DDGIProbeSelectData { uint offset; };
static _CB_DDGIProbeSelectData pass_DDGIProbeSelectData = { _hal_push.s5 };
#else
ConstantBuffer<CB> pass_DDGIProbeSelectData: register(b5, space5);
#endif
ConstantBuffer<DDGIProbeSelectData> CreateDDGIProbeSelectData()
{
	return ResourceDescriptorHeap[pass_DDGIProbeSelectData.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<DDGIProbeSelectData> dDGIProbeSelectData_global = CreateDDGIProbeSelectData();
ConstantBuffer<DDGIProbeSelectData> GetDDGIProbeSelectData() { return dDGIProbeSelectData_global; }
#endif