// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#ifndef SLOT_7
	#define SLOT_7
#else
	#error Slot 7 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/DebugViewDraw.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_DebugViewDraw { uint offset; };
static _CB_DebugViewDraw pass_DebugViewDraw = { _hal_push.s7 };
#else
ConstantBuffer<CB> pass_DebugViewDraw: register(b7, space7);
#endif
ConstantBuffer<DebugViewDraw> CreateDebugViewDraw()
{
	return ResourceDescriptorHeap[pass_DebugViewDraw.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<DebugViewDraw> debugViewDraw_global = CreateDebugViewDraw();
ConstantBuffer<DebugViewDraw> GetDebugViewDraw() { return debugViewDraw_global; }
#endif