// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_5
	#define SLOT_5
#else
	#error Slot 5 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/DenoiserReflectionResolve.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_DenoiserReflectionResolve { uint offset; };
static _CB_DenoiserReflectionResolve pass_DenoiserReflectionResolve = { _hal_push.s5 };
#else
ConstantBuffer<CB> pass_DenoiserReflectionResolve: register(b5, space5);
#endif

ConstantBuffer<DenoiserReflectionResolve> CreateDenoiserReflectionResolve()
{
	return ResourceDescriptorHeap[pass_DenoiserReflectionResolve.offset];
}
			
#ifndef NO_GLOBAL
static const ConstantBuffer<DenoiserReflectionResolve> denoiserReflectionResolve_global = CreateDenoiserReflectionResolve();
ConstantBuffer<DenoiserReflectionResolve> GetDenoiserReflectionResolve(){ return denoiserReflectionResolve_global; }
#endif