// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_5
	#define SLOT_5
#else
	#error Slot 5 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/DenoiserShadow_FilterLocal.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_DenoiserShadow_FilterLocal { uint offset; };
static _CB_DenoiserShadow_FilterLocal pass_DenoiserShadow_FilterLocal = { _hal_push.s5 };
#else
ConstantBuffer<CB> pass_DenoiserShadow_FilterLocal: register(b5, space5);
#endif
ConstantBuffer<DenoiserShadow_FilterLocal> CreateDenoiserShadow_FilterLocal()
{
	return ResourceDescriptorHeap[pass_DenoiserShadow_FilterLocal.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<DenoiserShadow_FilterLocal> denoiserShadow_FilterLocal_global = CreateDenoiserShadow_FilterLocal();
ConstantBuffer<DenoiserShadow_FilterLocal> GetDenoiserShadow_FilterLocal() { return denoiserShadow_FilterLocal_global; }
#endif