// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_4
	#define SLOT_4
#else
	#error Slot 4 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/DownsampleDepth.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_DownsampleDepth { uint offset; };
static _CB_DownsampleDepth pass_DownsampleDepth = { _hal_push.s4 };
#else
ConstantBuffer<CB> pass_DownsampleDepth: register(b4, space4);
#endif

ConstantBuffer<DownsampleDepth> CreateDownsampleDepth()
{
	return ResourceDescriptorHeap[pass_DownsampleDepth.offset];
}
			
#ifndef NO_GLOBAL
static const ConstantBuffer<DownsampleDepth> downsampleDepth_global = CreateDownsampleDepth();
ConstantBuffer<DownsampleDepth> GetDownsampleDepth(){ return downsampleDepth_global; }
#endif