// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_4
	#define SLOT_4
#else
	#error Slot 4 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/FSR.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_FSR { uint offset; };
static _CB_FSR pass_FSR = { _hal_push.s4 };
#else
ConstantBuffer<CB> pass_FSR: register(b4, space4);
#endif

ConstantBuffer<FSR> CreateFSR()
{
	return ResourceDescriptorHeap[pass_FSR.offset];
}
			
#ifndef NO_GLOBAL
static const FSR fSR_global = CreateFSR();
const FSR GetFSR(){ return fSR_global; }
#endif