// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_6
	#define SLOT_6
#else
	#error Slot 6 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/GBufferDownsample.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_GBufferDownsample { uint offset; };
static _CB_GBufferDownsample pass_GBufferDownsample = { _hal_push.s6 };
#else
ConstantBuffer<CB> pass_GBufferDownsample: register(b6, space6);
#endif

ConstantBuffer<GBufferDownsample> CreateGBufferDownsample()
{
	return ResourceDescriptorHeap[pass_GBufferDownsample.offset];
}
			
#ifndef NO_GLOBAL
static const ConstantBuffer<GBufferDownsample> gBufferDownsample_global = CreateGBufferDownsample();
ConstantBuffer<GBufferDownsample> GetGBufferDownsample(){ return gBufferDownsample_global; }
#endif