// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#ifndef SLOT_8
	#define SLOT_8
#else
	#error Slot 8 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/IndirectRTXHalfGBuffer.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_IndirectRTXHalfGBuffer { uint offset; };
static _CB_IndirectRTXHalfGBuffer pass_IndirectRTXHalfGBuffer = { _hal_push.s8 };
#else
ConstantBuffer<CB> pass_IndirectRTXHalfGBuffer: register(b8, space8);
#endif
ConstantBuffer<IndirectRTXHalfGBuffer> CreateIndirectRTXHalfGBuffer()
{
	return ResourceDescriptorHeap[pass_IndirectRTXHalfGBuffer.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<IndirectRTXHalfGBuffer> indirectRTXHalfGBuffer_global = CreateIndirectRTXHalfGBuffer();
ConstantBuffer<IndirectRTXHalfGBuffer> GetIndirectRTXHalfGBuffer() { return indirectRTXHalfGBuffer_global; }
#endif