// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_11
	#define SLOT_11
#else
	#error Slot 11 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/MaterialInfo.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_MaterialInfo { uint offset; };
static _CB_MaterialInfo pass_MaterialInfo = { _hal_push.s11 };
#else
ConstantBuffer<CB> pass_MaterialInfo: register(b11, space11);
#endif

ConstantBuffer<MaterialInfo> CreateMaterialInfo()
{
	return ResourceDescriptorHeap[pass_MaterialInfo.offset];
}
			
#ifndef NO_GLOBAL
static const ConstantBuffer<MaterialInfo> materialInfo_global = CreateMaterialInfo();
ConstantBuffer<MaterialInfo> GetMaterialInfo(){ return materialInfo_global; }
#endif