// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#ifndef SLOT_9
	#define SLOT_9
#else
	#error Slot 9 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/MeshletCaptureWrite.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_MeshletCaptureWrite { uint offset; };
static _CB_MeshletCaptureWrite pass_MeshletCaptureWrite = { _hal_push.s9 };
#else
ConstantBuffer<CB> pass_MeshletCaptureWrite: register(b9, space9);
#endif
ConstantBuffer<MeshletCaptureWrite> CreateMeshletCaptureWrite()
{
	return ResourceDescriptorHeap[pass_MeshletCaptureWrite.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<MeshletCaptureWrite> meshletCaptureWrite_global = CreateMeshletCaptureWrite();
ConstantBuffer<MeshletCaptureWrite> GetMeshletCaptureWrite() { return meshletCaptureWrite_global; }
#endif