// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_4
	#define SLOT_4
#else
	#error Slot 4 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/MipMapping.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_MipMapping { uint offset; };
static _CB_MipMapping pass_MipMapping = { _hal_push.s4 };
#else
ConstantBuffer<CB> pass_MipMapping: register(b4, space4);
#endif

ConstantBuffer<MipMapping> CreateMipMapping()
{
	return ResourceDescriptorHeap[pass_MipMapping.offset];
}
			
#ifndef NO_GLOBAL
static const ConstantBuffer<MipMapping> mipMapping_global = CreateMipMapping();
ConstantBuffer<MipMapping> GetMipMapping(){ return mipMapping_global; }
#endif