// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#ifndef SLOT_6
	#define SLOT_6
#else
	#error Slot 6 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/NormalRoughnessRepackParams.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_NormalRoughnessRepackParams { uint offset; };
static _CB_NormalRoughnessRepackParams pass_NormalRoughnessRepackParams = { _hal_push.s6 };
#else
ConstantBuffer<CB> pass_NormalRoughnessRepackParams: register(b6, space6);
#endif
ConstantBuffer<NormalRoughnessRepackParams> CreateNormalRoughnessRepackParams()
{
	return ResourceDescriptorHeap[pass_NormalRoughnessRepackParams.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<NormalRoughnessRepackParams> normalRoughnessRepackParams_global = CreateNormalRoughnessRepackParams();
ConstantBuffer<NormalRoughnessRepackParams> GetNormalRoughnessRepackParams() { return normalRoughnessRepackParams_global; }
#endif