// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_4
	#define SLOT_4
#else
	#error Slot 4 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/NRD_IndirectCombineParams.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_NRD_IndirectCombineParams { uint offset; };
static _CB_NRD_IndirectCombineParams pass_NRD_IndirectCombineParams = { _hal_push.s4 };
#else
ConstantBuffer<CB> pass_NRD_IndirectCombineParams: register(b4, space4);
#endif
ConstantBuffer<NRD_IndirectCombineParams> CreateNRD_IndirectCombineParams()
{
	return ResourceDescriptorHeap[pass_NRD_IndirectCombineParams.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<NRD_IndirectCombineParams> nRD_IndirectCombineParams_global = CreateNRD_IndirectCombineParams();
ConstantBuffer<NRD_IndirectCombineParams> GetNRD_IndirectCombineParams() { return nRD_IndirectCombineParams_global; }
#endif