// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_6
	#define SLOT_6
#else
	#error Slot 6 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/NRD_UnpackDebugParams.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_NRD_UnpackDebugParams { uint offset; };
static _CB_NRD_UnpackDebugParams pass_NRD_UnpackDebugParams = { _hal_push.s6 };
#else
ConstantBuffer<CB> pass_NRD_UnpackDebugParams: register(b6, space6);
#endif
ConstantBuffer<NRD_UnpackDebugParams> CreateNRD_UnpackDebugParams()
{
	return ResourceDescriptorHeap[pass_NRD_UnpackDebugParams.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<NRD_UnpackDebugParams> nRD_UnpackDebugParams_global = CreateNRD_UnpackDebugParams();
ConstantBuffer<NRD_UnpackDebugParams> GetNRD_UnpackDebugParams() { return nRD_UnpackDebugParams_global; }
#endif