// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_4
	#define SLOT_4
#else
	#error Slot 4 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/NRD_ShadowCombineParams.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_NRD_ShadowCombineParams { uint offset; };
static _CB_NRD_ShadowCombineParams pass_NRD_ShadowCombineParams = { _hal_push.s4 };
#else
ConstantBuffer<CB> pass_NRD_ShadowCombineParams: register(b4, space4);
#endif
ConstantBuffer<NRD_ShadowCombineParams> CreateNRD_ShadowCombineParams()
{
	return ResourceDescriptorHeap[pass_NRD_ShadowCombineParams.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<NRD_ShadowCombineParams> nRD_ShadowCombineParams_global = CreateNRD_ShadowCombineParams();
ConstantBuffer<NRD_ShadowCombineParams> GetNRD_ShadowCombineParams() { return nRD_ShadowCombineParams_global; }
#endif