// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#ifndef SLOT_4
	#define SLOT_4
#else
	#error Slot 4 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/PSSMConstants.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_PSSMConstants { uint offset; };
static _CB_PSSMConstants pass_PSSMConstants = { _hal_push.s4 };
#else
ConstantBuffer<CB> pass_PSSMConstants: register(b4, space4);
#endif
ConstantBuffer<PSSMConstants> CreatePSSMConstants()
{
	return ResourceDescriptorHeap[pass_PSSMConstants.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<PSSMConstants> pSSMConstants_global = CreatePSSMConstants();
ConstantBuffer<PSSMConstants> GetPSSMConstants() { return pSSMConstants_global; }
#endif