// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_5
	#define SLOT_5
#else
	#error Slot 5 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/PSSMData.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_PSSMData { uint offset; };
static _CB_PSSMData pass_PSSMData = { _hal_push.s5 };
#else
ConstantBuffer<CB> pass_PSSMData: register(b5, space5);
#endif

ConstantBuffer<PSSMData> CreatePSSMData()
{
	return ResourceDescriptorHeap[pass_PSSMData.offset];
}
			
#ifndef NO_GLOBAL
static const ConstantBuffer<PSSMData> pSSMData_global = CreatePSSMData();
ConstantBuffer<PSSMData> GetPSSMData(){ return pSSMData_global; }
#endif