// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_6
	#define SLOT_6
#else
	#error Slot 6 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/REBLUR_PrePassResources.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_REBLUR_PrePassResources { uint offset; };
static _CB_REBLUR_PrePassResources pass_REBLUR_PrePassResources = { _hal_push.s6 };
#else
ConstantBuffer<CB> pass_REBLUR_PrePassResources: register(b6, space6);
#endif
ConstantBuffer<REBLUR_PrePassResources> CreateREBLUR_PrePassResources()
{
	return ResourceDescriptorHeap[pass_REBLUR_PrePassResources.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<REBLUR_PrePassResources> rEBLUR_PrePassResources_global = CreateREBLUR_PrePassResources();
ConstantBuffer<REBLUR_PrePassResources> GetREBLUR_PrePassResources() { return rEBLUR_PrePassResources_global; }
#endif