// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_4
	#define SLOT_4
#else
	#error Slot 4 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/ReflectionCombine.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_ReflectionCombine { uint offset; };
static _CB_ReflectionCombine pass_ReflectionCombine = { _hal_push.s4 };
#else
ConstantBuffer<CB> pass_ReflectionCombine: register(b4, space4);
#endif

ConstantBuffer<ReflectionCombine> CreateReflectionCombine()
{
	return ResourceDescriptorHeap[pass_ReflectionCombine.offset];
}
			
#ifndef NO_GLOBAL
static const ConstantBuffer<ReflectionCombine> reflectionCombine_global = CreateReflectionCombine();
ConstantBuffer<ReflectionCombine> GetReflectionCombine(){ return reflectionCombine_global; }
#endif