// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#ifndef SLOT_6
	#define SLOT_6
#else
	#error Slot 6 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/SIGMA_BlurFirstPass1Resources.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_SIGMA_BlurFirstPass1Resources { uint offset; };
static _CB_SIGMA_BlurFirstPass1Resources pass_SIGMA_BlurFirstPass1Resources = { _hal_push.s6 };
#else
ConstantBuffer<CB> pass_SIGMA_BlurFirstPass1Resources: register(b6, space6);
#endif
ConstantBuffer<SIGMA_BlurFirstPass1Resources> CreateSIGMA_BlurFirstPass1Resources()
{
	return ResourceDescriptorHeap[pass_SIGMA_BlurFirstPass1Resources.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<SIGMA_BlurFirstPass1Resources> sIGMA_BlurFirstPass1Resources_global = CreateSIGMA_BlurFirstPass1Resources();
ConstantBuffer<SIGMA_BlurFirstPass1Resources> GetSIGMA_BlurFirstPass1Resources() { return sIGMA_BlurFirstPass1Resources_global; }
#endif