// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#ifndef SLOT_6
	#define SLOT_6
#else
	#error Slot 6 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/SIGMA_TemporalStabilizationResources.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_SIGMA_TemporalStabilizationResources { uint offset; };
static _CB_SIGMA_TemporalStabilizationResources pass_SIGMA_TemporalStabilizationResources = { _hal_push.s6 };
#else
ConstantBuffer<CB> pass_SIGMA_TemporalStabilizationResources: register(b6, space6);
#endif
ConstantBuffer<SIGMA_TemporalStabilizationResources> CreateSIGMA_TemporalStabilizationResources()
{
	return ResourceDescriptorHeap[pass_SIGMA_TemporalStabilizationResources.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<SIGMA_TemporalStabilizationResources> sIGMA_TemporalStabilizationResources_global = CreateSIGMA_TemporalStabilizationResources();
ConstantBuffer<SIGMA_TemporalStabilizationResources> GetSIGMA_TemporalStabilizationResources() { return sIGMA_TemporalStabilizationResources_global; }
#endif