// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#ifndef SLOT_6
	#define SLOT_6
#else
	#error Slot 6 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/SIGMA_SmoothTilesResources.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_SIGMA_SmoothTilesResources { uint offset; };
static _CB_SIGMA_SmoothTilesResources pass_SIGMA_SmoothTilesResources = { _hal_push.s6 };
#else
ConstantBuffer<CB> pass_SIGMA_SmoothTilesResources: register(b6, space6);
#endif
ConstantBuffer<SIGMA_SmoothTilesResources> CreateSIGMA_SmoothTilesResources()
{
	return ResourceDescriptorHeap[pass_SIGMA_SmoothTilesResources.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<SIGMA_SmoothTilesResources> sIGMA_SmoothTilesResources_global = CreateSIGMA_SmoothTilesResources();
ConstantBuffer<SIGMA_SmoothTilesResources> GetSIGMA_SmoothTilesResources() { return sIGMA_SmoothTilesResources_global; }
#endif