// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_5
	#define SLOT_5
#else
	#error Slot 5 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/SkyFace.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_SkyFace { uint offset; };
static _CB_SkyFace pass_SkyFace = { _hal_push.s5 };
#else
ConstantBuffer<CB> pass_SkyFace: register(b5, space5);
#endif

ConstantBuffer<SkyFace> CreateSkyFace()
{
	return ResourceDescriptorHeap[pass_SkyFace.offset];
}
			
#ifndef NO_GLOBAL
static const SkyFace skyFace_global = CreateSkyFace();
const SkyFace GetSkyFace(){ return skyFace_global; }
#endif