// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_4
	#define SLOT_4
#else
	#error Slot 4 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/StatGraph.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_StatGraph { uint offset; };
static _CB_StatGraph pass_StatGraph = { _hal_push.s4 };
#else
ConstantBuffer<CB> pass_StatGraph: register(b4, space4);
#endif

ConstantBuffer<StatGraph> CreateStatGraph()
{
	return ResourceDescriptorHeap[pass_StatGraph.offset];
}
			
#ifndef NO_GLOBAL
static const ConstantBuffer<StatGraph> statGraph_global = CreateStatGraph();
ConstantBuffer<StatGraph> GetStatGraph(){ return statGraph_global; }
#endif