// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#ifndef SLOT_5
	#define SLOT_5
#else
	#error Slot 5 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/VoxelZero.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_VoxelZero { uint offset; };
static _CB_VoxelZero pass_VoxelZero = { _hal_push.s5 };
#else
ConstantBuffer<CB> pass_VoxelZero: register(b5, space5);
#endif
ConstantBuffer<VoxelZero> CreateVoxelZero()
{
	return ResourceDescriptorHeap[pass_VoxelZero.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<VoxelZero> voxelZero_global = CreateVoxelZero();
ConstantBuffer<VoxelZero> GetVoxelZero() { return voxelZero_global; }
#endif