// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_5
	#define SLOT_5
#else
	#error Slot 5 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/VoxelVisibility.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_VoxelVisibility { uint offset; };
static _CB_VoxelVisibility pass_VoxelVisibility = { _hal_push.s5 };
#else
ConstantBuffer<CB> pass_VoxelVisibility: register(b5, space5);
#endif
ConstantBuffer<VoxelVisibility> CreateVoxelVisibility()
{
	return ResourceDescriptorHeap[pass_VoxelVisibility.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<VoxelVisibility> voxelVisibility_global = CreateVoxelVisibility();
ConstantBuffer<VoxelVisibility> GetVoxelVisibility() { return voxelVisibility_global; }
#endif