// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_4
	#define SLOT_4
#else
	#error Slot 4 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/VoxelInfo.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_VoxelInfo { uint offset; };
static _CB_VoxelInfo pass_VoxelInfo = { _hal_push.s4 };
#else
ConstantBuffer<CB> pass_VoxelInfo: register(b4, space4);
#endif
ConstantBuffer<VoxelInfo> CreateVoxelInfo()
{
	return ResourceDescriptorHeap[pass_VoxelInfo.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<VoxelInfo> voxelInfo_global = CreateVoxelInfo();
ConstantBuffer<VoxelInfo> GetVoxelInfo() { return voxelInfo_global; }
#endif