// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_6
	#define SLOT_6
#else
	#error Slot 6 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/VoxelOutput.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_VoxelOutput { uint offset; };
static _CB_VoxelOutput pass_VoxelOutput = { _hal_push.s6 };
#else
ConstantBuffer<CB> pass_VoxelOutput: register(b6, space6);
#endif

ConstantBuffer<VoxelOutput> CreateVoxelOutput()
{
	return ResourceDescriptorHeap[pass_VoxelOutput.offset];
}
			
#ifndef NO_GLOBAL
static const VoxelOutput voxelOutput_global = CreateVoxelOutput();
const VoxelOutput GetVoxelOutput(){ return voxelOutput_global; }
#endif