// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_6
	#define SLOT_6
#else
	#error Slot 6 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/VoxelUpscale.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_VoxelUpscale { uint offset; };
static _CB_VoxelUpscale pass_VoxelUpscale = { _hal_push.s6 };
#else
ConstantBuffer<CB> pass_VoxelUpscale: register(b6, space6);
#endif
ConstantBuffer<VoxelUpscale> CreateVoxelUpscale()
{
	return ResourceDescriptorHeap[pass_VoxelUpscale.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<VoxelUpscale> voxelUpscale_global = CreateVoxelUpscale();
ConstantBuffer<VoxelUpscale> GetVoxelUpscale() { return voxelUpscale_global; }
#endif