// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#ifndef SLOT_7
	#define SLOT_7
#else
	#error Slot 7 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/Voxelization.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_Voxelization { uint offset; };
static _CB_Voxelization pass_Voxelization = { _hal_push.s7 };
#else
ConstantBuffer<CB> pass_Voxelization: register(b7, space7);
#endif
ConstantBuffer<Voxelization> CreateVoxelization()
{
	return ResourceDescriptorHeap[pass_Voxelization.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<Voxelization> voxelization_global = CreateVoxelization();
ConstantBuffer<Voxelization> GetVoxelization() { return voxelization_global; }
#endif