// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_5
	#define SLOT_5
#else
	#error Slot 5 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/VoxelCopy.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_VoxelCopy { uint offset; };
static _CB_VoxelCopy pass_VoxelCopy = { _hal_push.s5 };
#else
ConstantBuffer<CB> pass_VoxelCopy: register(b5, space5);
#endif

ConstantBuffer<VoxelCopy> CreateVoxelCopy()
{
	return ResourceDescriptorHeap[pass_VoxelCopy.offset];
}
			
#ifndef NO_GLOBAL
static const VoxelCopy voxelCopy_global = CreateVoxelCopy();
const VoxelCopy GetVoxelCopy(){ return voxelCopy_global; }
#endif