// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_4
	#define SLOT_4
#else
	#error Slot 4 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/VSMCopyPageDepth.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_VSMCopyPageDepth { uint offset; };
static _CB_VSMCopyPageDepth pass_VSMCopyPageDepth = { _hal_push.s4 };
#else
ConstantBuffer<CB> pass_VSMCopyPageDepth: register(b4, space4);
#endif
ConstantBuffer<VSMCopyPageDepth> CreateVSMCopyPageDepth()
{
	return ResourceDescriptorHeap[pass_VSMCopyPageDepth.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<VSMCopyPageDepth> vSMCopyPageDepth_global = CreateVSMCopyPageDepth();
ConstantBuffer<VSMCopyPageDepth> GetVSMCopyPageDepth() { return vSMCopyPageDepth_global; }
#endif