// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_4
	#define SLOT_4
#else
	#error Slot 4 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/VSMSearchVerdictInitDispatch.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_VSMSearchVerdictInitDispatch { uint offset; };
static _CB_VSMSearchVerdictInitDispatch pass_VSMSearchVerdictInitDispatch = { _hal_push.s4 };
#else
ConstantBuffer<CB> pass_VSMSearchVerdictInitDispatch: register(b4, space4);
#endif
ConstantBuffer<VSMSearchVerdictInitDispatch> CreateVSMSearchVerdictInitDispatch()
{
	return ResourceDescriptorHeap[pass_VSMSearchVerdictInitDispatch.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<VSMSearchVerdictInitDispatch> vSMSearchVerdictInitDispatch_global = CreateVSMSearchVerdictInitDispatch();
ConstantBuffer<VSMSearchVerdictInitDispatch> GetVSMSearchVerdictInitDispatch() { return vSMSearchVerdictInitDispatch_global; }
#endif