// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_7
	#define SLOT_7
#else
	#error Slot 7 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/VSMShadowResolveIO.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_VSMShadowResolveIO { uint offset; };
static _CB_VSMShadowResolveIO pass_VSMShadowResolveIO = { _hal_push.s7 };
#else
ConstantBuffer<CB> pass_VSMShadowResolveIO: register(b7, space7);
#endif
ConstantBuffer<VSMShadowResolveIO> CreateVSMShadowResolveIO()
{
	return ResourceDescriptorHeap[pass_VSMShadowResolveIO.offset];
}

#ifndef NO_GLOBAL
static const ConstantBuffer<VSMShadowResolveIO> vSMShadowResolveIO_global = CreateVSMShadowResolveIO();
ConstantBuffer<VSMShadowResolveIO> GetVSMShadowResolveIO() { return vSMShadowResolveIO_global; }
#endif