// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#ifndef SLOT_12
	#define SLOT_12
#else
	#error Slot 12 is already used
#endif

#include "layout/DefaultLayout.h"
#include "tables/WorkGREmulation.h"

#ifndef CB_DEFINED
#define CB_DEFINED
struct CB { uint offset; };
#endif

#ifdef __spirv__
struct _CB_WorkGREmulation { uint offset; };
static _CB_WorkGREmulation pass_WorkGREmulation = { _hal_push.s12 };
#else
ConstantBuffer<CB> pass_WorkGREmulation: register(b12, space12);
#endif

ConstantBuffer<WorkGREmulation> CreateWorkGREmulation()
{
	return ResourceDescriptorHeap[pass_WorkGREmulation.offset];
}
			
#ifndef NO_GLOBAL
static const ConstantBuffer<WorkGREmulation> workGREmulation_global = CreateWorkGREmulation();
ConstantBuffer<WorkGREmulation> GetWorkGREmulation(){ return workGREmulation_global; }
#endif