// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.Raytrace.ColorRTXOutput;
import Core;
import :Autogen.Tables.Raytrace.ColorRTXOutput;
import :Autogen.Layouts.Frame.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace Raytrace
	{
		struct ColorRTXOutput :public DataHolder<ColorRTXOutput, SlotID::ColorRTXOutput, Table::Raytrace::ColorRTXOutput, ::Frame::DefaultLayout::Instance3>
		{
			static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
			ColorRTXOutput() = default;
		};
	}
}