import Core;
import jinja2cpp;
import cereal.json;


#include "Parsed.h"
#include "Parsing.h"

static const std::string cpp_path = "../../sources/HAL/autogen";
static const std::string hlsl_path = "../../workdir/shaders/autogen";


static const std::string cpp_path_render = "../../sources/RenderSystem/FrameGraph/autogen";


using namespace jinja2;

void iterate_files(std::filesystem::path path, std::function<void(std::filesystem::path)> f)
{
	using namespace std::filesystem;

	recursive_directory_iterator dir(path), end;

	while (dir != end)
	{
		// do other stuff here.
		if (!is_directory(*dir))
			f(dir->path());

		++dir;
	}
}

jinja2::TemplateEnv global;

rapidjson::Document make_map(auto& p)
{
	std::stringstream s;
	{
		cereal::JSONOutputArchive archive(s);

		p.serialize(archive);
	}
	rapidjson::Document doc;

	auto str = s.str();
	doc.Parse(str.c_str());

	return doc;
}

class TemplatesLibrary
{
	std::map<std::wstring, jinja2::Template> templates;

public:
	TemplatesLibrary(std::string dir)
	{
		iterate_files("templates/" + dir + "/", [this](std::filesystem::path path)
		{
			std::ifstream stream;
			stream.open(path);

			if (!stream.is_open())
				return;


			auto& tpl = templates[path.stem()];
			tpl = jinja2::Template(&global);
			tpl.Load(stream);

			stream.close();
		});
	}

	auto generate(std::wstring filename, const ValuesMap& params)
	{
		jinja2::Template& tpl = templates[filename];
		auto res = tpl.RenderAsString(params);

		if (res.has_value())
			return res.value();

		std::cout << res.error().ToString() << std::endl;
	}

	auto generate(std::wstring filename)
	{
		return generate(filename, ValuesMap{});
	}

	auto generate2(std::wstring filename, std::string name, auto& p)
	{
		auto dp = make_map(p);

		ValuesMap params = {
			{name, Reflect(dp)}
		};

		return generate(filename, params);
	}
};


int main()
{
	std::map<std::string, ValuesList> user_lists;

	try
	{
		Parsed parsed;

		iterate_files("sigs/", [&](std::wstring filename)
		{
			auto p = parse(filename);

			// Stamp every top-level named item with its source .sig path so
			// templates can emit an autogenerated-from comment in the output.
			std::string sig_path = "sources/SIGParser/"
			    + std::filesystem::path(filename).generic_string();
			auto tag = [&](auto& container)
			{
				for (auto& item : container)
					item.source_file = sig_path;
			};
			tag(p.tables);
			tag(p.layouts);
			tag(p.compute_pso);
			tag(p.graphics_pso);
			tag(p.workgraph_pso);
			tag(p.raytrace_pso);
			tag(p.rt);
			tag(p.views);
			tag(p.passes);

			parsed.merge(p);
		});

		parsed.setup();
		rapidjson::Document parsed_doc = make_map(parsed);

		jinja2::Value parsed_map = Reflect(parsed_doc);
		global.AddGlobal("parsed", parsed_map);
		global.AddGlobal("ValueType", ValuesMap{
			                 {"CB", ValueType::CB}, {"SRV", ValueType::SRV}, {"UAV", ValueType::UAV},
			                 {"SMP", ValueType::SMP}, {"STRUCT", ValueType::STRUCT}
		                 });

		global.AddGlobal("recursive_slots", jinja2::MakeCallable(
			                 [&](const std::string& name)
			                 {
				                 auto* layout = parsed.find_layout(name);
				                 ValuesList list;
				                 layout->recursive_slots([&](Slot& slot)
				                 {
					                 list.emplace_back(slot.name);
				                 });


				                 return list;
			                 },
			                 ArgInfo{"name"}
		                 ));

		global.AddGlobal("recursive_samplers", jinja2::MakeCallable(
			                 [&](const std::string& name)
			                 {
				                 auto* layout = parsed.find_layout(name);
				                 ValuesList list;


				                 layout->recursive_samplers([&](Sampler& slot)
				                 {
					                 list.emplace_back("HAL::Samplers::" + slot.expr);
				                 });


				                 return list;
			                 },
			                 ArgInfo{"name"}
		                 ));

		global.AddGlobal("get_name_for", jinja2::MakeCallable(
			                 [&](const int& i)
			                 {
				                 return get_name_for((ValueType)i);
			                 },
			                 ArgInfo{"i"}
		                 ));

		global.AddGlobal("create_list", jinja2::MakeCallable(
			                 [&](const std::string& b)
			                 {
				                 auto& list = user_lists[b];
				                 list.clear();
				                 //	 a.asList().emplace_back(b);
				                 return list;
			                 },
			                 ArgInfo{"b"}
		                 ));

		global.AddGlobal("get_list", jinja2::MakeCallable(
			                 [&](const std::string& b)
			                 {
				                 auto& list = user_lists[b];

				                 return list;
			                 },
			                 ArgInfo{"b"}
		                 ));

		// Is this pipeline entry tagged [Async]? Placement is a per-pipeline
		// decision, so it lives on the entry rather than the PassNode. Resolved in
		// C++ because the template's view of an entry does not expose its options.
		global.AddGlobal("entry_is_async", jinja2::MakeCallable(
			                 [&](const std::string& pipeline_name, const std::string& entry_name)
			                 {
				                 Pipeline* pipeline_ptr = parsed.pipelines.find(pipeline_name);
				                 if (!pipeline_ptr) return false;

				                 const PipelineEntry* entry = pipeline_ptr->entries.find(entry_name);
				                 return entry && entry->find_option("Async") != nullptr;
			                 },
			                 ArgInfo{"pipeline"}, ArgInfo{"entry"}
		                 ));

		// [Async2] / [Async3] pick an additional compute queue for this entry.
		// Both imply [Async]: the pass still needs PassFlags::Compute to leave
		// the direct queue at all.
		auto entry_has = [&](const std::string& pipeline_name, const std::string& entry_name, const char* opt)
		{
			Pipeline* pipeline_ptr = parsed.pipelines.find(pipeline_name);
			if (!pipeline_ptr) return false;

			const PipelineEntry* entry = pipeline_ptr->entries.find(entry_name);
			return entry && entry->find_option(opt) != nullptr;
		};

		global.AddGlobal("entry_is_async2", jinja2::MakeCallable(
			                 [entry_has](const std::string& pipeline_name, const std::string& entry_name)
			                 {
				                 return entry_has(pipeline_name, entry_name, "Async2");
			                 },
			                 ArgInfo{"pipeline"}, ArgInfo{"entry"}
		                 ));

		global.AddGlobal("entry_is_async3", jinja2::MakeCallable(
			                 [entry_has](const std::string& pipeline_name, const std::string& entry_name)
			                 {
				                 return entry_has(pipeline_name, entry_name, "Async3");
			                 },
			                 ArgInfo{"pipeline"}, ArgInfo{"entry"}
		                 ));

		global.AddGlobal("myappend", jinja2::MakeCallable(
			                 [&](const std::string& list_name, const std::string& b)
			                 {
				                 auto& list = user_lists[list_name];

				                 list.emplace_back(b);

				                 return list;
			                 },
			                 ArgInfo{"a"}, ArgInfo{"b"}
		                 ));

		global.AddGlobal("merge_lists", jinja2::MakeCallable(
			                 [](const GenericList& a, const GenericList& b)
			                 {
				                 ValuesList list;
				                 for (const auto& e : a)
					                 list.emplace_back(e);

				                 for (const auto& e : b)
					                 list.emplace_back(e);

				                 return list;
			                 },
			                 ArgInfo{"a"}, ArgInfo{"b"}
		                 ));
							  global.AddGlobal("merge_lists3", jinja2::MakeCallable(
			                 [](const GenericList& a, const GenericList& b, const GenericList& c)
			                 {
				                 ValuesList list;
				                 for (const auto& e : a)
					                 list.emplace_back(e);

				                 for (const auto& e : b)
					                 list.emplace_back(e);
								      for (const auto& e : c)
					                 list.emplace_back(e);

				                 return list;
			                 },
			                 ArgInfo{"a"}, ArgInfo{"b"}		   , ArgInfo{"c"}
		                 ));
		global.AddGlobal("lowerize", jinja2::MakeCallable(
			                 [](const std::string& name)
			                 {
				                 std::string lowcameled = name;
				                 lowcameled[0] = std::tolower(lowcameled[0]);
				                 return lowcameled;
			                 },
			                 ArgInfo{"name"}
		                 ));

		global.AddGlobal("camel", jinja2::MakeCallable(
			                 [](const std::string& name)
			                 {
				                 std::string lowcameled = name;
				                 lowcameled[0] = std::toupper(lowcameled[0]);
				                 return lowcameled;
			                 },
			                 ArgInfo{"name"}
		                 ));


		global.AddGlobal("replace_start", jinja2::MakeCallable(
			                 [](const std::string& a, const std::string& b, const std::string& c)
			                 {
				                 std::string res = a;

				                 if (res.starts_with(b))
					                 res.replace(0, b.size(), c);

				                 return res;
			                 },
			                 ArgInfo{"a"}, ArgInfo{"b"}, ArgInfo{"c"}
		                 ));



		global.AddGlobal("get_offset", jinja2::MakeCallable(
			                 [&](const GenericList& offsets, const int& i)
			                 {
				                 return offsets.GetAccessor()->GetIndexer()->GetItemByIndex(i);
			                 },
			                
			                 ArgInfo{"offsets"}, ArgInfo{"i"}
		                 ));
		global.AddGlobal("get_all_resources", jinja2::MakeCallable(
			[&]() -> ValuesList
			{
				std::set<std::string> seen;
				ValuesList result;

				std::function<void(const std::list<View_Param>&)> collect;
				collect = [&](const std::list<View_Param>& params)
				{
					for (const auto& p : params)
					{
						View* view = parsed.views.find(p.class_no_template);
						if (view)
							collect(view->params);
						else
						{
							if (seen.insert(p.name).second)
								result.emplace_back(p.name);
						}
					}
				};

				for (const auto& pass : parsed.passes)
					collect(pass.params);

				return result;
			}
		));

		// Shared source of truth for a pass's ordered (resource_id, write)
		// accesses. A leaf's write-ness comes from: its own [Write] if declared
		// directly, or the enclosing view usage's [Write] / [Write = {leaves...}]
		// if it's inside a view group. A recreate adds a trailing write on the
		// same id.
		auto compute_pass_accesses = [&](Pass* pass, std::vector<std::pair<std::string, bool>>& out)
		{
			std::function<void(const std::list<View_Param>&, bool, const std::function<bool(const std::string&)>&)> rec;
			rec = [&](const std::list<View_Param>& params, bool inside_view, const std::function<bool(const std::string&)>& parent_is_write)
			{
				for (const auto& p : params)
				{
					View* view = parsed.views.find(p.class_no_template);
					if (view)
					{
						// Build the write predicate for this view usage from its
						// [Write] option: a list -> membership; bare [Write] ->
						// whole view; absent -> nothing.
						const option* w = p.find_option("Write");
						std::function<bool(const std::string&)> pred;
						if (!w)
						{
							pred = [](const std::string&) { return false; };
						}
						else
						{
							std::set<std::string> s;
							if (!w->value_atom.values.empty())
								for (const auto& v : w->value_atom.values) s.insert(v.expr);
							else if (!w->value_atom.expr.empty())
								s.insert(w->value_atom.expr);

							if (s.empty()) pred = [](const std::string&) { return true; };
							else            pred = [s](const std::string& n) { return s.count(n) > 0; };
						}
						rec(view->params, true, pred);
					}
					else
					{
						bool write = inside_view ? parent_is_write(p.name)
						                         : (p.find_option("Write") != nullptr);
						out.emplace_back(p.name, write);
						if (p.find_option("Recreate"))
							out.emplace_back(p.name, true);
					}
				}
			};
			rec(pass->params, false, {});
		};

		global.AddGlobal("get_pass_accesses", jinja2::MakeCallable(
			[&, compute_pass_accesses](const std::string& pass_name) -> ValuesList
			{
				ValuesList result;
				Pass* pass = parsed.passes.find(pass_name);
				if (!pass) return result;

				std::vector<std::pair<std::string, bool>> acc;
				compute_pass_accesses(pass, acc);
				for (const auto& [id, write] : acc)
				{
					ValuesMap m;
					m["id"] = id;
					m["write"] = write;
					result.push_back(std::move(m));
				}
				return result;
			},
			ArgInfo{"pass_name"}
		));

		global.AddGlobal("get_pipeline_resources", jinja2::MakeCallable(
			[&](const std::string& pipeline_name) -> ValuesList
			{
				Pipeline* pipeline_ptr = parsed.pipelines.find(pipeline_name);
				if (!pipeline_ptr) return {};

				std::set<std::string> seen;
				ValuesList result;

				std::function<void(const std::list<View_Param>&)> collect;
				collect = [&](const std::list<View_Param>& params)
				{
					for (const auto& p : params)
					{
						View* view = parsed.views.find(p.class_no_template);
						if (view)
						{
							collect(view->params);
						}
						else
						{
							if (seen.insert(p.name).second)
								result.emplace_back(p.name);

							const option* recreate = p.find_option("Recreate");
							if (recreate)
							{
								if (seen.insert(recreate->value_atom.expr).second)
									result.emplace_back(recreate->value_atom.expr);
							}
						}
					}
				};

				for (const auto& entry : pipeline_ptr->entries)
				{
					Pass* pass = parsed.passes.find(entry.name);
					if (pass)
						collect(pass->params);
				}

				return result;
			},
			ArgInfo{"pipeline_name"}
		));

		// Precomputes each pipeline's per-resource RW-state timeline (mirroring the
		// runtime add_pass grouping). Returns:
		//   { "resources": [ {id, states:[{write,begin,count}]}... ],
		//     "passes":    [ {pass, index}... ] }         // referenced by begin/count
		// where each pass ref is a PassID name + [Multiple] instance index.
		global.AddGlobal("get_pipeline_states", jinja2::MakeCallable(
			[&, compute_pass_accesses](const std::string& pipeline_name) -> ValuesMap
			{
				ValuesMap out;
				out["resources"] = ValuesList{};

				Pipeline* pipeline_ptr = parsed.pipelines.find(pipeline_name);
				if (!pipeline_ptr) return out;

				// A single pass touch: which pass (name + Multiple instance) and
				// whether it writes.
				struct Touch { std::string pass; uint32_t index; bool write; };

				// Per resource version (id + chain_index), ordered touches. A
				// recreate() starts a new chain version: within one pass instance,
				// the 2nd+ access to the same id is the recreate, and it plus every
				// later touch go to the new version. Separate first-seen order
				// keeps output deterministic.
				using Key = std::pair<std::string, uint32_t>;   // (id, chain_index)
				std::map<Key, std::vector<Touch>> touches;
				std::vector<Key>                  resource_order;
				std::map<std::string, uint32_t>   version;       // current chain version per id

				for (const auto& entry : pipeline_ptr->entries)
				{
					Pass* pass = parsed.passes.find(entry.name);
					if (!pass) continue;

					uint32_t count = 1;
					if (const option* m = pass->find_option("Multiple"))
						count = (uint32_t)std::max(1, atoi(m->value_atom.expr.c_str()));

					std::vector<std::pair<std::string, bool>> accesses;
					compute_pass_accesses(pass, accesses);

					for (uint32_t inst = 0; inst < count; ++inst)
					{
						std::set<std::string> seen_in_pass;
						for (const auto& [id, write] : accesses)
						{
							if (!seen_in_pass.insert(id).second)
								++version[id];              // recreate -> next chain version

							Key key{ id, version[id] };
							auto it = touches.find(key);
							if (it == touches.end())
							{
								resource_order.push_back(key);
								it = touches.emplace(key, std::vector<Touch>{}).first;
							}
							it->second.push_back({ entry.name, inst, write });
						}
					}
				}

				// Group touches into states (new state on write, first touch, or
				// read-after-write). Each resource version owns its own states and
				// pass refs; state begin/count are offsets into that version's refs.
				ValuesList resources;
				for (const auto& key : resource_order)
				{
					const auto& id = key.first;
					const auto& ts = touches[key];

					ValuesList states;
					ValuesList pass_refs;
					bool have_state = false;
					bool cur_write = false;
					uint32_t begin = 0;
					uint32_t cnt = 0;

					auto flush = [&]()
					{
						if (!have_state) return;
						ValuesMap s;
						s["write"] = cur_write;
						s["begin"] = (int64_t)begin;
						s["count"] = (int64_t)cnt;
						states.push_back(std::move(s));
					};

					for (const auto& t : ts)
					{
						bool need_new = !have_state || t.write || cur_write;
						if (need_new)
						{
							flush();
							have_state = true;
							cur_write = t.write;
							begin = (uint32_t)pass_refs.size();
							cnt = 0;
						}
						ValuesMap pr;
						pr["pass"] = t.pass;
						pr["index"] = (int64_t)t.index;
						pass_refs.push_back(std::move(pr));
						++cnt;
					}
					flush();

					ValuesMap r;
					r["pass_refs"] = std::move(pass_refs);
					r["id"] = id;
					r["chain_index"] = (int64_t)key.second;
					r["states"] = std::move(states);
					resources.push_back(std::move(r));
				}

				out["resources"] = std::move(resources);
				return out;
			},
			ArgInfo{"pipeline_name"}
		));

		// Precomputes each pipeline's pass instances with queue type and prev-pass
		// dependency edges (the codegen equivalent of resolve_dependencies, run
		// over the same per-resource state timelines). Returns a list of
		//   { pass, index, compute, prev:[{pass,index}...] }
		// in pipeline order.
		global.AddGlobal("get_pipeline_passes", jinja2::MakeCallable(
			[&, compute_pass_accesses](const std::string& pipeline_name) -> ValuesList
			{
				ValuesList result;
				Pipeline* pipeline_ptr = parsed.pipelines.find(pipeline_name);
				if (!pipeline_ptr) return result;

				using Ref = std::pair<std::string, uint32_t>;   // (pass name, instance)
				struct Touch { Ref ref; bool write; };

				std::vector<std::pair<Ref, bool>>       order;    // (ref, compute) in pipeline order
				std::map<std::string, std::vector<Touch>> touches; // per resource, ordered
				std::vector<std::string>                resource_order;

				for (const auto& entry : pipeline_ptr->entries)
				{
					Pass* pass = parsed.passes.find(entry.name);
					if (!pass) continue;

					uint32_t count = 1;
					if (const option* m = pass->find_option("Multiple"))
						count = (uint32_t)std::max(1, atoi(m->value_atom.expr.c_str()));
					// [Compute] on the PassNode says the pass CAN run on the compute
					// queue; [Async] on this pipeline entry says it SHOULD. Async is
					// opt-in: a compute pass with no [Async] runs inline on the direct
					// queue, which costs nothing extra and avoids a fence pair for work
					// that has nothing to overlap with.
					bool compute = pass->find_option("Compute") != nullptr
					            && (entry.find_option("Async") != nullptr
					             || entry.find_option("Async2") != nullptr
					             || entry.find_option("Async3") != nullptr);

					std::vector<std::pair<std::string, bool>> accesses;
					compute_pass_accesses(pass, accesses);

					for (uint32_t inst = 0; inst < count; ++inst)
					{
						Ref ref{ entry.name, inst };
						order.emplace_back(ref, compute);
						for (const auto& [id, write] : accesses)
						{
							auto it = touches.find(id);
							if (it == touches.end())
							{
								resource_order.push_back(id);
								it = touches.emplace(id, std::vector<Touch>{}).first;
							}
							it->second.push_back({ ref, write });
						}
					}
				}

				// prev-pass edges: for each resource, walk its states accumulating
				// 'related' (passes of prior states); each pass in the current
				// state depends on all of related. Aggregate across resources.
				std::map<Ref, std::set<Ref>> deps;
				for (const auto& id : resource_order)
				{
					const auto& ts = touches[id];
					std::set<Ref>         related;
					std::vector<Ref>      cur;      // current state's passes
					bool have = false, cur_write = false;

					auto flush = [&]() { for (const auto& r : cur) related.insert(r); cur.clear(); };

					for (const auto& t : ts)
					{
						bool need_new = !have || t.write || cur_write;
						if (need_new) { flush(); have = true; cur_write = t.write; }
						for (const auto& r : related)
							if (r != t.ref) deps[t.ref].insert(r);
						cur.push_back(t.ref);
					}
				}

				for (const auto& [ref, compute] : order)
				{
					ValuesMap m;
					m["pass"] = ref.first;
					m["index"] = (int64_t)ref.second;
					m["compute"] = compute;

					ValuesList prev;
					auto it = deps.find(ref);
					if (it != deps.end())
						for (const auto& r : it->second)   // std::set -> deterministic order
						{
							ValuesMap pr;
							pr["pass"] = r.first;
							pr["index"] = (int64_t)r.second;
							prev.push_back(std::move(pr));
						}
					m["prev"] = std::move(prev);
					result.push_back(std::move(m));
				}
				return result;
			},
			ArgInfo{"pipeline_name"}
		));

		global.GetSettings().extensions.Do = true;


		TemplatesLibrary cpp_templates("cpp");
		TemplatesLibrary hlsl_templates("hlsl");

		// Tables
		for (auto& table : parsed.tables)
		{
			if (table.find_option("nobind"))
				my_stream(hlsl_path + "/tables", table.name + ".h") << hlsl_templates.generate2(
					L"nobind_table", "table", table);
			else
			{
				my_stream(hlsl_path + "/tables", table.name + ".h") << hlsl_templates.generate2(
					L"table", "table", table);

				if (table.slot)
				{
					my_stream(hlsl_path, table.name + ".h") << hlsl_templates.generate2(L"slot", "table", table);
				}
			}

			if (!table.find_option("shader_only"))
			{
				my_stream(cpp_path + "/tables", table.name + ".table.ixx") << cpp_templates.generate2(
					L"table", "table", table);

				if (table.slot)
				{
					my_stream(cpp_path + "/slots", table.name + ".ixx") << cpp_templates.generate2(
						L"slot", "table", table);
				}
			}

			if (table.find_option("RenderTarget"))
			{
				my_stream(hlsl_path + "/rt", table.name + ".h") << hlsl_templates.generate2(L"rt", "rt", table);
				my_stream(cpp_path + "/rt", table.name + ".rt.ixx") << cpp_templates.generate2(L"rt", "rt", table);
				std::filesystem::remove(cpp_path + "/rt/" + table.name + ".h");
				std::filesystem::remove(cpp_path + "/rt/" + table.name + ".ixx");
			}
		}

		// Layout
		for (auto& layout : parsed.layouts)
		{
			my_stream(hlsl_path + "/layout", layout.name + ".h") << hlsl_templates.generate2(
				L"layout", "layout", layout);
			my_stream(cpp_path + "/layout", layout.name + ".layout.ixx") << cpp_templates.generate2(
				L"layout", "layout", layout);
		}

		// PSO
		auto remove_old_pso_h = [&](const std::string& name)
		{
			std::filesystem::remove(cpp_path + "/pso/" + name + ".h");
			std::filesystem::remove(cpp_path + "/pso/" + name + ".ixx");
		};

		for (auto& pso : parsed.compute_pso)
		{
			my_stream(cpp_path + "/pso", pso.name + ".pso.ixx") << cpp_templates.generate2(L"pso", "pso", pso);
			remove_old_pso_h(pso.name);
		}

		for (auto& pso : parsed.graphics_pso)
		{
			my_stream(cpp_path + "/pso", pso.name + ".pso.ixx") << cpp_templates.generate2(L"pso", "pso", pso);
			remove_old_pso_h(pso.name);
		}

		for (auto& pso : parsed.workgraph_pso)
		{
			my_stream(cpp_path + "/pso", pso.name + ".pso.ixx") << cpp_templates.generate2(L"pso", "pso", pso);
			remove_old_pso_h(pso.name);
			my_stream(hlsl_path + "/workgraph", pso.name + ".h") << hlsl_templates.generate2(L"workgraph_nodes", "pso", pso);

			for (auto& node : pso.nodes)
			{
				auto dp = make_map(pso);
				auto dn = make_map(node);
				ValuesMap params = {
					{"pso", Reflect(dp)},
					{"node", Reflect(dn)},
				};
				my_stream(cpp_path + "/pso", pso.name + "_" + node.name + ".pso.ixx") << cpp_templates.generate(L"workgraph_node_pso", params);
			}
		}

		// RTX
		for (auto& pso : parsed.raytrace_gen)
		{
			auto bind = pso.find_option("Bind");
			parsed.find_rtx(bind->value_atom.expr)->gens.emplace_back(pso);

			my_stream(cpp_path + "/rtx", pso.name + ".h") << cpp_templates.generate2(L"raygen_pass", "pso", pso);
		}

		for (auto& pso : parsed.raytrace_pass)
		{
			auto bind = pso.find_option("Bind");
			parsed.find_rtx(bind->value_atom.expr)->passes.emplace_back(pso);


			my_stream(cpp_path + "/rtx", pso.name + ".h") << cpp_templates.generate2(L"raytrace_pass", "pso", pso);
			my_stream(hlsl_path + "/rtx", pso.name + ".h") << hlsl_templates.generate2(L"pass", "pso", pso);
		}

		for (auto& pso : parsed.raytrace_pso)
		{
			// collect unique payload tables and local slots needed by this PSO's passes
			ValuesList payload_tables, local_slots;
			std::set<std::string> seen_payload, seen_local;
			for (auto& pass : pso.passes)
			{
				auto* payload = pass.find_param("payload");
				if (payload && seen_payload.insert(payload->expr).second)
					payload_tables.emplace_back(payload->expr);

				auto* local = pass.find_param("local");
				if (local && seen_local.insert(local->expr).second)
					local_slots.emplace_back(local->expr);
			}

			auto dp = make_map(pso);
			ValuesMap params = {
				{ "pso",            Reflect(dp)     },
				{ "payload_tables", payload_tables  },
				{ "local_slots",    local_slots     },
			};

			my_stream(cpp_path + "/rtx", pso.name + ".rtx.ixx") << cpp_templates.generate(L"rtx_pso", params);
			std::filesystem::remove(cpp_path + "/rtx/" + pso.name + ".h");
			std::filesystem::remove(cpp_path + "/rtx/" + pso.name + ".ixx");
		}


		for (auto& pass : parsed.passes)
		{
			my_stream(cpp_path_render + "/pass", pass.name + ".h") << cpp_templates.generate2(L"pass", "pass", pass);
		}
		for (auto& view : parsed.views)
		{
			my_stream(cpp_path_render + "/pass", view.name + ".h") << cpp_templates.generate2(L"pass_view", "view", view);
		}
		for (auto& pipeline : parsed.pipelines)
		{
			my_stream(cpp_path_render + "/pass", pipeline.name + ".pipeline.h") << cpp_templates.generate2(L"pipeline", "pipeline", pipeline);
		}

		my_stream(cpp_path_render, "pass_defaults.h") << cpp_templates.generate(L"pass_defaults");
		my_stream(cpp_path_render, "resource_ids.h") << cpp_templates.generate(L"resource_ids");
		my_stream(cpp_path_render, "pass_ids.h") << cpp_templates.generate(L"pass_ids");

		// includes
		my_stream(cpp_path, "autogen.ixx") << cpp_templates.generate(L"autogen");
		my_stream(cpp_path, "autogen.cpp") << cpp_templates.generate(L"autogen_impl");
		my_stream(cpp_path, "enums.ixx") << cpp_templates.generate(L"enums");
		my_stream(cpp_path, "pso.cpp") << cpp_templates.generate(L"psos");

		my_stream(cpp_path_render, "enums.h") << cpp_templates.generate(L"pass_enums");
		my_stream(cpp_path_render, "passes.ixx") << cpp_templates.generate(L"passes");
	}
	catch (std::exception& e)
	{
		std::cout << "Error: " << e.what() << std::endl;
	}

	return 0;
}
