import Core;
import jinja2cpp;
import cereal.json;


#include "Parsed.h"
#include "Parsing.h"

static const std::string cpp_path = "../../sources/HAL/autogen";
static const std::string hlsl_path = "../../workdir/shaders/autogen";


static const std::string cpp_path_render = "../../sources/RenderSystem/FrameGraph/autogen";


using namespace jinja2;

void iterate_files(std::filesystem::path path, std::function<void(std::filesystem::path)> f)
{
	using namespace std::filesystem;

	recursive_directory_iterator dir(path), end;

	while (dir != end)
	{
		// do other stuff here.
		if (!is_directory(*dir))
			f(dir->path());

		++dir;
	}
}

jinja2::TemplateEnv global;

rapidjson::Document make_map(auto& p)
{
	std::stringstream s;
	{
		cereal::JSONOutputArchive archive(s);

		p.serialize(archive);
	}
	rapidjson::Document doc;

	auto str = s.str();
	doc.Parse(str.c_str());

	return doc;
}

class TemplatesLibrary
{
	std::map<std::wstring, jinja2::Template> templates;

public:
	TemplatesLibrary(std::string dir)
	{
		iterate_files("templates/" + dir + "/", [this](std::filesystem::path path)
		{
			std::ifstream stream;
			stream.open(path);

			if (!stream.is_open())
				return;


			auto& tpl = templates[path.stem()];
			tpl = jinja2::Template(&global);
			tpl.Load(stream);

			stream.close();
		});
	}

	auto generate(std::wstring filename, const ValuesMap& params)
	{
		jinja2::Template& tpl = templates[filename];
		auto res = tpl.RenderAsString(params);

		if (res.has_value())
			return res.value();

		std::cout << res.error().ToString() << std::endl;
	}

	auto generate(std::wstring filename)
	{
		return generate(filename, ValuesMap{});
	}

	auto generate2(std::wstring filename, std::string name, auto& p)
	{
		auto dp = make_map(p);

		ValuesMap params = {
			{name, Reflect(dp)}
		};

		return generate(filename, params);
	}
};


int main()
{
	std::map<std::string, ValuesList> user_lists;

	try
	{
		Parsed parsed;

		iterate_files("sigs/", [&](std::wstring filename)
		{
			auto p = parse(filename);

			// Stamp every top-level named item with its source .sig path so
			// templates can emit an autogenerated-from comment in the output.
			std::string sig_path = "sources/SIGParser/"
			    + std::filesystem::path(filename).generic_string();
			auto tag = [&](auto& container)
			{
				for (auto& item : container)
					item.source_file = sig_path;
			};
			tag(p.tables);
			tag(p.layouts);
			tag(p.compute_pso);
			tag(p.graphics_pso);
			tag(p.workgraph_pso);
			tag(p.raytrace_pso);
			tag(p.rt);
			tag(p.views);
			tag(p.passes);

			parsed.merge(p);
		});

		parsed.setup();
		rapidjson::Document parsed_doc = make_map(parsed);

		jinja2::Value parsed_map = Reflect(parsed_doc);
		global.AddGlobal("parsed", parsed_map);
		global.AddGlobal("ValueType", ValuesMap{
			                 {"CB", ValueType::CB}, {"SRV", ValueType::SRV}, {"UAV", ValueType::UAV},
			                 {"SMP", ValueType::SMP}, {"STRUCT", ValueType::STRUCT}
		                 });

		global.AddGlobal("recursive_slots", jinja2::MakeCallable(
			                 [&](const std::string& name)
			                 {
				                 auto* layout = parsed.find_layout(name);
				                 ValuesList list;
				                 layout->recursive_slots([&](Slot& slot)
				                 {
					                 list.emplace_back(slot.name);
				                 });


				                 return list;
			                 },
			                 ArgInfo{"name"}
		                 ));

		global.AddGlobal("recursive_samplers", jinja2::MakeCallable(
			                 [&](const std::string& name)
			                 {
				                 auto* layout = parsed.find_layout(name);
				                 ValuesList list;


				                 layout->recursive_samplers([&](Sampler& slot)
				                 {
					                 list.emplace_back("HAL::Samplers::" + slot.expr);
				                 });


				                 return list;
			                 },
			                 ArgInfo{"name"}
		                 ));

		global.AddGlobal("get_name_for", jinja2::MakeCallable(
			                 [&](const int& i)
			                 {
				                 return get_name_for((ValueType)i);
			                 },
			                 ArgInfo{"i"}
		                 ));

		global.AddGlobal("create_list", jinja2::MakeCallable(
			                 [&](const std::string& b)
			                 {
				                 auto& list = user_lists[b];
				                 list.clear();
				                 //	 a.asList().emplace_back(b);
				                 return list;
			                 },
			                 ArgInfo{"b"}
		                 ));

		global.AddGlobal("get_list", jinja2::MakeCallable(
			                 [&](const std::string& b)
			                 {
				                 auto& list = user_lists[b];

				                 return list;
			                 },
			                 ArgInfo{"b"}
		                 ));

		global.AddGlobal("myappend", jinja2::MakeCallable(
			                 [&](const std::string& list_name, const std::string& b)
			                 {
				                 auto& list = user_lists[list_name];

				                 list.emplace_back(b);

				                 return list;
			                 },
			                 ArgInfo{"a"}, ArgInfo{"b"}
		                 ));

		global.AddGlobal("merge_lists", jinja2::MakeCallable(
			                 [](const GenericList& a, const GenericList& b)
			                 {
				                 ValuesList list;
				                 for (const auto& e : a)
					                 list.emplace_back(e);

				                 for (const auto& e : b)
					                 list.emplace_back(e);

				                 return list;
			                 },
			                 ArgInfo{"a"}, ArgInfo{"b"}
		                 ));
							  global.AddGlobal("merge_lists3", jinja2::MakeCallable(
			                 [](const GenericList& a, const GenericList& b, const GenericList& c)
			                 {
				                 ValuesList list;
				                 for (const auto& e : a)
					                 list.emplace_back(e);

				                 for (const auto& e : b)
					                 list.emplace_back(e);
								      for (const auto& e : c)
					                 list.emplace_back(e);

				                 return list;
			                 },
			                 ArgInfo{"a"}, ArgInfo{"b"}		   , ArgInfo{"c"}
		                 ));
		global.AddGlobal("lowerize", jinja2::MakeCallable(
			                 [](const std::string& name)
			                 {
				                 std::string lowcameled = name;
				                 lowcameled[0] = std::tolower(lowcameled[0]);
				                 return lowcameled;
			                 },
			                 ArgInfo{"name"}
		                 ));

		global.AddGlobal("camel", jinja2::MakeCallable(
			                 [](const std::string& name)
			                 {
				                 std::string lowcameled = name;
				                 lowcameled[0] = std::toupper(lowcameled[0]);
				                 return lowcameled;
			                 },
			                 ArgInfo{"name"}
		                 ));


		global.AddGlobal("replace_start", jinja2::MakeCallable(
			                 [](const std::string& a, const std::string& b, const std::string& c)
			                 {
				                 std::string res = a;

				                 if (res.starts_with(b))
					                 res.replace(0, b.size(), c);

				                 return res;
			                 },
			                 ArgInfo{"a"}, ArgInfo{"b"}, ArgInfo{"c"}
		                 ));



		global.AddGlobal("get_offset", jinja2::MakeCallable(
			                 [&](const GenericList& offsets, const int& i)
			                 {
				                 return offsets.GetAccessor()->GetIndexer()->GetItemByIndex(i);
			                 },
			                
			                 ArgInfo{"offsets"}, ArgInfo{"i"}
		                 ));
		global.AddGlobal("get_all_resources", jinja2::MakeCallable(
			[&]() -> ValuesList
			{
				std::set<std::string> seen;
				ValuesList result;

				std::function<void(const std::list<View_Param>&)> collect;
				collect = [&](const std::list<View_Param>& params)
				{
					for (const auto& p : params)
					{
						View* view = parsed.views.find(p.class_no_template);
						if (view)
							collect(view->params);
						else
						{
							if (seen.insert(p.name).second)
								result.emplace_back(p.name);
						}
					}
				};

				for (const auto& pass : parsed.passes)
					collect(pass.params);

				return result;
			}
		));

		global.AddGlobal("get_pipeline_resources", jinja2::MakeCallable(
			[&](const std::string& pipeline_name) -> ValuesList
			{
				Pipeline* pipeline_ptr = parsed.pipelines.find(pipeline_name);
				if (!pipeline_ptr) return {};

				std::set<std::string> seen;
				ValuesList result;

				std::function<void(const std::list<View_Param>&)> collect;
				collect = [&](const std::list<View_Param>& params)
				{
					for (const auto& p : params)
					{
						View* view = parsed.views.find(p.class_no_template);
						if (view)
						{
							collect(view->params);
						}
						else
						{
							if (seen.insert(p.name).second)
								result.emplace_back(p.name);

							const option* recreate = p.find_option("Recreate");
							if (recreate)
							{
								if (seen.insert(recreate->value_atom.expr).second)
									result.emplace_back(recreate->value_atom.expr);
							}
						}
					}
				};

				for (const auto& entry : pipeline_ptr->entries)
				{
					Pass* pass = parsed.passes.find(entry.name);
					if (pass)
						collect(pass->params);
				}

				return result;
			},
			ArgInfo{"pipeline_name"}
		));

		global.GetSettings().extensions.Do = true;


		TemplatesLibrary cpp_templates("cpp");
		TemplatesLibrary hlsl_templates("hlsl");

		// Tables
		for (auto& table : parsed.tables)
		{
			if (table.find_option("nobind"))
				my_stream(hlsl_path + "/tables", table.name + ".h") << hlsl_templates.generate2(
					L"nobind_table", "table", table);
			else
			{
				my_stream(hlsl_path + "/tables", table.name + ".h") << hlsl_templates.generate2(
					L"table", "table", table);

				if (table.slot)
				{
					my_stream(hlsl_path, table.name + ".h") << hlsl_templates.generate2(L"slot", "table", table);
				}
			}

			if (!table.find_option("shader_only"))
			{
				my_stream(cpp_path + "/tables", table.name + ".table.ixx") << cpp_templates.generate2(
					L"table", "table", table);

				if (table.slot)
				{
					my_stream(cpp_path + "/slots", table.name + ".ixx") << cpp_templates.generate2(
						L"slot", "table", table);
				}
			}

			if (table.find_option("RenderTarget"))
			{
				my_stream(hlsl_path + "/rt", table.name + ".h") << hlsl_templates.generate2(L"rt", "rt", table);
				my_stream(cpp_path + "/rt", table.name + ".rt.ixx") << cpp_templates.generate2(L"rt", "rt", table);
				std::filesystem::remove(cpp_path + "/rt/" + table.name + ".h");
				std::filesystem::remove(cpp_path + "/rt/" + table.name + ".ixx");
			}
		}

		// Layout
		for (auto& layout : parsed.layouts)
		{
			my_stream(hlsl_path + "/layout", layout.name + ".h") << hlsl_templates.generate2(
				L"layout", "layout", layout);
			my_stream(cpp_path + "/layout", layout.name + ".layout.ixx") << cpp_templates.generate2(
				L"layout", "layout", layout);
		}

		// PSO
		auto remove_old_pso_h = [&](const std::string& name)
		{
			std::filesystem::remove(cpp_path + "/pso/" + name + ".h");
			std::filesystem::remove(cpp_path + "/pso/" + name + ".ixx");
		};

		for (auto& pso : parsed.compute_pso)
		{
			my_stream(cpp_path + "/pso", pso.name + ".pso.ixx") << cpp_templates.generate2(L"pso", "pso", pso);
			remove_old_pso_h(pso.name);
		}

		for (auto& pso : parsed.graphics_pso)
		{
			my_stream(cpp_path + "/pso", pso.name + ".pso.ixx") << cpp_templates.generate2(L"pso", "pso", pso);
			remove_old_pso_h(pso.name);
		}

		for (auto& pso : parsed.workgraph_pso)
		{
			my_stream(cpp_path + "/pso", pso.name + ".pso.ixx") << cpp_templates.generate2(L"pso", "pso", pso);
			remove_old_pso_h(pso.name);
			my_stream(hlsl_path + "/workgraph", pso.name + ".h") << hlsl_templates.generate2(L"workgraph_nodes", "pso", pso);

			for (auto& node : pso.nodes)
			{
				auto dp = make_map(pso);
				auto dn = make_map(node);
				ValuesMap params = {
					{"pso", Reflect(dp)},
					{"node", Reflect(dn)},
				};
				my_stream(cpp_path + "/pso", pso.name + "_" + node.name + ".pso.ixx") << cpp_templates.generate(L"workgraph_node_pso", params);
			}
		}

		// RTX
		for (auto& pso : parsed.raytrace_gen)
		{
			auto bind = pso.find_option("Bind");
			parsed.find_rtx(bind->value_atom.expr)->gens.emplace_back(pso);

			my_stream(cpp_path + "/rtx", pso.name + ".h") << cpp_templates.generate2(L"raygen_pass", "pso", pso);
		}

		for (auto& pso : parsed.raytrace_pass)
		{
			auto bind = pso.find_option("Bind");
			parsed.find_rtx(bind->value_atom.expr)->passes.emplace_back(pso);


			my_stream(cpp_path + "/rtx", pso.name + ".h") << cpp_templates.generate2(L"raytrace_pass", "pso", pso);
			my_stream(hlsl_path + "/rtx", pso.name + ".h") << hlsl_templates.generate2(L"pass", "pso", pso);
		}

		for (auto& pso : parsed.raytrace_pso)
		{
			// collect unique payload tables and local slots needed by this PSO's passes
			ValuesList payload_tables, local_slots;
			std::set<std::string> seen_payload, seen_local;
			for (auto& pass : pso.passes)
			{
				auto* payload = pass.find_param("payload");
				if (payload && seen_payload.insert(payload->expr).second)
					payload_tables.emplace_back(payload->expr);

				auto* local = pass.find_param("local");
				if (local && seen_local.insert(local->expr).second)
					local_slots.emplace_back(local->expr);
			}

			auto dp = make_map(pso);
			ValuesMap params = {
				{ "pso",            Reflect(dp)     },
				{ "payload_tables", payload_tables  },
				{ "local_slots",    local_slots     },
			};

			my_stream(cpp_path + "/rtx", pso.name + ".rtx.ixx") << cpp_templates.generate(L"rtx_pso", params);
			std::filesystem::remove(cpp_path + "/rtx/" + pso.name + ".h");
			std::filesystem::remove(cpp_path + "/rtx/" + pso.name + ".ixx");
		}


		for (auto& pass : parsed.passes)
		{
			my_stream(cpp_path_render + "/pass", pass.name + ".h") << cpp_templates.generate2(L"pass", "pass", pass);
		}
		for (auto& view : parsed.views)
		{
			my_stream(cpp_path_render + "/pass", view.name + ".h") << cpp_templates.generate2(L"pass_view", "view", view);
		}
		for (auto& pipeline : parsed.pipelines)
		{
			my_stream(cpp_path_render + "/pass", pipeline.name + ".pipeline.h") << cpp_templates.generate2(L"pipeline", "pipeline", pipeline);
		}

		my_stream(cpp_path_render, "pass_defaults.h") << cpp_templates.generate(L"pass_defaults");
		my_stream(cpp_path_render, "resource_ids.h") << cpp_templates.generate(L"resource_ids");

		// includes
		my_stream(cpp_path, "autogen.ixx") << cpp_templates.generate(L"autogen");
		my_stream(cpp_path, "autogen.cpp") << cpp_templates.generate(L"autogen_impl");
		my_stream(cpp_path, "enums.ixx") << cpp_templates.generate(L"enums");
		my_stream(cpp_path, "pso.cpp") << cpp_templates.generate(L"psos");

		my_stream(cpp_path_render, "enums.h") << cpp_templates.generate(L"pass_enums");
		my_stream(cpp_path_render, "passes.ixx") << cpp_templates.generate(L"passes");
	}
	catch (std::exception& e)
	{
		std::cout << "Error: " << e.what() << std::endl;
	}

	return 0;
}
