// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Tables.Meshes.MeshletCaptureWrite;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)
	namespace Meshes
	{
		struct MeshletCaptureWrite
		{
			static constexpr SlotID ID = SlotID::MeshletCaptureWrite;
			HLSL::RWStructuredBuffer<uint> masks;
			HLSL::RWStructuredBuffer<uint>& GetMasks() { return masks; }
			static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
			template<class Compiler>
			void compile(Compiler& compiler) const
			{
				compiler.compile(masks, "MeshletCaptureWrite::masks");
			}
			struct Compiled
			{
				uint masks; // RWStructuredBuffer<uint>

			
				private:
				SERIALIZE()
				{
				}


			};

			static std::string get_typename()
			{
				return "Tables::MeshletCaptureWrite";
			}
			private:
			SERIALIZE()
			{
			}

		};
	}
	#pragma pack(pop)
}

