// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Tables.UI.DisplayOutput;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)
	namespace UI
	{
		struct DisplayOutput
		{
			static constexpr SlotID ID = SlotID::DisplayOutput;
			float ui_scale;
			float& GetUi_scale() { return ui_scale; }
			static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
			template<class Compiler>
			void compile(Compiler& compiler) const
			{
				compiler.compile(ui_scale, "DisplayOutput::ui_scale");
			}
			using Compiled = DisplayOutput;

			static std::string get_typename()
			{
				return "Tables::DisplayOutput";
			}
			private:
			SERIALIZE()
			{
				ar& NVP(ui_scale);
			}

		};
	}
	#pragma pack(pop)
}

