// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Slots.DDGIIndirectDebugData;
import Core;
import :Autogen.Tables.DDGIIndirectDebugData;
import :Autogen.Layouts.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	struct DDGIIndirectDebugData :public DataHolder<DDGIIndirectDebugData, SlotID::DDGIIndirectDebugData, Table::DDGIIndirectDebugData, DefaultLayout::Instance0>
	{
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
		DDGIIndirectDebugData() = default;
	};
}