// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.DownsampleDepthMip;
import Core;
import :Autogen.Tables.DownsampleDepthMip;
import :Autogen.Layouts.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace Utility
	{
		struct DownsampleDepthMip :public DataHolder<DownsampleDepthMip, SlotID::DownsampleDepthMip, Table::Utility::DownsampleDepthMip, ::Frame::DefaultLayout::Instance0>
		{
			static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
			DownsampleDepthMip() = default;
		};
	}
}