// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Slots.GatherMeshesBoxes;
import Core;
import :Autogen.Tables.GatherMeshesBoxes;
import :Autogen.Layouts.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	struct GatherMeshesBoxes :public DataHolder<GatherMeshesBoxes, SlotID::GatherMeshesBoxes, Table::GatherMeshesBoxes, DefaultLayout::Instance1>
	{
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
		GatherMeshesBoxes() = default;
	};
}