// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Slots.NormalRoughnessRepackParams;
import Core;
import :Autogen.Tables.NormalRoughnessRepackParams;
import :Autogen.Layouts.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	struct NormalRoughnessRepackParams :public DataHolder<NormalRoughnessRepackParams, SlotID::NormalRoughnessRepackParams, Table::NormalRoughnessRepackParams, DefaultLayout::Instance2>
	{
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
		NormalRoughnessRepackParams() = default;
	};
}