// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Slots.REBLUR_HitDistReconstructionSpecularResources;
import Core;
import :Autogen.Tables.REBLUR_HitDistReconstructionSpecularResources;
import :Autogen.Layouts.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	struct REBLUR_HitDistReconstructionSpecularResources :public DataHolder<REBLUR_HitDistReconstructionSpecularResources, SlotID::REBLUR_HitDistReconstructionSpecularResources, Table::REBLUR_HitDistReconstructionSpecularResources, DefaultLayout::Instance2>
	{
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
		REBLUR_HitDistReconstructionSpecularResources() = default;
	};
}