// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.REBLUR_PostBlurTS0Resources;
import Core;
import :Autogen.Tables.REBLUR_PostBlurTS0Resources;
import :Autogen.Layouts.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	struct REBLUR_PostBlurTS0Resources :public DataHolder<REBLUR_PostBlurTS0Resources, SlotID::REBLUR_PostBlurTS0Resources, Table::REBLUR_PostBlurTS0Resources, DefaultLayout::Instance2>
	{
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
		REBLUR_PostBlurTS0Resources() = default;
	};
}