// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Slots.ReflectionRTXUpscale;
import Core;
import :Autogen.Tables.ReflectionRTXUpscale;
import :Autogen.Layouts.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	struct ReflectionRTXUpscale :public DataHolder<ReflectionRTXUpscale, SlotID::ReflectionRTXUpscale, Table::ReflectionRTXUpscale, DefaultLayout::Instance5>
	{
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
		ReflectionRTXUpscale() = default;
	};
}