// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.SkyData;
import Core;
import :Autogen.Tables.SkyData;
import :Autogen.Layouts.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace Environment
	{
		struct SkyData :public DataHolder<SkyData, SlotID::SkyData, Table::Environment::SkyData, ::Frame::DefaultLayout::Instance0>
		{
			static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
			SkyData() = default;
		};
	}
}