// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
export module HAL:Autogen.Slots.VSMCopyPageDepthBatch;
import Core;
import :Autogen.Tables.VSMCopyPageDepthBatch;
import :Autogen.Layouts.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	struct VSMCopyPageDepthBatch :public DataHolder<VSMCopyPageDepthBatch, SlotID::VSMCopyPageDepthBatch, Table::VSMCopyPageDepthBatch, DefaultLayout::Instance0>
	{
		static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
		VSMCopyPageDepthBatch() = default;
	};
}