// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.VSMDepthAnalysis;
import Core;
import :Autogen.Tables.VSMDepthAnalysis;
import :Autogen.Layouts.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace Shadows
	{
		namespace VSM
		{
			struct VSMDepthAnalysis :public DataHolder<VSMDepthAnalysis, SlotID::VSMDepthAnalysis, Table::Shadows::VSM::VSMDepthAnalysis, ::Frame::DefaultLayout::Instance0>
			{
				static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
				VSMDepthAnalysis() = default;
			};
		}
	}
}