// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.Shadows.VSM.VSMDownsampleHiZBatch;
import Core;
import :Autogen.Tables.Shadows.VSM.VSMDownsampleHiZBatch;
import :Autogen.Layouts.Frame.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace Shadows
	{
		namespace VSM
		{
			struct VSMDownsampleHiZBatch :public DataHolder<VSMDownsampleHiZBatch, SlotID::VSMDownsampleHiZBatch, Table::Shadows::VSM::VSMDownsampleHiZBatch, ::Frame::DefaultLayout::Instance0>
			{
				static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
				VSMDownsampleHiZBatch() = default;
			};
		}
	}
}