// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
namespace GI
{

	struct Indirect: public RaytraceRaygen<Indirect>
	{
		static const constexpr uint ID = 7;
		static const constexpr std::string_view shader = "shaders\\rtx/raytracing.hlsl";
		static const constexpr std::wstring_view raygen = L"MyRaygenShader";
	};
}