// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.Post.BloomCopy;
import Core;
import :Autogen.Tables.Post.BloomCopy;
import :Autogen.Layouts.Frame.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace Post
	{
		struct BloomCopy :public DataHolder<BloomCopy, SlotID::BloomCopy, Table::Post::BloomCopy, ::Frame::DefaultLayout::Instance0>
		{
			static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
			BloomCopy() = default;
		};
	}
}