// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Tables.Dev.DebugViewGather;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
import :Autogen.Tables.Meshes.CommandData;
export namespace Table
{
	#pragma pack(push, 1)
	namespace Dev
	{
		struct DebugViewGather
		{
			static constexpr SlotID ID = SlotID::DebugViewGather;
			HLSL::AppendStructuredBuffer<Table::Meshes::CommandData> commands;
			HLSL::AppendStructuredBuffer<Table::Meshes::CommandData>& GetCommands() { return commands; }
			static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
			template<class Compiler>
			void compile(Compiler& compiler) const
			{
				compiler.compile(commands, "DebugViewGather::commands");
			}
			struct Compiled
			{
				uint commands; // AppendStructuredBuffer<CommandData>

			
				private:
				SERIALIZE()
				{
				}


			};

			static std::string get_typename()
			{
				return "Tables::DebugViewGather";
			}
			private:
			SERIALIZE()
			{
			}

		};
	}
	#pragma pack(pop)
}

