// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Tables.Dev.DebugViewTint;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
export namespace Table
{
	#pragma pack(push, 1)
	namespace Dev
	{
		struct DebugViewTint
		{
			static constexpr SlotID ID = SlotID::DebugViewTint;
			float4 tint;
			float4& GetTint() { return tint; }
			static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
			template<class Compiler>
			void compile(Compiler& compiler) const
			{
				compiler.compile(tint, "DebugViewTint::tint");
			}
			using Compiled = DebugViewTint;

			static std::string get_typename()
			{
				return "Tables::DebugViewTint";
			}
			private:
			SERIALIZE()
			{
				ar& NVP(tint);
			}

		};
	}
	#pragma pack(pop)
}

