// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Tables.Dev.DebugViewGather;

import Core;
import :SIG;
import :Types;
import :HLSL;
import :Enums;
import :Autogen.Tables.Meshes.CommandData;
export namespace Table
{
	#pragma pack(push, 1)
	namespace Dev
	{
		struct DebugViewGather
		{
			static constexpr SlotID ID = SlotID::DebugViewGather;
			uint capture_frame;
			::Dev::DebugViewSource source;
			HLSL::StructuredBuffer<uint> stamps;
			HLSL::AppendStructuredBuffer<Table::Meshes::CommandData> commands[4];
			HLSL::AppendStructuredBuffer<Table::Meshes::CommandData>* GetCommands() { return commands; }
			HLSL::StructuredBuffer<uint>& GetStamps() { return stamps; }
			uint& GetCapture_frame() { return capture_frame; }
			::Dev::DebugViewSource& GetSource() { return source; }
			static constexpr SIG_TYPE TYPE = SIG_TYPE::Table;
			template<class Compiler>
			void compile(Compiler& compiler) const
			{
				compiler.compile(capture_frame, "DebugViewGather::capture_frame");
				compiler.compile(source, "DebugViewGather::source");
				compiler.compile(stamps, "DebugViewGather::stamps");
				compiler.compile(commands, "DebugViewGather::commands");
			}
			struct Compiled
			{
				uint capture_frame; // uint
				::Dev::DebugViewSource source; // DebugViewSource
				uint stamps; // StructuredBuffer<uint>
				uint commands[4]; // AppendStructuredBuffer<CommandData>

			
				private:
				SERIALIZE()
				{
					ar& NVP(capture_frame);
					ar& NVP(source);
				}


			};

			static std::string get_typename()
			{
				return "Tables::DebugViewGather";
			}
			private:
			SERIALIZE()
			{
				ar& NVP(capture_frame);
				ar& NVP(source);
			}

		};
	}
	#pragma pack(pop)
}

