// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.Denoise.NRD.Clear_UInt4Resources;
import Core;
import :Autogen.Tables.Denoise.NRD.Clear_UInt4Resources;
import :Autogen.Layouts.Frame.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace Denoise
	{
		namespace NRD
		{
			struct Clear_UInt4Resources :public DataHolder<Clear_UInt4Resources, SlotID::Clear_UInt4Resources, Table::Denoise::NRD::Clear_UInt4Resources, ::Frame::DefaultLayout::Instance2>
			{
				static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
				Clear_UInt4Resources() = default;
			};
		}
	}
}