// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.Denoise.NRD.REBLUR_ValidationResources;
import Core;
import :Autogen.Tables.Denoise.NRD.REBLUR_ValidationResources;
import :Autogen.Layouts.Frame.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace Denoise
	{
		namespace NRD
		{
			struct REBLUR_ValidationResources :public DataHolder<REBLUR_ValidationResources, SlotID::REBLUR_ValidationResources, Table::Denoise::NRD::REBLUR_ValidationResources, ::Frame::DefaultLayout::Instance2>
			{
				static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
				REBLUR_ValidationResources() = default;
			};
		}
	}
}