// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.Dev.FrameGraph_Debug_TextureCube;
import Core;
import :Autogen.Tables.Dev.FrameGraph_Debug_TextureCube;
import :Autogen.Layouts.Frame.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace Dev
	{
		struct FrameGraph_Debug_TextureCube :public DataHolder<FrameGraph_Debug_TextureCube, SlotID::FrameGraph_Debug_TextureCube, Table::Dev::FrameGraph_Debug_TextureCube, ::Frame::DefaultLayout::Instance1>
		{
			static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
			FrameGraph_Debug_TextureCube() = default;
		};
	}
}