// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.Shadows.Denoise.DenoiserShadow_FilterLast;
import Core;
import :Autogen.Tables.Shadows.Denoise.DenoiserShadow_FilterLast;
import :Autogen.Layouts.Frame.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace Shadows
	{
		namespace Denoise
		{
			struct DenoiserShadow_FilterLast :public DataHolder<DenoiserShadow_FilterLast, SlotID::DenoiserShadow_FilterLast, Table::Shadows::Denoise::DenoiserShadow_FilterLast, ::Frame::DefaultLayout::Instance1>
			{
				static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
				DenoiserShadow_FilterLast() = default;
			};
		}
	}
}