// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.Shadows.Denoise.DenoiserShadow_TileClassification;
import Core;
import :Autogen.Tables.Shadows.Denoise.DenoiserShadow_TileClassification;
import :Autogen.Layouts.Frame.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace Shadows
	{
		namespace Denoise
		{
			struct DenoiserShadow_TileClassification :public DataHolder<DenoiserShadow_TileClassification, SlotID::DenoiserShadow_TileClassification, Table::Shadows::Denoise::DenoiserShadow_TileClassification, ::Frame::DefaultLayout::Instance0>
			{
				static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
				DenoiserShadow_TileClassification() = default;
			};
		}
	}
}