// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.Environment.SkyFace;
import Core;
import :Autogen.Tables.Environment.SkyFace;
import :Autogen.Layouts.Frame.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace Environment
	{
		struct SkyFace :public DataHolder<SkyFace, SlotID::SkyFace, Table::Environment::SkyFace, ::Frame::DefaultLayout::Instance1>
		{
			static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
			SkyFace() = default;
		};
	}
}