// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"

using namespace FrameGraph;

namespace Passes
{

class CubeMapEnviromentProcessor : public PassNodeBase
{
public:
	struct Context
	{


		Handlers::TextureCube sky_cubemap = ResourceID::sky_cubemap;


		Handlers::TextureCube sky_cubemap_filtered = ResourceID::sky_cubemap_filtered;


		Handlers::TextureCube sky_cubemap_filtered_diffuse = ResourceID::sky_cubemap_filtered_diffuse;


		// Resources this pass always creates with a fixed desc, generated from
		// each field's own [Size]/[Format] annotation (plus [Always] for the
		// creation flags, or [Always]+[Recreate]+[RecreateFlags] for a field
		// that needs its original chain link before recreating a new one).
		// Called by TypedPass::setup() after setup_func returns true - not a
		// substitute for setup_func's own create()/recreate() calls for
		// anything whose Desc depends on runtime state.
		static void create_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.create(data.sky_cubemap_filtered, { ivec3(64, 64, 0), HAL::Format::R11G11B10_FLOAT, 1, 0 }, FrameGraph::ResourceFlags::UnorderedAccess | FrameGraph::ResourceFlags::Static);
			builder.create(data.sky_cubemap_filtered_diffuse, { ivec3(64, 64, 0), HAL::Format::R11G11B10_FLOAT, 1, 0 }, FrameGraph::ResourceFlags::UnorderedAccess | FrameGraph::ResourceFlags::Static);
		}
		// Resources this pass touches, in declaration order, each paired with
		// whether the pass writes it (own [Write], or the view usage's
		// [Write] / [Write = {leaves...}] for resources inside a view group).
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
			{ ResourceID::sky_cubemap, false },
			{ ResourceID::sky_cubemap_filtered, true },
			{ ResourceID::sky_cubemap_filtered_diffuse, true },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"CubeMapEnviromentProcessor"};

	static constexpr PassID ID = PassID::CubeMapEnviromentProcessor;


	using setup_func_type = std::function<FrameGraph::SetupResult(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	setup_func_type setup_func;
	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::Compute;
};

}
