// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"

using namespace FrameGraph;

namespace Passes
{

class DDGIIndirectDebug : public PassNodeBase
{
public:
	struct Context
	{


		Handlers::Texture GBuffer_Normals = ResourceID::GBuffer_Normals;


		Handlers::Texture GBuffer_DepthMips = ResourceID::GBuffer_DepthMips;


		Handlers::Texture DDGI_ProbeIrradiance = ResourceID::DDGI_ProbeIrradiance;


		Handlers::Texture DDGI_ProbeVisibility = ResourceID::DDGI_ProbeVisibility;


		Handlers::StructuredBuffer<uint> DDGI_ProbeResidency = ResourceID::DDGI_ProbeResidency;


		Handlers::StructuredBuffer<uint> scene = ResourceID::scene;


		Handlers::StructuredBuffer<uint> DDGI_ProbeResidencyPending = ResourceID::DDGI_ProbeResidencyPending;


		Handlers::Texture DDGIIndirectDebug = ResourceID::DDGIIndirectDebug;


		// Resources this pass always needs whenever it runs, generated from
		// each field's own [Always=X] annotation (further gated by [Optional=X]
		// when present -- a raw bool expression, e.g. builder.exists(...) or a
		// context-read flag, deciding whether this specific field is actually
		// needed this frame), or, for a View-typed field (e.g. `GBuffer
		// gbuffer;`), every leaf the View itself marks [Always=X] that this
		// pass's own [Write=...] on that field doesn't already cover. A field
		// that ALSO carries [Size]/[Format] (so create_always() below creates
		// it under its own [Optional] condition) gets the negated condition
		// here instead -- "need what some other instance/frame already
		// created" is the complement of "create it this time." Called by
		// TypedPass::setup() after setup_func returns true - not a
		// substitute for setup_func's own need()/create() calls for anything
		// else conditional.
		static void need_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.need(data.GBuffer_Normals, FrameGraph::ResourceFlags::Read);
			builder.need(data.GBuffer_DepthMips, FrameGraph::ResourceFlags::Read);
			builder.need(data.DDGI_ProbeIrradiance, FrameGraph::ResourceFlags::Read);
			builder.need(data.DDGI_ProbeVisibility, FrameGraph::ResourceFlags::Read);
			builder.need(data.DDGI_ProbeResidency, FrameGraph::ResourceFlags::Read);
			builder.need(data.scene, FrameGraph::ResourceFlags::Read);
			builder.need(data.DDGI_ProbeResidencyPending, FrameGraph::ResourceFlags::UnorderedAccess);
		}

		// Resources this pass always creates with a fixed desc, generated from
		// each field's own [Size]/[Format] annotation (plus [Always] for the
		// creation flags, or [Always]+[Recreate]+[RecreateFlags] for a field
		// that needs its original chain link before recreating a new one). A
		// field that ALSO carries [Optional] creates only under that
		// condition -- need_always() (above) emits a complementary need() for
		// the SAME field under the negated condition, using the same
		// [Always] flags, e.g. a [Multiple] pass where instance 0 creates a
		// shared resource and every other instance just needs it (see
		// PSSM_Cascade, pssm.sig). Called by TypedPass::setup() after
		// setup_func returns true - not a substitute for setup_func's own
		// create()/recreate() calls for anything whose Desc depends on
		// runtime state.
		static void create_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.create(data.DDGIIndirectDebug, { ivec3(builder.graph->get_context<Table::ViewportContext>().frame_size, 0), HAL::Format::R16G16B16A16_FLOAT, 1, 1 }, FrameGraph::ResourceFlags::UnorderedAccess);
		}
		// Which chain link each handler field resolved to, one named slot per
		// field. Filled from a live frame's finished Context and applied on a
		// replayed one, so a replay neither re-runs create_always/need_always nor
		// depends on the order they made their calls in. The id is not stored:
		// the field fixes it.
		struct Cache
		{
			FrameGraph::ChainIndex GBuffer_Normals = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex GBuffer_DepthMips = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex DDGI_ProbeIrradiance = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex DDGI_ProbeVisibility = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex DDGI_ProbeResidency = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex scene = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex DDGI_ProbeResidencyPending = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex DDGIIndirectDebug = FrameGraph::ChainIndex::Unresolved;
		};

		static void save_to_cache([[maybe_unused]] const Context& data, [[maybe_unused]] Cache& cache)
		{
			cache.GBuffer_Normals = FrameGraph::TaskBuilder::cache_slot(data.GBuffer_Normals, ResourceID::GBuffer_Normals);
			cache.GBuffer_DepthMips = FrameGraph::TaskBuilder::cache_slot(data.GBuffer_DepthMips, ResourceID::GBuffer_DepthMips);
			cache.DDGI_ProbeIrradiance = FrameGraph::TaskBuilder::cache_slot(data.DDGI_ProbeIrradiance, ResourceID::DDGI_ProbeIrradiance);
			cache.DDGI_ProbeVisibility = FrameGraph::TaskBuilder::cache_slot(data.DDGI_ProbeVisibility, ResourceID::DDGI_ProbeVisibility);
			cache.DDGI_ProbeResidency = FrameGraph::TaskBuilder::cache_slot(data.DDGI_ProbeResidency, ResourceID::DDGI_ProbeResidency);
			cache.scene = FrameGraph::TaskBuilder::cache_slot(data.scene, ResourceID::scene);
			cache.DDGI_ProbeResidencyPending = FrameGraph::TaskBuilder::cache_slot(data.DDGI_ProbeResidencyPending, ResourceID::DDGI_ProbeResidencyPending);
			cache.DDGIIndirectDebug = FrameGraph::TaskBuilder::cache_slot(data.DDGIIndirectDebug, ResourceID::DDGIIndirectDebug);
		}

		// Replay counterpart of create_always/need_always. A field this pass
		// creates gets its desc recomputed on the link the cache names, so descs
		// follow the current context instead of being stored in the plan; every
		// other field is only pointed at its link. Each link is created by exactly
		// one pass and nothing here reads another resource's desc, so passes can
		// load in any order. A [Recreate] without [Size]/[Format] copies the
		// previous link's desc, which LoadGraph does once every pass has loaded.
		static void load_from_cache([[maybe_unused]] Context& data, [[maybe_unused]] const Cache& cache, [[maybe_unused]] const FrameGraph::TaskBuilder& builder)
		{
			builder.load(data.GBuffer_Normals, ResourceID::GBuffer_Normals, cache.GBuffer_Normals);
			builder.load(data.GBuffer_DepthMips, ResourceID::GBuffer_DepthMips, cache.GBuffer_DepthMips);
			builder.load(data.DDGI_ProbeIrradiance, ResourceID::DDGI_ProbeIrradiance, cache.DDGI_ProbeIrradiance);
			builder.load(data.DDGI_ProbeVisibility, ResourceID::DDGI_ProbeVisibility, cache.DDGI_ProbeVisibility);
			builder.load(data.DDGI_ProbeResidency, ResourceID::DDGI_ProbeResidency, cache.DDGI_ProbeResidency);
			builder.load(data.scene, ResourceID::scene, cache.scene);
			builder.load(data.DDGI_ProbeResidencyPending, ResourceID::DDGI_ProbeResidencyPending, cache.DDGI_ProbeResidencyPending);
			builder.create_versioned(data.DDGIIndirectDebug, cache.DDGIIndirectDebug, { ivec3(builder.graph->get_context<Table::ViewportContext>().frame_size, 0), HAL::Format::R16G16B16A16_FLOAT, 1, 1 });
		}

		// Resources this pass touches, in declaration order, each paired with
		// whether the pass writes it (own [Write], or the view usage's
		// [Write] / [Write = {leaves...}] for resources inside a view group).
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
			{ ResourceID::GBuffer_Normals, false },
			{ ResourceID::GBuffer_DepthMips, false },
			{ ResourceID::DDGI_ProbeIrradiance, false },
			{ ResourceID::DDGI_ProbeVisibility, false },
			{ ResourceID::DDGI_ProbeResidency, false },
			{ ResourceID::scene, false },
			{ ResourceID::DDGI_ProbeResidencyPending, true },
			{ ResourceID::DDGIIndirectDebug, true },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"DDGIIndirectDebug"};

	static constexpr PassID ID = PassID::DDGIIndirectDebug;


	using setup_func_type = std::function<FrameGraph::SetupResult(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;

	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::Compute;
};

}
