// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once


using namespace FrameGraph;

namespace Passes
{
	struct GBuffer 
	{
		Handlers::Texture GBuffer_Albedo = ResourceID::GBuffer_Albedo;
		Handlers::Texture GBuffer_Normals = ResourceID::GBuffer_Normals;
		Handlers::Texture GBuffer_Depth = ResourceID::GBuffer_Depth;
		Handlers::Texture GBuffer_Specular = ResourceID::GBuffer_Specular;
		Handlers::Texture GBuffer_Speed = ResourceID::GBuffer_Speed;
		Handlers::Texture GBuffer_DepthMips = ResourceID::GBuffer_DepthMips;
		Handlers::Texture GBuffer_Quality = ResourceID::GBuffer_Quality;
		Handlers::Texture GBuffer_TempColor = ResourceID::GBuffer_TempColor;
		Handlers::Texture GBuffer_NormalsPrev = ResourceID::GBuffer_NormalsPrev;
		Handlers::Texture GBuffer_SpecularPrev = ResourceID::GBuffer_SpecularPrev;
		Handlers::Texture GBuffer_DepthPrev = ResourceID::GBuffer_DepthPrev;
		Handlers::Texture GBuffer_HiZ = ResourceID::GBuffer_HiZ;
		Handlers::Texture GBuffer_HiZ_UAV = ResourceID::GBuffer_HiZ_UAV;
	};
}