// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"

using namespace FrameGraph;

namespace Passes
{

class NRD_REBLUR_Execute : public PassNodeBase
{
public:
	struct Context
	{


		Handlers::Texture NRD_ViewZ = ResourceID::NRD_ViewZ;


		Handlers::Texture NRD_NormalRoughness = ResourceID::NRD_NormalRoughness;


		Handlers::Texture NRD_Mv = ResourceID::NRD_Mv;


		Handlers::Texture NRD_DiffuseRadianceHitDist = ResourceID::NRD_DiffuseRadianceHitDist;


		Handlers::Texture NRD_SpecularRadianceHitDist = ResourceID::NRD_SpecularRadianceHitDist;


		Handlers::Texture RTXIndirectDenoised = ResourceID::RTXIndirectDenoised;


		Handlers::Texture RTXIndirectDenoisedPreview = ResourceID::RTXIndirectDenoisedPreview;


		Handlers::Texture RTXReflectionDenoised = ResourceID::RTXReflectionDenoised;


		// Resources this pass always needs whenever it runs, generated from
		// each field's own [Always=X] annotation. Called by TypedPass::setup()
		// after setup_func returns true - not a substitute for setup_func's
		// own need()/create() calls for anything conditional.
		static void need_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.need(data.NRD_ViewZ, FrameGraph::ResourceFlags::ComputeRead);
			builder.need(data.NRD_NormalRoughness, FrameGraph::ResourceFlags::ComputeRead);
			builder.need(data.NRD_Mv, FrameGraph::ResourceFlags::ComputeRead);
			builder.need(data.NRD_DiffuseRadianceHitDist, FrameGraph::ResourceFlags::ComputeRead);
			builder.need(data.NRD_SpecularRadianceHitDist, FrameGraph::ResourceFlags::ComputeRead);
		}
		// Resources this pass touches, in declaration order, each paired with
		// whether the pass writes it (own [Write], or the view usage's
		// [Write] / [Write = {leaves...}] for resources inside a view group).
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
			{ ResourceID::NRD_ViewZ, false },
			{ ResourceID::NRD_NormalRoughness, false },
			{ ResourceID::NRD_Mv, false },
			{ ResourceID::NRD_DiffuseRadianceHitDist, false },
			{ ResourceID::NRD_SpecularRadianceHitDist, false },
			{ ResourceID::RTXIndirectDenoised, true },
			{ ResourceID::RTXIndirectDenoisedPreview, true },
			{ ResourceID::RTXReflectionDenoised, true },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"NRD_REBLUR_Execute"};

	static constexpr PassID ID = PassID::NRD_REBLUR_Execute;


	using setup_func_type = std::function<bool(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	setup_func_type setup_func;
	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::General;
};

}
