// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"
#include "GBuffer.h"
using namespace FrameGraph;

namespace Passes
{

class NRD_GBufferPack : public PassNodeBase
{
public:
	struct Context
	{

		GBuffer gbuffer;

		Handlers::Texture RTXIndirectNoise = ResourceID::RTXIndirectNoise;


		Handlers::Texture RTXReflectionNoise = ResourceID::RTXReflectionNoise;


		Handlers::Texture VoxelIndirectNoiseRaw = ResourceID::VoxelIndirectNoiseRaw;


		Handlers::Texture VoxelReflectionNoiseRaw = ResourceID::VoxelReflectionNoiseRaw;


		Handlers::Texture NRD_ViewZ = ResourceID::NRD_ViewZ;


		Handlers::Texture NRD_NormalRoughness = ResourceID::NRD_NormalRoughness;


		Handlers::Texture NRD_Mv = ResourceID::NRD_Mv;


		Handlers::Texture NRD_DiffuseRadianceHitDist = ResourceID::NRD_DiffuseRadianceHitDist;


		Handlers::Texture NRD_SpecularRadianceHitDist = ResourceID::NRD_SpecularRadianceHitDist;


		// Resources this pass always creates with a fixed desc, generated from
		// each field's own [Size]/[Format] annotation (plus [Always] for the
		// creation flags, or [Always]+[Recreate]+[RecreateFlags] for a field
		// that needs its original chain link before recreating a new one).
		// Called by TypedPass::setup() after setup_func returns true - not a
		// substitute for setup_func's own create()/recreate() calls for
		// anything whose Desc depends on runtime state.
		static void create_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.create(data.NRD_ViewZ, { ivec3(builder.graph->get_context<Table::ViewportContext>().frame_size, 0), HAL::Format::R32_FLOAT, 1, 1 }, FrameGraph::ResourceFlags::UnorderedAccess);
			builder.create(data.NRD_NormalRoughness, { ivec3(builder.graph->get_context<Table::ViewportContext>().frame_size, 0), HAL::Format::R8G8B8A8_UNORM, 1, 1 }, FrameGraph::ResourceFlags::UnorderedAccess);
			builder.create(data.NRD_Mv, { ivec3(builder.graph->get_context<Table::ViewportContext>().frame_size, 0), HAL::Format::R16G16B16A16_FLOAT, 1, 1 }, FrameGraph::ResourceFlags::UnorderedAccess);
			builder.create(data.NRD_DiffuseRadianceHitDist, { ivec3(builder.graph->get_context<Table::ViewportContext>().frame_size, 0), HAL::Format::R16G16B16A16_FLOAT, 1, 1 }, FrameGraph::ResourceFlags::UnorderedAccess);
			builder.create(data.NRD_SpecularRadianceHitDist, { ivec3(builder.graph->get_context<Table::ViewportContext>().frame_size, 0), HAL::Format::R16G16B16A16_FLOAT, 1, 1 }, FrameGraph::ResourceFlags::UnorderedAccess);
		}
		// Resources this pass touches, in declaration order, each paired with
		// whether the pass writes it (own [Write], or the view usage's
		// [Write] / [Write = {leaves...}] for resources inside a view group).
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
			{ ResourceID::GBuffer_Albedo, false },
			{ ResourceID::GBuffer_Normals, false },
			{ ResourceID::GBuffer_Depth, false },
			{ ResourceID::GBuffer_Specular, false },
			{ ResourceID::GBuffer_Speed, false },
			{ ResourceID::GBuffer_DepthMips, false },
			{ ResourceID::GBuffer_Quality, false },
			{ ResourceID::GBuffer_NormalsPrev, false },
			{ ResourceID::GBuffer_SpecularPrev, false },
			{ ResourceID::GBuffer_DepthPrev, false },
			{ ResourceID::RTXIndirectNoise, false },
			{ ResourceID::RTXReflectionNoise, false },
			{ ResourceID::VoxelIndirectNoiseRaw, false },
			{ ResourceID::VoxelReflectionNoiseRaw, false },
			{ ResourceID::NRD_ViewZ, true },
			{ ResourceID::NRD_NormalRoughness, true },
			{ ResourceID::NRD_Mv, true },
			{ ResourceID::NRD_DiffuseRadianceHitDist, true },
			{ ResourceID::NRD_SpecularRadianceHitDist, true },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"NRD_GBufferPack"};

	static constexpr PassID ID = PassID::NRD_GBufferPack;


	using setup_func_type = std::function<FrameGraph::SetupResult(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	setup_func_type setup_func;
	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::General;
};

}
