// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"

using namespace FrameGraph;
namespace Passes
{

class PSSM_Cascade : public PassNodeBase
{
public:
	struct Context
	{


		Handlers::Texture PSSM_Depths = ResourceID::PSSM_Depths;

		Handlers::StructuredBuffer<Table::Camera> PSSM_Cameras = ResourceID::PSSM_Cameras;

		// Resources this pass touches, in declaration order, each paired with
		// whether the pass declares [Write] on it.
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
		{ ResourceID::PSSM_Depths, false },
		{ ResourceID::PSSM_Cameras, false },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"PSSM_Cascade"};

	static constexpr uint32_t MaxCount = 6;
	static constexpr LiteralWStr Names[MaxCount] = {
		LiteralWStr{L"PSSM_Cascade_0"},
		LiteralWStr{L"PSSM_Cascade_1"},
		LiteralWStr{L"PSSM_Cascade_2"},
		LiteralWStr{L"PSSM_Cascade_3"},
		LiteralWStr{L"PSSM_Cascade_4"},
		LiteralWStr{L"PSSM_Cascade_5"},
	};

	static constexpr PassID ID = PassID::PSSM_Cascade;


	using setup_func_type = std::function<bool(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	std::array<setup_func_type, MaxCount> setup_funcs;
	std::array<render_func_type, MaxCount> render_funcs;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::General;
};

}
