// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"
#include "GBuffer.h"
using namespace FrameGraph;

namespace Passes
{

class PSSM_Combine : public PassNodeBase
{
public:
	struct Context
	{

		Handlers::StructuredBuffer<Table::Camera> PSSM_Cameras = ResourceID::PSSM_Cameras;

		GBuffer gbuffer;

		Handlers::Texture LightMask = ResourceID::LightMask;


		Handlers::Texture ShadowMask = ResourceID::ShadowMask;


		Handlers::Texture ResultTexture = ResourceID::ResultTexture;


		// Resources this pass always needs whenever it runs, generated from
		// each field's own [Always=X] annotation. Called by TypedPass::setup()
		// after setup_func returns true - not a substitute for setup_func's
		// own need()/create() calls for anything conditional.
		static void need_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.need(data.ResultTexture, FrameGraph::ResourceFlags::UnorderedAccess);
		}
		// Resources this pass touches, in declaration order, each paired with
		// whether the pass writes it (own [Write], or the view usage's
		// [Write] / [Write = {leaves...}] for resources inside a view group).
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
			{ ResourceID::PSSM_Cameras, false },
			{ ResourceID::GBuffer_Albedo, false },
			{ ResourceID::GBuffer_Normals, false },
			{ ResourceID::GBuffer_Depth, false },
			{ ResourceID::GBuffer_Specular, false },
			{ ResourceID::GBuffer_Speed, false },
			{ ResourceID::GBuffer_DepthMips, false },
			{ ResourceID::GBuffer_Quality, false },
			{ ResourceID::GBuffer_TempColor, false },
			{ ResourceID::GBuffer_NormalsPrev, false },
			{ ResourceID::GBuffer_SpecularPrev, false },
			{ ResourceID::GBuffer_DepthPrev, false },
			{ ResourceID::GBuffer_HiZ, false },
			{ ResourceID::GBuffer_HiZ_UAV, false },
			{ ResourceID::LightMask, false },
			{ ResourceID::ShadowMask, false },
			{ ResourceID::ResultTexture, true },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"PSSM_Combine"};

	static constexpr PassID ID = PassID::PSSM_Combine;


	using setup_func_type = std::function<bool(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	setup_func_type setup_func;
	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::Compute;
};

}
