// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"

using namespace FrameGraph;

namespace Passes
{

class PSSM_Global : public PassNodeBase
{
public:
	struct Context
	{


		Handlers::Texture global_depth = ResourceID::global_depth;

		Handlers::StructuredBuffer<Table::Camera> global_camera = ResourceID::global_camera;


		// Resources this pass always creates with a fixed desc, generated from
		// each field's own [Size]/[Format] annotation (plus [Always] for the
		// creation flags, or [Always]+[Recreate]+[RecreateFlags] for a field
		// that needs its original chain link before recreating a new one).
		// Called by TypedPass::setup() after setup_func returns true - not a
		// substitute for setup_func's own create()/recreate() calls for
		// anything whose Desc depends on runtime state.
		static void create_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.create(data.global_depth, { ivec3(1024, 1024, 0), HAL::Format::R32_TYPELESS, 1, 1 }, FrameGraph::ResourceFlags::DepthStencil);
			builder.create(data.global_camera, { 1 }, FrameGraph::ResourceFlags::CopyDest);
		}
		// Resources this pass touches, in declaration order, each paired with
		// whether the pass writes it (own [Write], or the view usage's
		// [Write] / [Write = {leaves...}] for resources inside a view group).
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
			{ ResourceID::global_depth, true },
			{ ResourceID::global_camera, true },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"PSSM_Global"};

	static constexpr PassID ID = PassID::PSSM_Global;


	using setup_func_type = std::function<FrameGraph::SetupResult(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	setup_func_type setup_func;
	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::General;
};

}
