// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"

using namespace FrameGraph;

namespace Passes
{

class ReflectionDenoiser_Reproject : public PassNodeBase
{
public:
	struct Context
	{


		Handlers::Texture GBuffer_DepthPrev = ResourceID::GBuffer_DepthPrev;


		Handlers::Texture GBuffer_NormalsPrev = ResourceID::GBuffer_NormalsPrev;


		Handlers::Texture GBuffer_Depth = ResourceID::GBuffer_Depth;


		Handlers::Texture GBuffer_Normals = ResourceID::GBuffer_Normals;


		Handlers::Texture GBuffer_Speed = ResourceID::GBuffer_Speed;


		Handlers::Texture VoxelReflectionNoise = ResourceID::VoxelReflectionNoise;


		Handlers::Texture ReflectionDenoiser_RadiancePrev = ResourceID::ReflectionDenoiser_RadiancePrev;


		Handlers::Texture ReflectionDenoiser_AverageRadiance = ResourceID::ReflectionDenoiser_AverageRadiance;


		Handlers::Texture ReflectionDenoiser_AverageRadiancePrev = ResourceID::ReflectionDenoiser_AverageRadiancePrev;


		Handlers::Texture ReflectionDenoiser_Variance = ResourceID::ReflectionDenoiser_Variance;


		Handlers::Texture ReflectionDenoiser_VariancePrev = ResourceID::ReflectionDenoiser_VariancePrev;


		Handlers::Texture ReflectionDenoiser_SampleCount = ResourceID::ReflectionDenoiser_SampleCount;


		Handlers::Texture ReflectionDenoiser_SampleCountPrev = ResourceID::ReflectionDenoiser_SampleCountPrev;


		Handlers::Texture ReflectionDenoiser_ReprojectedRadiance = ResourceID::ReflectionDenoiser_ReprojectedRadiance;


		Handlers::Texture BlueNoise = ResourceID::BlueNoise;

		// Resources this pass touches, in declaration order, each paired with
		// whether the pass writes it (own [Write], or the view usage's
		// [Write] / [Write = {leaves...}] for resources inside a view group).
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
			{ ResourceID::GBuffer_DepthPrev, false },
			{ ResourceID::GBuffer_NormalsPrev, false },
			{ ResourceID::GBuffer_Depth, false },
			{ ResourceID::GBuffer_Normals, false },
			{ ResourceID::GBuffer_Speed, false },
			{ ResourceID::VoxelReflectionNoise, true },
			{ ResourceID::ReflectionDenoiser_RadiancePrev, true },
			{ ResourceID::ReflectionDenoiser_AverageRadiance, true },
			{ ResourceID::ReflectionDenoiser_AverageRadiancePrev, true },
			{ ResourceID::ReflectionDenoiser_Variance, true },
			{ ResourceID::ReflectionDenoiser_VariancePrev, true },
			{ ResourceID::ReflectionDenoiser_SampleCount, true },
			{ ResourceID::ReflectionDenoiser_SampleCountPrev, true },
			{ ResourceID::ReflectionDenoiser_ReprojectedRadiance, true },
			{ ResourceID::BlueNoise, false },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"ReflectionDenoiser_Reproject"};

	static constexpr PassID ID = PassID::ReflectionDenoiser_Reproject;


	using setup_func_type = std::function<bool(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	setup_func_type setup_func;
	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::Compute;
};

}
