// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"
#include "GBuffer.h"
using namespace FrameGraph;

namespace Passes
{

class Scene : public PassNodeBase
{
public:
	struct Context
	{

		GBuffer gbuffer;

		Handlers::StructuredBuffer<uint> scene = ResourceID::scene;

		// Resources this pass touches, in declaration order, each paired with
		// whether the pass writes it (own [Write], or the view usage's
		// [Write] / [Write = {leaves...}] for resources inside a view group).
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
			{ ResourceID::GBuffer_Albedo, true },
			{ ResourceID::GBuffer_Normals, true },
			{ ResourceID::GBuffer_Depth, true },
			{ ResourceID::GBuffer_Specular, true },
			{ ResourceID::GBuffer_Speed, true },
			{ ResourceID::GBuffer_DepthMips, true },
			{ ResourceID::GBuffer_Quality, true },
			{ ResourceID::GBuffer_TempColor, false },
			{ ResourceID::GBuffer_NormalsPrev, false },
			{ ResourceID::GBuffer_SpecularPrev, false },
			{ ResourceID::GBuffer_DepthPrev, false },
			{ ResourceID::GBuffer_HiZ, true },
			{ ResourceID::GBuffer_HiZ_UAV, true },
			{ ResourceID::scene, false },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"Scene"};

	static constexpr PassID ID = PassID::Scene;


	using setup_func_type = std::function<bool(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	setup_func_type setup_func;
	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::General;
};

}
