// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"

using namespace FrameGraph;
namespace Passes
{

class Sky : public PassNodeBase
{
public:
	struct Context
	{


		Handlers::Texture GBuffer_Depth = ResourceID::GBuffer_Depth;


		Handlers::Texture ResultTexture = ResourceID::ResultTexture;

		// Resources this pass touches, in declaration order, each paired with
		// whether the pass declares [Write] on it.
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
		{ ResourceID::GBuffer_Depth, false },
		{ ResourceID::ResultTexture, false },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"Sky"};

	static constexpr PassID ID = PassID::Sky;


	using setup_func_type = std::function<bool(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	setup_func_type setup_func;
	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::General;
};

}
