// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"

using namespace FrameGraph;
namespace Passes
{

class stencil_renderer_before : public PassNodeBase
{
public:
	struct Context
	{


		Handlers::Texture depth_tex = ResourceID::depth_tex;


		Handlers::StructuredBuffer<UINT> id_buffer = ResourceID::id_buffer;


		Handlers::StructuredBuffer<UINT> axis_id_buffer = ResourceID::axis_id_buffer;

		// Resources this pass touches, in declaration order, each paired with
		// whether the pass declares [Write] on it.
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
		{ ResourceID::depth_tex, false },
		{ ResourceID::id_buffer, false },
		{ ResourceID::axis_id_buffer, false },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"stencil_renderer_before"};

	static constexpr PassID ID = PassID::stencil_renderer_before;


	using setup_func_type = std::function<bool(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	setup_func_type setup_func;
	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::Required;
};

}
