// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"

using namespace FrameGraph;
namespace Passes
{

class UI_PreDraw : public PassNodeBase
{
public:
	struct Context
	{


		Handlers::StructuredBuffer<uint> UI_PreDraw_Sync = ResourceID::UI_PreDraw_Sync;

		static inline const wchar_t* const resource_names[] = {		L"UI_PreDraw_Sync",
		};
		static constexpr uint resource_count = std::size(resource_names);
	};


	std::span<const wchar_t* const> GetUsedResourcesList() const override
	{
		return std::span<const wchar_t* const>(Context::resource_names, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"UI_PreDraw"};

	static constexpr PassID ID = PassID::UI_PreDraw;


	using setup_func_type = std::function<bool(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	setup_func_type setup_func;
	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::Required;
};

}
