// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"

using namespace FrameGraph;

namespace Passes
{

class UI_Render : public PassNodeBase
{
public:
	struct Context
	{


		Handlers::Texture swapchain = ResourceID::swapchain;


		Handlers::StructuredBuffer<uint> UI_PreDraw_Sync = ResourceID::UI_PreDraw_Sync;


		// Resources this pass always needs whenever it runs, generated from
		// each field's own [Always=X] annotation. Called by TypedPass::setup()
		// after setup_func returns true - not a substitute for setup_func's
		// own need()/create() calls for anything conditional.
		static void need_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.need(data.swapchain, FrameGraph::ResourceFlags::RenderTarget);
		}
		// Resources this pass touches, in declaration order, each paired with
		// whether the pass writes it (own [Write], or the view usage's
		// [Write] / [Write = {leaves...}] for resources inside a view group).
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
			{ ResourceID::swapchain, true },
			{ ResourceID::UI_PreDraw_Sync, false },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"UI_Render"};

	static constexpr uint32_t MaxCount = 16;
	static constexpr LiteralWStr Names[MaxCount] = {
		LiteralWStr{L"UI_Render_0"},
		LiteralWStr{L"UI_Render_1"},
		LiteralWStr{L"UI_Render_2"},
		LiteralWStr{L"UI_Render_3"},
		LiteralWStr{L"UI_Render_4"},
		LiteralWStr{L"UI_Render_5"},
		LiteralWStr{L"UI_Render_6"},
		LiteralWStr{L"UI_Render_7"},
		LiteralWStr{L"UI_Render_8"},
		LiteralWStr{L"UI_Render_9"},
		LiteralWStr{L"UI_Render_10"},
		LiteralWStr{L"UI_Render_11"},
		LiteralWStr{L"UI_Render_12"},
		LiteralWStr{L"UI_Render_13"},
		LiteralWStr{L"UI_Render_14"},
		LiteralWStr{L"UI_Render_15"},
	};

	static constexpr PassID ID = PassID::UI_Render;


	using setup_func_type = std::function<FrameGraph::SetupResult(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	std::array<setup_func_type, MaxCount> setup_funcs;
	std::array<render_func_type, MaxCount> render_funcs;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::General;
};

}
