// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"
#include "GBuffer.h"
using namespace FrameGraph;
namespace Passes
{

class VoxelDebug : public PassNodeBase
{
public:
	struct Context
	{

		GBuffer gbuffer;

		Handlers::Texture VoxelDebug = ResourceID::VoxelDebug;


		Handlers::Texture3D VoxelLighted = ResourceID::VoxelLighted;

		// Resources this pass touches, in declaration order, each paired with
		// whether the pass declares [Write] on it.
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
		{ ResourceID::GBuffer_Albedo, false },
		{ ResourceID::GBuffer_Normals, false },
		{ ResourceID::GBuffer_Depth, false },
		{ ResourceID::GBuffer_Specular, false },
		{ ResourceID::GBuffer_Speed, false },
		{ ResourceID::GBuffer_DepthMips, false },
		{ ResourceID::GBuffer_Quality, false },
		{ ResourceID::GBuffer_TempColor, false },
		{ ResourceID::GBuffer_NormalsPrev, false },
		{ ResourceID::GBuffer_SpecularPrev, false },
		{ ResourceID::GBuffer_DepthPrev, false },
		{ ResourceID::GBuffer_HiZ, false },
		{ ResourceID::GBuffer_HiZ_UAV, false },
		{ ResourceID::VoxelDebug, false },
		{ ResourceID::VoxelLighted, false },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"VoxelDebug"};

	static constexpr PassID ID = PassID::VoxelDebug;


	using setup_func_type = std::function<bool(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	setup_func_type setup_func;
	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::General;
};

}
