// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"

using namespace FrameGraph;

namespace Passes
{

class VSM_RenderPages : public PassNodeBase
{
public:
	struct Context
	{


		Handlers::Texture VSM_Atlas = ResourceID::VSM_Atlas;


		Handlers::Texture VSM_PageTable = ResourceID::VSM_PageTable;

		Handlers::StructuredBuffer<Table::Camera> VSM_PageCameras = ResourceID::VSM_PageCameras;


		Handlers::Texture VSM_PageHiZ = ResourceID::VSM_PageHiZ;

		Handlers::StructuredBuffer<Table::VSMDispatchCommandData> VSM_DispatchCommands = ResourceID::VSM_DispatchCommands;

		// Resources this pass touches, in declaration order, each paired with
		// whether the pass writes it (own [Write], or the view usage's
		// [Write] / [Write = {leaves...}] for resources inside a view group).
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
			{ ResourceID::VSM_Atlas, true },
			{ ResourceID::VSM_PageTable, true },
			{ ResourceID::VSM_PageCameras, true },
			{ ResourceID::VSM_PageHiZ, true },
			{ ResourceID::VSM_DispatchCommands, false },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"VSM_RenderPages"};

	static constexpr PassID ID = PassID::VSM_RenderPages;


	using setup_func_type = std::function<bool(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	setup_func_type setup_func;
	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::General;
};

}
