// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"

using namespace FrameGraph;

namespace Passes
{

class VSM_BlockerSearch : public PassNodeBase
{
public:
	struct Context
	{


		Handlers::Texture GBuffer_Albedo = ResourceID::GBuffer_Albedo;


		Handlers::Texture GBuffer_Normals = ResourceID::GBuffer_Normals;


		Handlers::Texture GBuffer_Specular = ResourceID::GBuffer_Specular;


		Handlers::Texture GBuffer_Speed = ResourceID::GBuffer_Speed;


		Handlers::Texture GBuffer_DepthMips = ResourceID::GBuffer_DepthMips;


		Handlers::Texture VSM_Atlas = ResourceID::VSM_Atlas;


		Handlers::Texture VSM_PageTable = ResourceID::VSM_PageTable;

		Handlers::StructuredBuffer<Table::Camera> VSM_PageCameras = ResourceID::VSM_PageCameras;


		Handlers::Texture VSM_PageHiZ = ResourceID::VSM_PageHiZ;


		Handlers::Texture BlueNoise = ResourceID::BlueNoise;


		Handlers::StructuredBuffer<uint2> VSM_SearchTiles = ResourceID::VSM_SearchTiles;


		Handlers::Texture VSM_BlockerSearchResult = ResourceID::VSM_BlockerSearchResult;


		Handlers::StructuredBuffer<uint2> VSM_ConfirmedLitTiles = ResourceID::VSM_ConfirmedLitTiles;


		Handlers::StructuredBuffer<uint2> VSM_BlurTiles = ResourceID::VSM_BlurTiles;


		Handlers::Texture VSM_AmbiguousMask = ResourceID::VSM_AmbiguousMask;


		// Resources this pass always needs whenever it runs, generated from
		// each field's own [Always=X] annotation (further gated by [Optional=X]
		// when present -- a raw bool expression, e.g. builder.exists(...) or a
		// context-read flag, deciding whether this specific field is actually
		// needed this frame), or, for a View-typed field (e.g. `GBuffer
		// gbuffer;`), every leaf the View itself marks [Always=X] that this
		// pass's own [Write=...] on that field doesn't already cover. A field
		// that ALSO carries [Size]/[Format] (so create_always() below creates
		// it under its own [Optional] condition) gets the negated condition
		// here instead -- "need what some other instance/frame already
		// created" is the complement of "create it this time." Called by
		// TypedPass::setup() after setup_func returns true - not a
		// substitute for setup_func's own need()/create() calls for anything
		// else conditional.
		static void need_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.need(data.GBuffer_Albedo, FrameGraph::ResourceFlags::Read);
			builder.need(data.GBuffer_Normals, FrameGraph::ResourceFlags::Read);
			builder.need(data.GBuffer_Specular, FrameGraph::ResourceFlags::Read);
			builder.need(data.GBuffer_Speed, FrameGraph::ResourceFlags::Read);
			builder.need(data.GBuffer_DepthMips, FrameGraph::ResourceFlags::None);
			builder.need(data.VSM_Atlas, FrameGraph::ResourceFlags::Read);
			builder.need(data.VSM_PageTable, FrameGraph::ResourceFlags::Read);
			builder.need(data.VSM_PageCameras, FrameGraph::ResourceFlags::Read);
			builder.need(data.VSM_PageHiZ, FrameGraph::ResourceFlags::Read);
			builder.need(data.BlueNoise, FrameGraph::ResourceFlags::Read);
			builder.need(data.VSM_SearchTiles, FrameGraph::ResourceFlags::Read);
		}

		// Resources this pass always creates with a fixed desc, generated from
		// each field's own [Size]/[Format] annotation (plus [Always] for the
		// creation flags, or [Always]+[Recreate]+[RecreateFlags] for a field
		// that needs its original chain link before recreating a new one). A
		// field that ALSO carries [Optional] creates only under that
		// condition -- need_always() (above) emits a complementary need() for
		// the SAME field under the negated condition, using the same
		// [Always] flags, e.g. a [Multiple] pass where instance 0 creates a
		// shared resource and every other instance just needs it (see
		// PSSM_Cascade, pssm.sig). Called by TypedPass::setup() after
		// setup_func returns true - not a substitute for setup_func's own
		// create()/recreate() calls for anything whose Desc depends on
		// runtime state.
		static void create_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.create(data.VSM_BlockerSearchResult, { ivec3(builder.graph->get_context<Table::ViewportContext>().frame_size, 0), HAL::Format::R32G32B32A32_UINT, 1, 1 }, FrameGraph::ResourceFlags::UnorderedAccess);
			builder.create(data.VSM_ConfirmedLitTiles, { (size_t)(((builder.graph->get_context<Table::ViewportContext>().frame_size.x + 15) / 16) * ((builder.graph->get_context<Table::ViewportContext>().frame_size.y + 15) / 16)), true }, FrameGraph::ResourceFlags::UnorderedAccess);
			builder.create(data.VSM_BlurTiles, { (size_t)(((builder.graph->get_context<Table::ViewportContext>().frame_size.x + 15) / 16) * ((builder.graph->get_context<Table::ViewportContext>().frame_size.y + 15) / 16)), true }, FrameGraph::ResourceFlags::UnorderedAccess);
			builder.create(data.VSM_AmbiguousMask, { ivec3(ivec2((builder.graph->get_context<Table::ViewportContext>().frame_size.x + 15) / 16, (builder.graph->get_context<Table::ViewportContext>().frame_size.y + 15) / 16), 0), HAL::Format::R8_UNORM, 1, 1 }, FrameGraph::ResourceFlags::UnorderedAccess);
		}
		// Which chain link each handler field resolved to, one named slot per
		// field. Filled from a live frame's finished Context and applied on a
		// replayed one, so a replay neither re-runs create_always/need_always nor
		// depends on the order they made their calls in. The id is not stored:
		// the field fixes it.
		struct Cache
		{
			FrameGraph::ChainIndex GBuffer_Albedo = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex GBuffer_Normals = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex GBuffer_Specular = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex GBuffer_Speed = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex GBuffer_DepthMips = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex VSM_Atlas = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex VSM_PageTable = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex VSM_PageCameras = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex VSM_PageHiZ = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex BlueNoise = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex VSM_SearchTiles = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex VSM_BlockerSearchResult = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex VSM_ConfirmedLitTiles = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex VSM_BlurTiles = FrameGraph::ChainIndex::Unresolved;
			FrameGraph::ChainIndex VSM_AmbiguousMask = FrameGraph::ChainIndex::Unresolved;
		};

		static void save_to_cache([[maybe_unused]] const Context& data, [[maybe_unused]] Cache& cache)
		{
			cache.GBuffer_Albedo = FrameGraph::TaskBuilder::cache_slot(data.GBuffer_Albedo, ResourceID::GBuffer_Albedo);
			cache.GBuffer_Normals = FrameGraph::TaskBuilder::cache_slot(data.GBuffer_Normals, ResourceID::GBuffer_Normals);
			cache.GBuffer_Specular = FrameGraph::TaskBuilder::cache_slot(data.GBuffer_Specular, ResourceID::GBuffer_Specular);
			cache.GBuffer_Speed = FrameGraph::TaskBuilder::cache_slot(data.GBuffer_Speed, ResourceID::GBuffer_Speed);
			cache.GBuffer_DepthMips = FrameGraph::TaskBuilder::cache_slot(data.GBuffer_DepthMips, ResourceID::GBuffer_DepthMips);
			cache.VSM_Atlas = FrameGraph::TaskBuilder::cache_slot(data.VSM_Atlas, ResourceID::VSM_Atlas);
			cache.VSM_PageTable = FrameGraph::TaskBuilder::cache_slot(data.VSM_PageTable, ResourceID::VSM_PageTable);
			cache.VSM_PageCameras = FrameGraph::TaskBuilder::cache_slot(data.VSM_PageCameras, ResourceID::VSM_PageCameras);
			cache.VSM_PageHiZ = FrameGraph::TaskBuilder::cache_slot(data.VSM_PageHiZ, ResourceID::VSM_PageHiZ);
			cache.BlueNoise = FrameGraph::TaskBuilder::cache_slot(data.BlueNoise, ResourceID::BlueNoise);
			cache.VSM_SearchTiles = FrameGraph::TaskBuilder::cache_slot(data.VSM_SearchTiles, ResourceID::VSM_SearchTiles);
			cache.VSM_BlockerSearchResult = FrameGraph::TaskBuilder::cache_slot(data.VSM_BlockerSearchResult, ResourceID::VSM_BlockerSearchResult);
			cache.VSM_ConfirmedLitTiles = FrameGraph::TaskBuilder::cache_slot(data.VSM_ConfirmedLitTiles, ResourceID::VSM_ConfirmedLitTiles);
			cache.VSM_BlurTiles = FrameGraph::TaskBuilder::cache_slot(data.VSM_BlurTiles, ResourceID::VSM_BlurTiles);
			cache.VSM_AmbiguousMask = FrameGraph::TaskBuilder::cache_slot(data.VSM_AmbiguousMask, ResourceID::VSM_AmbiguousMask);
		}

		// Replay counterpart of create_always/need_always. A field this pass
		// creates gets its desc recomputed on the link the cache names, so descs
		// follow the current context instead of being stored in the plan; every
		// other field is only pointed at its link. Each link is created by exactly
		// one pass and nothing here reads another resource's desc, so passes can
		// load in any order. A [Recreate] without [Size]/[Format] copies the
		// previous link's desc, which LoadGraph does once every pass has loaded.
		static void load_from_cache([[maybe_unused]] Context& data, [[maybe_unused]] const Cache& cache, [[maybe_unused]] const FrameGraph::TaskBuilder& builder)
		{
			builder.load(data.GBuffer_Albedo, ResourceID::GBuffer_Albedo, cache.GBuffer_Albedo);
			builder.load(data.GBuffer_Normals, ResourceID::GBuffer_Normals, cache.GBuffer_Normals);
			builder.load(data.GBuffer_Specular, ResourceID::GBuffer_Specular, cache.GBuffer_Specular);
			builder.load(data.GBuffer_Speed, ResourceID::GBuffer_Speed, cache.GBuffer_Speed);
			builder.load(data.GBuffer_DepthMips, ResourceID::GBuffer_DepthMips, cache.GBuffer_DepthMips);
			builder.load(data.VSM_Atlas, ResourceID::VSM_Atlas, cache.VSM_Atlas);
			builder.load(data.VSM_PageTable, ResourceID::VSM_PageTable, cache.VSM_PageTable);
			builder.load(data.VSM_PageCameras, ResourceID::VSM_PageCameras, cache.VSM_PageCameras);
			builder.load(data.VSM_PageHiZ, ResourceID::VSM_PageHiZ, cache.VSM_PageHiZ);
			builder.load(data.BlueNoise, ResourceID::BlueNoise, cache.BlueNoise);
			builder.load(data.VSM_SearchTiles, ResourceID::VSM_SearchTiles, cache.VSM_SearchTiles);
			builder.create_versioned(data.VSM_BlockerSearchResult, cache.VSM_BlockerSearchResult, { ivec3(builder.graph->get_context<Table::ViewportContext>().frame_size, 0), HAL::Format::R32G32B32A32_UINT, 1, 1 });
			builder.create_versioned(data.VSM_ConfirmedLitTiles, cache.VSM_ConfirmedLitTiles, { (size_t)(((builder.graph->get_context<Table::ViewportContext>().frame_size.x + 15) / 16) * ((builder.graph->get_context<Table::ViewportContext>().frame_size.y + 15) / 16)), true });
			builder.create_versioned(data.VSM_BlurTiles, cache.VSM_BlurTiles, { (size_t)(((builder.graph->get_context<Table::ViewportContext>().frame_size.x + 15) / 16) * ((builder.graph->get_context<Table::ViewportContext>().frame_size.y + 15) / 16)), true });
			builder.create_versioned(data.VSM_AmbiguousMask, cache.VSM_AmbiguousMask, { ivec3(ivec2((builder.graph->get_context<Table::ViewportContext>().frame_size.x + 15) / 16, (builder.graph->get_context<Table::ViewportContext>().frame_size.y + 15) / 16), 0), HAL::Format::R8_UNORM, 1, 1 });
		}

		// Resources this pass touches, in declaration order, each paired with
		// whether the pass writes it (own [Write], or the view usage's
		// [Write] / [Write = {leaves...}] for resources inside a view group).
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
			{ ResourceID::GBuffer_Albedo, false },
			{ ResourceID::GBuffer_Normals, false },
			{ ResourceID::GBuffer_Specular, false },
			{ ResourceID::GBuffer_Speed, false },
			{ ResourceID::GBuffer_DepthMips, false },
			{ ResourceID::VSM_Atlas, false },
			{ ResourceID::VSM_PageTable, false },
			{ ResourceID::VSM_PageCameras, false },
			{ ResourceID::VSM_PageHiZ, false },
			{ ResourceID::BlueNoise, false },
			{ ResourceID::VSM_SearchTiles, false },
			{ ResourceID::VSM_BlockerSearchResult, true },
			{ ResourceID::VSM_ConfirmedLitTiles, true },
			{ ResourceID::VSM_BlurTiles, true },
			{ ResourceID::VSM_AmbiguousMask, true },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"VSM_BlockerSearch"};

	static constexpr PassID ID = PassID::VSM_BlockerSearch;


	using setup_func_type = std::function<FrameGraph::SetupResult(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;

	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::Compute;
};

}
