// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"

using namespace FrameGraph;

namespace Passes
{

class VSM_HiZRebuild : public PassNodeBase
{
public:
	struct Context
	{


		Handlers::Texture VSM_Atlas = ResourceID::VSM_Atlas;


		Handlers::Texture VSM_PageHiZ = ResourceID::VSM_PageHiZ;


		Handlers::StructuredBuffer<uint> VSM_DirtySlots = ResourceID::VSM_DirtySlots;


		// Resources this pass always needs whenever it runs, generated from
		// each field's own [Always=X] annotation. Called by TypedPass::setup()
		// after setup_func returns true - not a substitute for setup_func's
		// own need()/create() calls for anything conditional.
		static void need_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.need(data.VSM_Atlas, FrameGraph::ResourceFlags::Read);
			builder.need(data.VSM_PageHiZ, FrameGraph::ResourceFlags::UnorderedAccess);
		}

		// Resources this pass always creates with a fixed desc, generated from
		// each field's own [Size]/[Format] annotation (plus [Always] for the
		// creation flags, or [Always]+[Recreate]+[RecreateFlags] for a field
		// that needs its original chain link before recreating a new one).
		// Called by TypedPass::setup() after setup_func returns true - not a
		// substitute for setup_func's own create()/recreate() calls for
		// anything whose Desc depends on runtime state.
		static void create_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.create(data.VSM_DirtySlots, { (size_t)Constants::VSM_PhysicalPageCount }, FrameGraph::ResourceFlags::CopyDest | FrameGraph::ResourceFlags::Static);
		}
		// Resources this pass touches, in declaration order, each paired with
		// whether the pass writes it (own [Write], or the view usage's
		// [Write] / [Write = {leaves...}] for resources inside a view group).
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
			{ ResourceID::VSM_Atlas, false },
			{ ResourceID::VSM_PageHiZ, true },
			{ ResourceID::VSM_DirtySlots, true },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"VSM_HiZRebuild"};

	static constexpr PassID ID = PassID::VSM_HiZRebuild;


	using setup_func_type = std::function<FrameGraph::SetupResult(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	setup_func_type setup_func;
	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::Compute;
};

}
