// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"

using namespace FrameGraph;

namespace Passes
{

class VSM_RenderPages : public PassNodeBase
{
public:
	struct Context
	{


		Handlers::Texture VSM_Atlas = ResourceID::VSM_Atlas;


		Handlers::Texture VSM_PageTable = ResourceID::VSM_PageTable;

		Handlers::StructuredBuffer<Table::Camera> VSM_PageCameras = ResourceID::VSM_PageCameras;


		Handlers::Texture VSM_PageHiZ = ResourceID::VSM_PageHiZ;

		Handlers::StructuredBuffer<Table::VSMDispatchCommandData> VSM_DispatchCommands = ResourceID::VSM_DispatchCommands;

		Handlers::StructuredBuffer<Table::VSMLevelDispatchInfo> VSM_LevelDispatchInfo = ResourceID::VSM_LevelDispatchInfo;


		// Resources this pass always needs whenever it runs, generated from
		// each field's own [Always=X] annotation (further gated by [Optional=X]
		// when present -- a raw bool expression, e.g. builder.exists(...) or a
		// context-read flag, deciding whether this specific field is actually
		// needed this frame), or, for a View-typed field (e.g. `GBuffer
		// gbuffer;`), every leaf the View itself marks [Always=X] that this
		// pass's own [Write=...] on that field doesn't already cover. A field
		// that ALSO carries [Size]/[Format] (so create_always() below creates
		// it under its own [Optional] condition) gets the negated condition
		// here instead -- "need what some other instance/frame already
		// created" is the complement of "create it this time." Called by
		// TypedPass::setup() after setup_func returns true - not a
		// substitute for setup_func's own need()/create() calls for anything
		// else conditional.
		static void need_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.need(data.VSM_Atlas, FrameGraph::ResourceFlags::DepthStencil);
			builder.need(data.VSM_DispatchCommands, FrameGraph::ResourceFlags::Read);
			builder.need(data.VSM_LevelDispatchInfo, FrameGraph::ResourceFlags::Read);
		}

		// Resources this pass always creates with a fixed desc, generated from
		// each field's own [Size]/[Format] annotation (plus [Always] for the
		// creation flags, or [Always]+[Recreate]+[RecreateFlags] for a field
		// that needs its original chain link before recreating a new one). A
		// field that ALSO carries [Optional] creates only under that
		// condition -- need_always() (above) emits a complementary need() for
		// the SAME field under the negated condition, using the same
		// [Always] flags, e.g. a [Multiple] pass where instance 0 creates a
		// shared resource and every other instance just needs it (see
		// PSSM_Cascade, pssm.sig). Called by TypedPass::setup() after
		// setup_func returns true - not a substitute for setup_func's own
		// create()/recreate() calls for anything whose Desc depends on
		// runtime state.
		static void create_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.create(data.VSM_PageTable, { ivec3(ivec2(Constants::VSM_PagesPerLevelSide, Constants::VSM_PagesPerLevelSide), 0), HAL::Format::R32_UINT, Constants::MaxLevels, 1 }, FrameGraph::ResourceFlags::CopyDest | FrameGraph::ResourceFlags::Static);
			builder.create(data.VSM_PageCameras, { 416 }, FrameGraph::ResourceFlags::CopyDest | FrameGraph::ResourceFlags::Static);
			builder.create(data.VSM_PageHiZ, { ivec3(ivec2(Constants::VSM_PageSize, Constants::VSM_PageSize), 0), HAL::Format::R32G32_FLOAT, Constants::VSM_PhysicalPageCount, Constants::VSM_PyramidMipCount }, FrameGraph::ResourceFlags::UnorderedAccess | FrameGraph::ResourceFlags::Static);
		}
		// Resources this pass touches, in declaration order, each paired with
		// whether the pass writes it (own [Write], or the view usage's
		// [Write] / [Write = {leaves...}] for resources inside a view group).
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
			{ ResourceID::VSM_Atlas, true },
			{ ResourceID::VSM_PageTable, true },
			{ ResourceID::VSM_PageCameras, true },
			{ ResourceID::VSM_PageHiZ, true },
			{ ResourceID::VSM_DispatchCommands, false },
			{ ResourceID::VSM_LevelDispatchInfo, false },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"VSM_RenderPages"};

	static constexpr PassID ID = PassID::VSM_RenderPages;


	using setup_func_type = std::function<FrameGraph::SetupResult(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	setup_func_type setup_func;
	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::General;
};

}
