// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"
#include "GBuffer.h"
using namespace FrameGraph;

namespace Passes
{

class VSM_ScreenSpaceShadow : public PassNodeBase
{
public:
	struct Context
	{

		GBuffer gbuffer;

		Handlers::Texture VSM_AmbiguousMask = ResourceID::VSM_AmbiguousMask;


		Handlers::Texture VSM_ContactShadow = ResourceID::VSM_ContactShadow;


		// Resources this pass always needs whenever it runs, generated from
		// each field's own [Always=X] annotation (further gated by [Optional=X]
		// when present -- a raw bool expression, e.g. builder.exists(...) or a
		// context-read flag, deciding whether this specific field is actually
		// needed this frame). Called by TypedPass::setup() after setup_func
		// returns true - not a substitute for setup_func's own need()/create()
		// calls for anything else conditional.
		static void need_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.need(data.VSM_AmbiguousMask, FrameGraph::ResourceFlags::Read);
		}

		// Resources this pass always creates with a fixed desc, generated from
		// each field's own [Size]/[Format] annotation (plus [Always] for the
		// creation flags, or [Always]+[Recreate]+[RecreateFlags] for a field
		// that needs its original chain link before recreating a new one).
		// Called by TypedPass::setup() after setup_func returns true - not a
		// substitute for setup_func's own create()/recreate() calls for
		// anything whose Desc depends on runtime state.
		static void create_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.create(data.VSM_ContactShadow, { ivec3(builder.graph->get_context<Table::ViewportContext>().frame_size, 0), HAL::Format::R8_UNORM, 1, 1 }, FrameGraph::ResourceFlags::UnorderedAccess);
		}
		// Resources this pass touches, in declaration order, each paired with
		// whether the pass writes it (own [Write], or the view usage's
		// [Write] / [Write = {leaves...}] for resources inside a view group).
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
			{ ResourceID::GBuffer_Albedo, false },
			{ ResourceID::GBuffer_Normals, false },
			{ ResourceID::GBuffer_Depth, false },
			{ ResourceID::GBuffer_Specular, false },
			{ ResourceID::GBuffer_Speed, false },
			{ ResourceID::GBuffer_DepthMips, false },
			{ ResourceID::GBuffer_Quality, false },
			{ ResourceID::GBuffer_NormalsPrev, false },
			{ ResourceID::GBuffer_SpecularPrev, false },
			{ ResourceID::GBuffer_DepthPrev, false },
			{ ResourceID::VSM_AmbiguousMask, false },
			{ ResourceID::VSM_ContactShadow, true },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"VSM_ScreenSpaceShadow"};

	static constexpr PassID ID = PassID::VSM_ScreenSpaceShadow;


	using setup_func_type = std::function<FrameGraph::SetupResult(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	setup_func_type setup_func;
	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::Compute;
};

}
