// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "../PassNodeBase.h"

using namespace FrameGraph;

namespace Passes
{

class VSM_BlockerClassify : public PassNodeBase
{
public:
	struct Context
	{


		Handlers::Texture GBuffer_Albedo = ResourceID::GBuffer_Albedo;


		Handlers::Texture GBuffer_Normals = ResourceID::GBuffer_Normals;


		Handlers::Texture GBuffer_Specular = ResourceID::GBuffer_Specular;


		Handlers::Texture GBuffer_Speed = ResourceID::GBuffer_Speed;


		Handlers::Texture GBuffer_DepthMips = ResourceID::GBuffer_DepthMips;


		Handlers::Texture VSM_PageTable = ResourceID::VSM_PageTable;

		Handlers::StructuredBuffer<Table::Camera> VSM_PageCameras = ResourceID::VSM_PageCameras;


		Handlers::Texture VSM_PageHiZ = ResourceID::VSM_PageHiZ;


		Handlers::StructuredBuffer<uint2> VSM_LitTiles = ResourceID::VSM_LitTiles;


		Handlers::StructuredBuffer<uint2> VSM_DarkTiles = ResourceID::VSM_DarkTiles;


		Handlers::StructuredBuffer<uint2> VSM_SearchTiles = ResourceID::VSM_SearchTiles;


		// Resources this pass always needs whenever it runs, generated from
		// each field's own [Always=X] annotation (further gated by [Optional=X]
		// when present -- a raw bool expression, e.g. builder.exists(...) or a
		// context-read flag, deciding whether this specific field is actually
		// needed this frame), or, for a View-typed field (e.g. `GBuffer
		// gbuffer;`), every leaf the View itself marks [Always=X] that this
		// pass's own [Write=...] on that field doesn't already cover. Called
		// by TypedPass::setup() after setup_func returns true - not a
		// substitute for setup_func's own need()/create() calls for anything
		// else conditional.
		static void need_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.need(data.GBuffer_Albedo, FrameGraph::ResourceFlags::Read);
			builder.need(data.GBuffer_Normals, FrameGraph::ResourceFlags::Read);
			builder.need(data.GBuffer_Specular, FrameGraph::ResourceFlags::Read);
			builder.need(data.GBuffer_Speed, FrameGraph::ResourceFlags::Read);
			builder.need(data.GBuffer_DepthMips, FrameGraph::ResourceFlags::None);
			builder.need(data.VSM_PageTable, FrameGraph::ResourceFlags::Read);
			builder.need(data.VSM_PageCameras, FrameGraph::ResourceFlags::Read);
			builder.need(data.VSM_PageHiZ, FrameGraph::ResourceFlags::Read);
		}

		// Resources this pass always creates with a fixed desc, generated from
		// each field's own [Size]/[Format] annotation (plus [Always] for the
		// creation flags, or [Always]+[Recreate]+[RecreateFlags] for a field
		// that needs its original chain link before recreating a new one).
		// Called by TypedPass::setup() after setup_func returns true - not a
		// substitute for setup_func's own create()/recreate() calls for
		// anything whose Desc depends on runtime state.
		static void create_always(Context& data, FrameGraph::TaskBuilder& builder)
		{
			builder.create(data.VSM_LitTiles, { 2 * (size_t)(((builder.graph->get_context<Table::ViewportContext>().frame_size.x + 15) / 16) * ((builder.graph->get_context<Table::ViewportContext>().frame_size.y + 15) / 16)), true }, FrameGraph::ResourceFlags::UnorderedAccess);
			builder.create(data.VSM_DarkTiles, { 2 * (size_t)(((builder.graph->get_context<Table::ViewportContext>().frame_size.x + 15) / 16) * ((builder.graph->get_context<Table::ViewportContext>().frame_size.y + 15) / 16)), true }, FrameGraph::ResourceFlags::UnorderedAccess);
			builder.create(data.VSM_SearchTiles, { 2 * (size_t)(((builder.graph->get_context<Table::ViewportContext>().frame_size.x + 15) / 16) * ((builder.graph->get_context<Table::ViewportContext>().frame_size.y + 15) / 16)), true }, FrameGraph::ResourceFlags::UnorderedAccess);
		}
		// Resources this pass touches, in declaration order, each paired with
		// whether the pass writes it (own [Write], or the view usage's
		// [Write] / [Write = {leaves...}] for resources inside a view group).
		static inline const FrameGraph::ResourceAccess resource_accesses[] = {
			{ ResourceID::GBuffer_Albedo, false },
			{ ResourceID::GBuffer_Normals, false },
			{ ResourceID::GBuffer_Specular, false },
			{ ResourceID::GBuffer_Speed, false },
			{ ResourceID::GBuffer_DepthMips, false },
			{ ResourceID::VSM_PageTable, false },
			{ ResourceID::VSM_PageCameras, false },
			{ ResourceID::VSM_PageHiZ, false },
			{ ResourceID::VSM_LitTiles, true },
			{ ResourceID::VSM_DarkTiles, true },
			{ ResourceID::VSM_SearchTiles, true },
		};
		static constexpr uint resource_count = std::size(resource_accesses);
	};


	std::span<const FrameGraph::ResourceAccess> GetUsedResourcesList() const override
	{
		return std::span<const FrameGraph::ResourceAccess>(Context::resource_accesses, Context::resource_count);
	}

	static constexpr LiteralWStr Name{L"VSM_BlockerClassify"};

	static constexpr PassID ID = PassID::VSM_BlockerClassify;


	using setup_func_type = std::function<FrameGraph::SetupResult(Context&, FrameGraph::TaskBuilder&)>;
	using render_func_type = std::function<void(Context&, FrameGraph::FrameContext&)>;


	setup_func_type setup_func;
	render_func_type render_func;

	const FrameGraph::PassFlags flags = FrameGraph::PassFlags::Compute;
};

}
