// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
struct Clear_Constants
{
	float gDebug; // float
	float gViewZScale; // float
	float gDenoisingRange; // float
	uint gOut; // RWTexture2D<float4>
	float GetGDebug() { return gDebug; }
	float GetGViewZScale() { return gViewZScale; }
	float GetGDenoisingRange() { return gDenoisingRange; }
	RWTexture2D<float4> GetGOut() { return ResourceDescriptorHeap[gOut]; }
};