// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
struct Countour
{
	float4 color; // float4
	uint selected_id; // uint
	uint object_ids; // Texture2D<uint>
	float4 GetColor() { return color; }
	uint GetSelected_id() { return selected_id; }
	Texture2D<uint> GetObject_ids() { return ResourceDescriptorHeap[object_ids]; }
};