// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
#include "DDGIInfo.h"
#include "DDGIProbes.h"
struct DDGIProbeTraceData
{
	uint probe_radiance; // RWTexture2D<float4>
	uint probe_gbuffer; // RWTexture2D<float4>
	DDGIInfo info; // DDGIInfo
	DDGIProbes probes; // DDGIProbes
	DDGIInfo GetInfo() { return info; }
	DDGIProbes GetProbes() { return probes; }
	RWTexture2D<float4> GetProbe_radiance() { return ResourceDescriptorHeap[probe_radiance]; }
	RWTexture2D<float4> GetProbe_gbuffer() { return ResourceDescriptorHeap[probe_gbuffer]; }
};