// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
#include "DDGIInfo.h"
#include "DDGIProbes.h"
namespace GI
{
	namespace DDGI
	{
		struct DDGIProbeSelectData
		{
			DDGIInfo info; // DDGIInfo
			DDGIProbes probes; // DDGIProbes
			DDGIInfo GetInfo() { return info; }
			DDGIProbes GetProbes() { return probes; }
		};
	}
}
using GI::DDGI::DDGIProbeSelectData;