// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
namespace Dev
{
	struct DebugViewDraw
	{
		float4 tint; // float4
		uint read_meshlet_masks; // uint
		uint meshlet_filter; // uint
		uint color_by_meshlet; // uint
		uint meshlet_masks; // StructuredBuffer<uint>
		float4 GetTint() { return tint; }
		uint GetRead_meshlet_masks() { return read_meshlet_masks; }
		uint GetMeshlet_filter() { return meshlet_filter; }
		uint GetColor_by_meshlet() { return color_by_meshlet; }
		StructuredBuffer<uint> GetMeshlet_masks() { return ResourceDescriptorHeap[meshlet_masks]; }
	};
}
using Dev::DebugViewDraw;