// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
#include "DebugStruct.h"
struct DebugInfo
{
	uint debug; // RWStructuredBuffer<DebugStruct>
	uint logCount; // RWStructuredBuffer<uint>
	RWStructuredBuffer<DebugStruct> GetDebug() { return ResourceDescriptorHeap[debug]; }
	RWStructuredBuffer<uint> GetLogCount() { return ResourceDescriptorHeap[logCount]; }
	void LogWrite(uint id, uint4 args)
	{
		uint slot;
		InterlockedAdd(GetLogCount()[0], 1, slot);

		if (slot < 64)
		{
			DebugStruct e;
			e.format_id = id;
			e.args = args;
			GetDebug()[slot] = e;
		}
	}

	void Log(uint id) { LogWrite(id, uint4(0, 0, 0, 0)); }

	void Log(uint id, uint a0) { LogWrite(id, uint4(a0, 0, 0, 0)); }

	void Log(uint id, uint a0, uint a1) { LogWrite(id, uint4(a0, a1, 0, 0)); }

	void Log(uint id, uint a0, uint a1, uint a2) { LogWrite(id, uint4(a0, a1, a2, 0)); }

	void Log(uint id, uint a0, uint a1, uint a2, uint a3) { LogWrite(id, uint4(a0, a1, a2, a3)); }

};