// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
namespace Shadows
{
	namespace Denoise
	{
		struct DenoiserShadow_Filter
		{
			float4x4 ProjectionInverse; // float4x4
			int2 BufferDimensions; // int2
			float2 InvBufferDimensions; // float2
			float DepthSimilaritySigma; // float
			uint t2d_DepthBuffer; // Texture2D<float>
			uint t2d_NormalBuffer; // Texture2D<float16_t3>
			uint sb_tileMetaData; // StructuredBuffer<uint>
			float4x4 GetProjectionInverse() { return ProjectionInverse; }
			int2 GetBufferDimensions() { return BufferDimensions; }
			float2 GetInvBufferDimensions() { return InvBufferDimensions; }
			float GetDepthSimilaritySigma() { return DepthSimilaritySigma; }
			Texture2D<float> GetT2d_DepthBuffer() { return ResourceDescriptorHeap[t2d_DepthBuffer]; }
			Texture2D<float16_t3> GetT2d_NormalBuffer() { return ResourceDescriptorHeap[t2d_NormalBuffer]; }
			StructuredBuffer<uint> GetSb_tileMetaData() { return ResourceDescriptorHeap[sb_tileMetaData]; }
		};
	}
}
using Shadows::Denoise::DenoiserShadow_Filter;