// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
struct DeviceCapabilities
{
	bool rtx_supported; // bool
	bool dlssrr_available; // bool
	bool GetRtx_supported() { return rtx_supported; }
	bool GetDlssrr_available() { return dlssrr_available; }
};