// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"



struct DrawStencil
{
	uint vertices; // StructuredBuffer<float4>
	StructuredBuffer<float4> GetVertices() { return ResourceDescriptorHeap[vertices]; }
};