// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
namespace UI
{
	namespace Text
	{
		struct FontRendering
		{
			uint tex0; // Texture2D<float>
			uint positions; // StructuredBuffer<float4>
			Texture2D<float> GetTex0() { return ResourceDescriptorHeap[tex0]; }
			StructuredBuffer<float4> GetPositions() { return ResourceDescriptorHeap[positions]; }
		};
	}
}
using UI::Text::FontRendering;