// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "FSRConstants.h"



struct FSR
{
	uint source; // Texture2D<float4>
	uint target; // RWTexture2D<float4>
	FSRConstants constants; // FSRConstants
	FSRConstants GetConstants() { return constants; }
	Texture2D<float4> GetSource() { return ResourceDescriptorHeap[source]; }
	RWTexture2D<float4> GetTarget() { return ResourceDescriptorHeap[target]; }
};