// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
struct GatherPipelineGlobal
{
	uint meshes_count; // StructuredBuffer<uint>
	uint commands; // Buffer<uint>
	StructuredBuffer<uint> GetMeshes_count() { return ResourceDescriptorHeap[meshes_count]; }
	Buffer<uint> GetCommands() { return ResourceDescriptorHeap[commands]; }
};