// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================

#pragma once
#include "sig_hlsl.hlsl"
#include "BoxInfo.h"
struct GatherBoxes
{
	uint culledMeshes; // AppendStructuredBuffer<BoxInfo>
	uint visibleMeshes; // AppendStructuredBuffer<uint>
	AppendStructuredBuffer<BoxInfo> GetCulledMeshes() { return ResourceDescriptorHeap[culledMeshes]; }
	AppendStructuredBuffer<uint> GetVisibleMeshes() { return ResourceDescriptorHeap[visibleMeshes]; }
};