// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
struct GBufferDownsampleRT
{
	uint depth; // RenderTarget<float>
	uint color; // RenderTarget<float4>
	Texture2D<float> GetDepth() { return ResourceDescriptorHeap[depth]; }
	Texture2D<float4> GetColor() { return ResourceDescriptorHeap[color]; }
};