// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
struct GBufferQuality
{
	uint ref; // Texture2D<float4>
	Texture2D<float4> GetRef() { return ResourceDescriptorHeap[ref]; }
};