// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
namespace UI
{
	namespace Text
	{
		struct GlyphQuad
		{
			float4 pos; // float4
			float4 uv; // float4
			float4 color; // float4
			uint atlas; // uint
			uint is_color; // uint
			float4 GetPos() { return pos; }
			float4 GetUv() { return uv; }
			float4 GetColor() { return color; }
			uint GetAtlas() { return atlas; }
			uint GetIs_color() { return is_color; }
		};
	}
}
using UI::Text::GlyphQuad;