// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
struct Glyph
{
	float2 pos; // float2
	uint index; // uint
	float4 color; // float4
	float2 GetPos() { return pos; }
	uint GetIndex() { return index; }
	float4 GetColor() { return color; }
};