// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "DispatchArguments.h"



struct InitDispatch
{
	uint counter; // RWStructuredBuffer<uint>
	uint dispatch_data; // RWStructuredBuffer<DispatchArguments>
	RWStructuredBuffer<uint> GetCounter() { return ResourceDescriptorHeap[counter]; }
	RWStructuredBuffer<DispatchArguments> GetDispatch_data() { return ResourceDescriptorHeap[dispatch_data]; }
};