// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
namespace Editor
{
	struct MaterialPreviewInfo
	{
		MaterialCB data; // MaterialCB
		uint textures; // Texture2D<float4>
		uint results; // RWTexture2DArray<float4>
		MaterialCB GetData() { return data; }
		RWTexture2DArray<float4> GetResults() { return ResourceDescriptorHeap[results]; }
		Texture2D<float4> GetTextures(int i)
		{
			StructuredBuffer<uint> indirection = ResourceDescriptorHeap[textures];
			uint id = indirection[NonUniformResourceIndex(i)];
			return ResourceDescriptorHeap[NonUniformResourceIndex(id)];
		}

	};
}
using Editor::MaterialPreviewInfo;