// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
namespace Meshes
{
	struct MeshInfo
	{
		uint vertex_offset_local; // uint
		uint meshlet_offset_local; // uint
		uint node_offset; // uint
		uint meshlet_count; // uint
		uint object_id; // uint
		uint meshlet_mask_offset; // uint
		uint GetVertex_offset_local() { return vertex_offset_local; }
		uint GetMeshlet_offset_local() { return meshlet_offset_local; }
		uint GetNode_offset() { return node_offset; }
		uint GetMeshlet_count() { return meshlet_count; }
		uint GetObject_id() { return object_id; }
		uint GetMeshlet_mask_offset() { return meshlet_mask_offset; }
	};
}
using Meshes::MeshInfo;