// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================

#pragma once
#include "sig_hlsl.hlsl"
struct PickerBuffer
{
	uint viewBuffer; // RWStructuredBuffer<uint>
	RWStructuredBuffer<uint> GetViewBuffer() { return ResourceDescriptorHeap[viewBuffer]; }
};