// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
#include "Camera.h"
namespace Shadows
{
	namespace PSSM
	{
		struct PSSMDataGlobal
		{
			uint light_buffer; // Texture2D<float>
			uint light_camera; // StructuredBuffer<Camera>
			Texture2D<float> GetLight_buffer() { return ResourceDescriptorHeap[light_buffer]; }
			StructuredBuffer<Camera> GetLight_camera() { return ResourceDescriptorHeap[light_camera]; }
		};
	}
}
using Shadows::PSSM::PSSMDataGlobal;