// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================

#pragma once
#include "sig_hlsl.hlsl"
#include "GBuffer.h"
struct PSSMLighting
{
	uint light_mask; // Texture2D<float>
	GBuffer gbuffer; // GBuffer
	GBuffer GetGbuffer() { return gbuffer; }
	Texture2D<float> GetLight_mask() { return ResourceDescriptorHeap[light_mask]; }
};