// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
#include "REBLURSharedConstants.h"
struct REBLUR_PostBlurTS1Resources
{
	uint gIn_Tiles; // Texture2D<float>
	uint gIn_Normal_Roughness; // Texture2D<float4>
	uint gIn_Data1; // Texture2D<float2>
	uint gIn_ViewZ; // Texture2D<float>
	uint gIn_Diff; // Texture2D<float4>
	uint gOut_Normal_Roughness; // RWTexture2D<float4>
	uint gOut_Diff; // RWTexture2D<float4>
	REBLURSharedConstants sharedConstants; // REBLURSharedConstants
	REBLURSharedConstants GetSharedConstants() { return sharedConstants; }
	Texture2D<float> GetGIn_Tiles() { return ResourceDescriptorHeap[gIn_Tiles]; }
	Texture2D<float4> GetGIn_Normal_Roughness() { return ResourceDescriptorHeap[gIn_Normal_Roughness]; }
	Texture2D<float2> GetGIn_Data1() { return ResourceDescriptorHeap[gIn_Data1]; }
	Texture2D<float> GetGIn_ViewZ() { return ResourceDescriptorHeap[gIn_ViewZ]; }
	Texture2D<float4> GetGIn_Diff() { return ResourceDescriptorHeap[gIn_Diff]; }
	RWTexture2D<float4> GetGOut_Normal_Roughness() { return ResourceDescriptorHeap[gOut_Normal_Roughness]; }
	RWTexture2D<float4> GetGOut_Diff() { return ResourceDescriptorHeap[gOut_Diff]; }
};