// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "GBuffer.h"
struct ReflectionCombine
{
	uint reflection; // Texture2D<float4>
	uint target; // RWTexture2D<float4>
	GBuffer gbuffer; // GBuffer
	GBuffer GetGbuffer() { return gbuffer; }
	Texture2D<float4> GetReflection() { return ResourceDescriptorHeap[reflection]; }
	RWTexture2D<float4> GetTarget() { return ResourceDescriptorHeap[target]; }
};