// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "enums.h"


namespace Raytrace
{
	struct [raypayload] ShadowPayload
	{
		bool hit : read(anyhit,closesthit,miss,caller) : write(anyhit,closesthit,miss,caller);
		float dist : read(closesthit,miss,caller) : write(closesthit,miss,caller);
		bool GetHit() { return hit; }
		float GetDist() { return dist; }
	};
}
using Raytrace::ShadowPayload;