// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
#include "SIGMASharedConstants.h"
namespace Denoise
{
	namespace NRD
	{
		struct SIGMA_CopyResources
		{
			uint gIn_Tiles; // Texture2D<float2>
			uint gIn_History; // Texture2D<float4>
			uint gIn_HistoryLength; // Texture2D<uint>
			uint gOut_History; // RWTexture2D<float4>
			uint gOut_HistoryLength; // RWTexture2D<uint>
			SIGMASharedConstants sharedConstants; // SIGMASharedConstants
			SIGMASharedConstants GetSharedConstants() { return sharedConstants; }
			Texture2D<float2> GetGIn_Tiles() { return ResourceDescriptorHeap[gIn_Tiles]; }
			Texture2D<float4> GetGIn_History() { return ResourceDescriptorHeap[gIn_History]; }
			Texture2D<uint> GetGIn_HistoryLength() { return ResourceDescriptorHeap[gIn_HistoryLength]; }
			RWTexture2D<float4> GetGOut_History() { return ResourceDescriptorHeap[gOut_History]; }
			RWTexture2D<uint> GetGOut_HistoryLength() { return ResourceDescriptorHeap[gOut_HistoryLength]; }
		};
	}
}
using Denoise::NRD::SIGMA_CopyResources;