// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
namespace Environment
{
	struct SkyFace
	{
		uint faces; // RWTexture2DArray<float4>
		RWTexture2DArray<float4> GetFaces() { return ResourceDescriptorHeap[faces]; }
	};
}
using Environment::SkyFace;