// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
struct UIRenderState
{
	uint passes_needed; // uint
	uint per_pass; // uint
	uint GetPasses_needed() { return passes_needed; }
	uint GetPer_pass() { return per_pass; }
};