// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
struct VoxelGISelectors
{
	bool voxelize_scene; // bool
	bool light_scene; // bool
	bool reflection_enabled; // bool
	bool debug_voxel_trace; // bool
	bool GetVoxelize_scene() { return voxelize_scene; }
	bool GetLight_scene() { return light_scene; }
	bool GetReflection_enabled() { return reflection_enabled; }
	bool GetDebug_voxel_trace() { return debug_voxel_trace; }
};