// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "VoxelTilingParams.h"
struct VoxelZero
{
	uint Target; // RWTexture3D<float4>
	VoxelTilingParams params; // VoxelTilingParams
	VoxelTilingParams GetParams() { return params; }
	RWTexture3D<float4> GetTarget() { return ResourceDescriptorHeap[Target]; }
};