// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "VoxelTilingParams.h"



struct VoxelMipMap
{
	uint SrcMip; // Texture3D<float4>
	uint OutMips_0; // RWTexture3D<float4> [was OutMips[3]]
	uint OutMips_1; // RWTexture3D<float4> [was OutMips[3]]
	uint OutMips_2; // RWTexture3D<float4> [was OutMips[3]]
	VoxelTilingParams params; // VoxelTilingParams
	VoxelTilingParams GetParams() { return params; }
	RWTexture3D<float4> GetOutMips(int i)
	{
		if (i == 0) return ResourceDescriptorHeap[OutMips_0];
		if (i == 1) return ResourceDescriptorHeap[OutMips_1];
		              return ResourceDescriptorHeap[OutMips_2];
	}

	Texture3D<float4> GetSrcMip() { return ResourceDescriptorHeap[SrcMip]; }
};