// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
struct VSMBlockerSearchOutput
{
	uint blocker_search_result; // RWTexture2D<uint4>
	RWTexture2D<uint4> GetBlocker_search_result() { return ResourceDescriptorHeap[blocker_search_result]; }
};