// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "DispatchArguments.h"
struct VSMBlockerClassifyInitDispatch
{
	uint lit_counter; // StructuredBuffer<uint>
	uint dark_counter; // StructuredBuffer<uint>
	uint search_counter; // StructuredBuffer<uint>
	uint lit_dispatch_data; // RWStructuredBuffer<DispatchArguments>
	uint dark_dispatch_data; // RWStructuredBuffer<DispatchArguments>
	uint search_dispatch_data; // RWStructuredBuffer<DispatchArguments>
	StructuredBuffer<uint> GetLit_counter() { return ResourceDescriptorHeap[lit_counter]; }
	StructuredBuffer<uint> GetDark_counter() { return ResourceDescriptorHeap[dark_counter]; }
	StructuredBuffer<uint> GetSearch_counter() { return ResourceDescriptorHeap[search_counter]; }
	RWStructuredBuffer<DispatchArguments> GetLit_dispatch_data() { return ResourceDescriptorHeap[lit_dispatch_data]; }
	RWStructuredBuffer<DispatchArguments> GetDark_dispatch_data() { return ResourceDescriptorHeap[dark_dispatch_data]; }
	RWStructuredBuffer<DispatchArguments> GetSearch_dispatch_data() { return ResourceDescriptorHeap[search_dispatch_data]; }
};