// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
struct VSMDirtyPageInfo
{
	uint physical_slot; // uint
	uint level; // uint
	uint page_x; // uint
	uint page_y; // uint
	uint GetPhysical_slot() { return physical_slot; }
	uint GetLevel() { return level; }
	uint GetPage_x() { return page_x; }
	uint GetPage_y() { return page_y; }
};