// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
#include "VSMPageBatch.h"
namespace Shadows
{
	namespace VSM
	{
		struct VSMLevelDispatchInfo
		{
			uint page_batch_cb; // VSMPageBatch
			float2 bounds_min; // float2
			float2 bounds_max; // float2
			uint GetPage_batch_cb() { return page_batch_cb; }
			float2 GetBounds_min() { return bounds_min; }
			float2 GetBounds_max() { return bounds_max; }
		};
	}
}
using Shadows::VSM::VSMLevelDispatchInfo;