// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
#include "Camera.h"
#include "GBuffer.h"
struct VSMLighting
{
	uint vsm_atlas; // Texture2DArray<float>
	uint page_table; // Texture2DArray<uint>
	uint page_cameras; // StructuredBuffer<Camera>
	uint blue_noise; // Texture2D<float2>
	uint rtx_shadow_mask; // Texture2D<float>
	uint contact_shadow; // Texture2D<float>
	uint result; // RWTexture2D<float4>
	uint shadow_noise; // RWTexture2D<float>
	GBuffer gbuffer; // GBuffer
	GBuffer GetGbuffer() { return gbuffer; }
	Texture2DArray<float> GetVsm_atlas() { return ResourceDescriptorHeap[vsm_atlas]; }
	Texture2DArray<uint> GetPage_table() { return ResourceDescriptorHeap[page_table]; }
	StructuredBuffer<Camera> GetPage_cameras() { return ResourceDescriptorHeap[page_cameras]; }
	RWTexture2D<float4> GetResult() { return ResourceDescriptorHeap[result]; }
	Texture2D<float2> GetBlue_noise() { return ResourceDescriptorHeap[blue_noise]; }
	Texture2D<float> GetRtx_shadow_mask() { return ResourceDescriptorHeap[rtx_shadow_mask]; }
	Texture2D<float> GetContact_shadow() { return ResourceDescriptorHeap[contact_shadow]; }
	RWTexture2D<float> GetShadow_noise() { return ResourceDescriptorHeap[shadow_noise]; }
};