// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by SigParser from .sig files in sources/SIGParser/sigs/
// Changes will be lost on next generation. Edit the .sig source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
struct VSMSelectors
{
	bool use_vsm_contact_shadow; // bool
	VSMDebugView vsm_debug_view; // VSMDebugView
	bool GetUse_vsm_contact_shadow() { return use_vsm_contact_shadow; }
	VSMDebugView GetVsm_debug_view() { return vsm_debug_view; }
};