// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
#pragma once
#include "sig_hlsl.hlsl"
#include "enums.h"
#include "GBuffer.h"
namespace Dev
{
	struct WorkGraphTest
	{
		uint output; // RWTexture2D<float4>
		uint target; // RWTexture2D<float4>
		GBuffer gbuffer; // GBuffer
		GBuffer GetGbuffer() { return gbuffer; }
		RWTexture2D<float4> GetOutput() { return ResourceDescriptorHeap[output]; }
		RWTexture2D<float4> GetTarget() { return ResourceDescriptorHeap[target]; }
	};
}
using Dev::WorkGraphTest;