// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.Meshes.GatherPipeline;
import Core;
import :Autogen.Tables.Meshes.GatherPipeline;
import :Autogen.Layouts.Frame.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace Meshes
	{
		struct GatherPipeline :public DataHolder<GatherPipeline, SlotID::GatherPipeline, Table::Meshes::GatherPipeline, ::Frame::DefaultLayout::Instance1>
		{
			static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
			GatherPipeline() = default;
		};
	}
}