// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.Meshes.MaterialInfo;
import Core;
import :Autogen.Tables.Meshes.MaterialInfo;
import :Autogen.Layouts.Frame.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace Meshes
	{
		struct MaterialInfo :public DataHolder<MaterialInfo, SlotID::MaterialInfo, Table::Meshes::MaterialInfo, ::Frame::DefaultLayout::MaterialData>
		{
			static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
			MaterialInfo() = default;
		};
	}
}