#include "Math.h"
import serialization;
/*
CEREAL_REGISTER_TYPE(AABB)
CEREAL_REGISTER_TYPE(Frustum)
CEREAL_REGISTER_TYPE(Plane)
CEREAL_REGISTER_TYPE(Primitive)
CEREAL_REGISTER_TYPE(Ray)
CEREAL_REGISTER_TYPE(Sphere)


BOOST_CLASS_EXPORT_IMPLEMENT(AABB)
BOOST_CLASS_EXPORT_IMPLEMENT(Frustum)
BOOST_CLASS_EXPORT_IMPLEMENT(Plane)
BOOST_CLASS_EXPORT_IMPLEMENT(Primitive)
BOOST_CLASS_EXPORT_IMPLEMENT(Ray)
BOOST_CLASS_EXPORT_IMPLEMENT(Sphere)*/