#include "Math.h"
import serialization;

BOOST_CLASS_EXPORT_KEY(AABB)
BOOST_CLASS_EXPORT_KEY(Frustum)
BOOST_CLASS_EXPORT_KEY(Plane)
BOOST_CLASS_EXPORT_KEY(Primitive)
BOOST_CLASS_EXPORT_KEY(Ray)
BOOST_CLASS_EXPORT_KEY(Sphere)


BOOST_CLASS_EXPORT_IMPLEMENT(AABB)
BOOST_CLASS_EXPORT_IMPLEMENT(Frustum)
BOOST_CLASS_EXPORT_IMPLEMENT(Plane)
BOOST_CLASS_EXPORT_IMPLEMENT(Primitive)
BOOST_CLASS_EXPORT_IMPLEMENT(Ray)
BOOST_CLASS_EXPORT_IMPLEMENT(Sphere)