// ============================================================================
// THIS FILE IS AUTOMATICALLY GENERATED - DO NOT MANUALLY EDIT
// ============================================================================
// Generated by Prism from .prism files in sources/Prism/defs/
// Changes will be lost on next generation. Edit the .prism source files instead.
// ============================================================================
export module HAL:Autogen.Slots.Post.Upscale.FSR;
import Core;
import :Autogen.Tables.Post.Upscale.FSR;
import :Autogen.Layouts.Frame.DefaultLayout;
import :SIG;
import :Types;
import :Enums;
import :Slots;

export namespace Slots
{
	namespace Post
	{
		namespace Upscale
		{
			struct FSR :public DataHolder<FSR, SlotID::FSR, Table::Post::Upscale::FSR, ::Frame::DefaultLayout::Instance0>
			{
				static constexpr SIG_TYPE TYPE = SIG_TYPE::Slot;
				FSR() = default;
			};
		}
	}
}